##########################################
# Country definition for Solomon Islands #
##########################################

country =
{ tag                 = U16
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 10
  capital             = 1622
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 9
    political_left    = 2
    freedom           = 9
    free_market       = 10
    professional_army = 5
    defense_lobby     = 4
    interventionism   = 2
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  ownedprovinces      = { 1622 1685 5871 5870 3132 1684 1614 1683 5868 5869 }
  controlledprovinces = { 1622 1685 5871 5870 3132 1684 1614 1683 5868 5869 }
  nationalprovinces   = { 1622 1685 5871 5870 3132 1684 1614 1683 5868 5869 }

}