##############################
# Country definition for LAO #
##############################

country =
{ tag                 = LAO
  energy              = 100
  metal               = 100
  rare_materials      = 502
  oil                 = 50
  supplies            = 50
  money               = 100
  capital             = 1329
  manpower            = 25
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 4
    political_left    = 10
    freedom           = 3
    free_market       = 3
    professional_army = 5
    defense_lobby     = 8
    interventionism   = 1
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  ownedprovinces      = {
		1329 1332 1589 1306 2950 3118 3119 3117 3116 7987 7024
	}
  controlledprovinces = {
		1329 1332 1589 1306 2950 3118 3119 3117 3116 7987 7024
	}
  nationalprovinces   = {
		1329 1332 1589 1306 2950 3118 3119 3117 3116 7987 7024
	}
  techapps = {
   ###################
   #     Infantry    #
   ###################
   #Infantry
   1010 
   #Motorized
   1100 
   #Mountain
   1160 
   #Special Forces
   1250 
   #Mechanized
   1470
   #Irregular Infantry
   1360
   #Combat Engineers
   1830
   #Supply and Repair
   1990
   ###################
   #Armor & Artillery#
   ###################
   #Main Battle Tanks
   2620
   #Armored Cars
   2860
   #Anti-Air
   2800
   #Armored Personnel Carriers
   2170
   #Field Artillery
   2290 
   #Self-Propelled Anti-Air
   2810
   #Man-Portable Air-Defense Systems
   3000
   #Self-Propelled Artillery
   2220
   #Self-Propelled Rocket Artillery
   2980 
   ###################
   #     Naval       #
   ###################
   #Frigates
   3110
   #Submarines
   3010
   #Transport Ships
   3900
   ###################
   #    Aircraft     #
   ###################
   #Multi-Role
   4500
   #Air Transports
   4250
   ###################
   #    Industry     #
   ###################
   #Light Industry
   5810
   #Heavy Industry
   5130
   #Material Science
   53050
   #Construction Eng.
   5800
   #Agriculture
   5700
   #Oil
   5190
   ###################
   #  Land Doctrines #
   ###################
   6500 
   6510 6530 
   1650
   6560 #Defensive
   ###################
   #  Air Doctrines  #
   ###################
   9190 9200
   }
}
