#####################
# Country main data #
#####################

country =
{ tag                    = JAP
  #belligerence           = 10
  capital                = 1184
  manpower               = 500
  # Resource Reserves
  energy                 = 20000
  metal                  = 10000
  rare_materials         = 5000
  oil                    = 5000
  supplies               = 8000
  money                  = 70000
  transports             = 2000
  escorts                = 4000
  
  #peacetime_ic_mod       = 0.4
  
  diplomacy =
  { relation = { tag = BEL value = -25 }
    relation = { tag = CGX value = -75 }
    relation = { tag = CHC value = -200 }
    relation = { tag = CHI value = -100 }
    relation = { tag = CHL value = 20 }
    relation = { tag = CSX value = -75 }
    relation = { tag = CXB value = -75 }
    relation = { tag = CYN value = -75 }
    relation = { tag = ENG value = -25 }
    relation = { tag = ETH value = 35 }
    relation = { tag = FIN value = 20 }
    relation = { tag = FRA value = -20 }
    relation = { tag = GER value = 20 }
    relation = { tag = HOL value = -50 }
    relation = { tag = MAN value = 200 access = yes }
    relation = { tag = PHI value = 1 }
    relation = { tag = SIA value = 75 }
    relation = { tag = SOV value = -10 }
    relation = { tag = USA value = 15 }
  }
  SpyInfo                = { country = "ENG" NumberOfSpies = 2 }
  SpyInfo                = { country = "FRA" NumberOfSpies = 2 }
  SpyInfo                = { country = "SOV" NumberOfSpies = 5 }
  SpyInfo                = { country = "USA" NumberOfSpies = 3 }
  SpyInfo                = { country = "SIK" NumberOfSpies = 1 }
  SpyInfo                = { country = "TAN" NumberOfSpies = 1 }
  SpyInfo                = { country = "GER" NumberOfSpies = 2 }
  SpyInfo                = { country = "CXB" NumberOfSpies = 2 }
  SpyInfo                = { country = "CYN" NumberOfSpies = 2 }
  SpyInfo                = { country = "LUX" NumberOfSpies = 1 }
  SpyInfo                = { country = "POR" NumberOfSpies = 1 }
  SpyInfo                = { country = "ITA" NumberOfSpies = 2 }
  SpyInfo                = { country = "CHI" NumberOfSpies = 4 }
  SpyInfo                = { country = "CGX" NumberOfSpies = 1 }
  SpyInfo                = { country = "PHI" NumberOfSpies = 2 }
  SpyInfo                = { country = "NZL" NumberOfSpies = 1 }
  SpyInfo                = { country = "AST" NumberOfSpies = 2 }
  # Sakhalin
  nationalprovinces      = { 1177 1178 1179 1180 1181 1182 1183 1184 1185 1186 1187 1188 1189 1190 1191 1784 1599 1192 1193 1785 1174 1176  
1436 1437 1399
3061 3062 3063 3064 3065 3066 3067 3068 3069 3070 
3071 3072 3073 3074 3075 3076 3077 3078 3079 3080 
3081 3082 3083 3084 3085 3086 3087 3088 3089
5653 5655
7938 7939 7940 7941 7962 7963 7964 7965 7966 7967 7968 7969 7970 7971
                           }
  ownedprovinces         = { 1178 1179 1180 1181 1182 1183 1184 1185 1186 1187 1188 1189 1190 1191 1784 1599 1192 1193 1785 1174  
1436 1437 1399
3061 3062 3063 3064 3065 3066 3067 3068 3069 3070 
3071 3072 3073 3074 3075 3076 3077 3078 3079 3080 
3081 3082 3083 3084 3085 3086 3087 3088 
5653 5655
7938 7962 7963 7964 7965 7966 7967 7968 
                           }

  controlledprovinces    = { 1178 1179 1180 1181 1182 1183 1184 1185 1186 1187 1188 1189 1190 1191 1784 1599 1192 1193 1785 1174  
1436 1437 1399
3061 3062 3063 3064 3065 3066 3067 3068 3069 3070 
3071 3072 3073 3074 3075 3076 3077 3078 3079 3080 
3081 3082 3083 3084 3085 3086 3087 3088 
5653 5655
7938 7962 7963 7964 7965 7966 7967 7968 
                           }
  claimedprovinces 		 = {}

  inventions = {  }
  blueprints             = { 8180 8230 8310 8320 }
  policy =
  { date              = { year = 0 month = january day = 0 }
     democratic        = 10
     political_left    = 2 
     freedom           = 10#3 
     free_market       = 10 
     professional_army = 6 
     defense_lobby     = 4 
     interventionism   = 4 
  }
}
 
