##############################
# Country definition for JOR #
##############################

country =
{ tag                 = JOR
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 10
  capital             = 1796
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 3
    political_left    = 3
    freedom           = 3
    free_market       = 5
    professional_army = 5
    defense_lobby     = 8
    interventionism   = 7
  }
  diplomacy = { 
	relation = { tag = USA value = -25 }
	}
  headofstate            = {  type = 9 id = 370001  } 
  headofgovernment       = {  type = 9 id = 370002  } 
  foreignminister        = {  type = 9 id = 370003  } 
  armamentminister       = {  type = 9 id = 370004  } 
  ministerofsecurity     = {  type = 9 id = 370005  } 
  ministerofintelligence = {  type = 9 id = 370006  } 
  chiefofstaff           = {  type = 9 id = 370007  } 
  chiefofarmy            = {  type = 9 id = 370008  } 
  chiefofnavy            = {  type = 9 id = 370009  } 
  chiefofair             = {  type = 9 id = 370010  } 
  
  ownedprovinces      = {
1796 1882 1802 407 1803 4166 
	}
  controlledprovinces = {
1796 1882 1802 407 1803 4166 
	}
  nationalprovinces   = {
1796 1882 1802 407 1803 4166 4167 1797
	}

}
