#################################
# Country definition for Kuwait #
#################################
province = { id = 1041 energy = 115 ic = 6 } #Kuwait

##################### 
# Country main data # 
##################### 

country =
{ tag                 = U91
  energy              = 10000
  metal               = 1000
  rare_materials      = 500
  oil                 = 8000
  supplies            = 500
  money               = 2000
  capital             = 1822
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 3
    political_left    = 3
    freedom           = 3
    free_market       = 6
    professional_army = 5
    defense_lobby     = 8
    interventionism   = 8
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  ownedprovinces      = { 6499 1822 }
  controlledprovinces = { 6499 1822 }
  nationalprovinces   = { 6499 1822 }

}
