##############################
# Country definition for LAO #
##############################

country =
{ tag                 = LAO
  energy              = 100
  metal               = 100
  rare_materials      = 502
  oil                 = 50
  supplies            = 50
  money               = 100
  capital             = 1329
  manpower            = 25
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 4
    political_left    = 10
    freedom           = 3
    free_market       = 3
    professional_army = 5
    defense_lobby     = 8
    interventionism   = 1
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  ownedprovinces      = {
		1329 1332 1589 1306 2950 3118 3119 3117 3116 7987 7024
	}
  controlledprovinces = {
		1329 1332 1589 1306 2950 3118 3119 3117 3116 7987 7024
	}
  nationalprovinces   = {
		1329 1332 1589 1306 2950 3118 3119 3117 3116 7987 7024
	}

}
