##############################
# Country definition for YEM #
##############################

country =
{ tag                    = U43
  # Resource Reserves
  energy                 = 200
  metal                  = 200
  rare_materials         = 200
  oil                    = 200
  supplies               = 200
  money                  = 10
  manpower               = 100
  capital                = 1812
  policy =
  { date              = { year = 0 month = january day = 0 }
     democratic        = 3 
     political_left    = 8
     freedom           = 1 
     free_market       = 8
     professional_army = 2 
     defense_lobby     = 8 
     interventionism   = 4 
  }
  nationalprovinces      = { 1812 1813 1814 2855 1815 2857 4185 4186 4235 4174 4187 4188 4189 6566 6567 6568 6569 6570 6571 6924 6925 6565 7450 7274 7275 }
  ownedprovinces         = { 1813 1814 1815 4187 4188 4189 6566 6567 6568 6569 6570 6571 6565 7274 7275 }
  controlledprovinces    = { 1813 1814 1815 4187 4188 4189 6566 6567 6568 6569 6570 6571 6565 7274 7275 }
  
  diplomacy =
  { relation = { tag = AST value = 150 }
    relation = { tag = BHU value = 150 }
    relation = { tag = CAN value = 150 }
    relation = { tag = ENG value = 150 }
    relation = { tag = FRA value = 150 }
    relation = { tag = GER value = 1 }
    relation = { tag = IRQ value = 125 }
    relation = { tag = ITA value = 50 }
    relation = { tag = NEP value = 150 }
    relation = { tag = NZL value = 150 }
    relation = { tag = OMN value = 150 }
    relation = { tag = SAF value = 150 }
    relation = { tag = SAU value = 125 }
    relation = { tag = TUR value = 35 }
    relation = { tag = USA value = 100 }
  }
  headofstate            = { type = 9 id = 93001 }
  headofgovernment       = { type = 9 id = 93002 }
  foreignminister        = { type = 9 id = 93003 }
  armamentminister       = { type = 9 id = 93004 }
  ministerofsecurity     = { type = 9 id = 93005 }
  ministerofintelligence = { type = 9 id = 93006 }
  chiefofstaff           = { type = 9 id = 93007 }
  chiefofarmy            = { type = 9 id = 93008 }
  chiefofnavy            = { type = 9 id = 93009 }
  chiefofair             = { type = 9 id = 93010 }
} 
 
