
##################################
# Country definition for Bahrain #
##################################

country =
{ tag                 = CGX
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 1000
  capital             = 1906
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 3
    political_left    = 2
    freedom           = 3
    free_market       = 6
    professional_army = 1
    defense_lobby     = 6
    interventionism   = 3
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  ownedprovinces      = { 1906 7004 }
  controlledprovinces = { 1906 7004 }
  nationalprovinces   = { 1906 7004 }

}