
##############################
# Country definition for SUD #
##############################

country =
{ tag                 = U42
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 10
  capital             = 1286
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 3
    political_left    = 4
    freedom           = 3
    free_market       = 5
    professional_army = 5
    defense_lobby     = 8
    interventionism   = 8
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
	
   headofstate            = {  type = 9 id = 1025001  } 
   headofgovernment       = {  type = 9 id = 1025002  } 
   
  ownedprovinces      = { 1285 1286 1288 1590 5198 5195 5196 5197 7305 7925 7926 }
  controlledprovinces = { 1285 1286 1288 1590 5198 5195 5196 5197 7305 7925 7926 }
  nationalprovinces   = { 1285 1286 1288 1590 5198 5195 5196 5197 7305 7925 7926 5204 1457 5208 7924 5207 1519 1456 5206 }

}