
###################################
# Country definition for Botswana #
###################################

country =
{ tag                 = U41
  energy              = 1000
  metal               = 100
  rare_materials      = 500
  oil                 = 500
  supplies            = 500
  money               = 10
  capital             = 1112
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 7
    political_left    = 3
    freedom           = 3
    free_market       = 5
    professional_army = 5
    defense_lobby     = 8
    interventionism   = 8
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  ownedprovinces      = { 4983 4984 4985 4986 2800 1112 4987 4988 4990 1111 1105 4989 4991 }
  controlledprovinces = { 4983 4984 4985 4986 2800 1112 4987 4988 4990 1111 1105 4989 4991 }
  nationalprovinces   = { 4983 4984 4985 4986 2800 1112 4987 4988 4990 1111 1105 4989 4991 }

}