#####################
# Country main data #
#####################

country =
{ tag                    = BUL
  ai = "bul_1985.ai"
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 50
  manpower               = 200
  capital                = 417
  transports             = 10
  escorts                = 4
  
  diplomacy = {}
  
  SpyInfo                = { country = "ENG" NumberOfSpies = 1 }
  SpyInfo                = { country = "FRA" NumberOfSpies = 1 }
  SpyInfo                = { country = "SOV" NumberOfSpies = 1 }
  SpyInfo                = { country = "CZE" NumberOfSpies = 1 }
  SpyInfo                = { country = "AUS" NumberOfSpies = 1 }
  SpyInfo                = { country = "GER" NumberOfSpies = 1 }
  SpyInfo                = { country = "HUN" NumberOfSpies = 1 }
  SpyInfo                = { country = "ALB" NumberOfSpies = 1 }
  SpyInfo                = { country = "GRE" NumberOfSpies = 1 }
  SpyInfo                = { country = "ROM" NumberOfSpies = 1 }
  SpyInfo                = { country = "ITA" NumberOfSpies = 1 }
  nationalprovinces      = { 
417 419 420 422 421 416 413 414 410 423 2323 2324 1911 
2612 2610 3374 3397 3352 3353 3354 435 6564 6563 6505 7337 6506 6507
  }
  ownedprovinces         = { 419 420 422 421 417 416 2323 2324 1911
2612
3352 3353 3354
6506 6507 6510 7337 423
  }
  controlledprovinces    = { 419 420 422 421 417 416 2323 2324 1911
2612
3352 3353 3354
6506 6507 6510 7337 423
  }
  claimedprovinces  	 = { 
1169 411 412 3055 3393 2321 2322 3398 436 2449 6510 1168 6562 6508 6511 7352 7055 7319 2319
  }

  inventions = {  }
  policy =
  { date              = { year = 0 month = january day = 0 }
     democratic        = 1 
     political_left    = 10
     free_market       = 4
     freedom           = 3 
     professional_army = 3 
     defense_lobby     = 6 
     interventionism   = 6
  }
  headofstate            = { type = 9 id = 19001 }
  headofgovernment       = { type = 9 id = 19002 }
  foreignminister        = { type = 9 id = 19003 }
  armamentminister       = { type = 9 id = 19004 }
  ministerofsecurity     = { type = 9 id = 19005 }
  ministerofintelligence = { type = 9 id = 19006 }
  chiefofstaff           = { type = 9 id = 19007 }
  chiefofarmy            = { type = 9 id = 19008 }
  chiefofnavy            = { type = 9 id = 19009 }
  chiefofair             = { type = 9 id = 19010 }
}