
#######################################
# Country definition for Burkina Faso #
#######################################

country =
{ tag                 = U81
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 10
  capital             = 997
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 2
    political_left    = 8
    freedom           = 2
    free_market       = 2
    professional_army = 5
    defense_lobby     = 8
    interventionism   = 3
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  ownedprovinces      = { 997 996 2784
4555 4556 4557 4558 4559 4560 4561 4562 4563 4564 4565
7903 7902
	}
  controlledprovinces = { 997 996 2784
4555 4556 4557 4558 4559 4560 4561 4562 4563 4564 4565
7903 7902
	}
  nationalprovinces   = { 997 996 2784
4555 4556 4557 4558 4559 4560 4561 4562 4563 4564 4565
7903 7902
	}
	
}