
##################################
# Country definition for Burundi #
##################################

country =
{ tag                 = U48
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 10
  capital             = 2283
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 3
    political_left    = 3
    freedom           = 4
    free_market       = 7
    professional_army = 5
    defense_lobby     = 8
    interventionism   = 2
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  ownedprovinces      = { 2283 7037 4731 }
  controlledprovinces = { 2283 7037 4731 }
  nationalprovinces   = { 2283 7037 4731 }

}