###################################
# Country definition for Cambodia #
###################################

country =
{ tag                 = CMB
  energy              = 1000
  metal               = 100
  rare_materials      = 500
  oil                 = 500
  supplies            = 500
  money               = 10
  capital             = 1339
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 3
    political_left    = 7
    freedom           = 2
    free_market       = 2
    professional_army = 1
    defense_lobby     = 6
    interventionism   = 3
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
	
	ownedprovinces =      { 1339 1340 1341 1336 3121 3120 3122 7025 7908 7026 7909 7910 }
	controlledprovinces = { 1339 1340 1341 1336 3121 3120 3122 7025 7908 7026 7909 7910 }
	nationalprovinces =   { 1339 1340 1341 1336 3121 3120 3122 7025 7908 7026 7909 7910 }
    claimedprovinces =    { 7906 }

}