
#####################################
# Country definition for Cape Verde #
#####################################

country =
{ tag                 = U07
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 10
  capital             = 1146
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 9
    political_left    = 2
    freedom           = 9
    free_market       = 10
    professional_army = 5
    defense_lobby     = 4
    interventionism   = 2
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  ownedprovinces      = { 1146 7440 7441 }
  controlledprovinces = { 1146 7440 7441 }
  nationalprovinces   = { 1146 7440 7441 }

}