
##############################
# Country definition for  #
##############################

country =
{ tag                 = U82
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 10
  capital             = 1078
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 3
    political_left    = 3
    freedom           = 4
    free_market       = 6
    professional_army = 5
    defense_lobby     = 2
    interventionism   = 8
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  ownedprovinces      = { 1078 1070 2746
4755 4756 4757 4758 4759 4760 4761 4762 4763
7333 7332 7331 7330 7329
	}
  controlledprovinces = { 1078 1070 2746
4755 4756 4757 4758 4759 4760 4761 4762 4763
7333 7332 7331 7330 7329
	}
  nationalprovinces   = { 1078 1070 2746
4755 4756 4757 4758 4759 4760 4761 4762 4763
7333 7332 7331 7330 7329
	}

}