
#######################################
# Country definition for French Congo #
#######################################

country =
{ tag                 = U85
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 10
  capital             = 1075
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 3
    political_left    = 7
    freedom           = 4
    free_market       = 3
    professional_army = 5
    defense_lobby     = 8
    interventionism   = 8
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  ownedprovinces      = { 1075 1076 2750 2748 2747
4883 4884 4885 4886 4887 4888 4889 4890 4891
7339
	}
  controlledprovinces = { 1075 1076 2750 2748 2747
4883 4884 4885 4886 4887 4888 4889 4890 4891
7339
	}
  nationalprovinces   = { 1075 1076 2750 2748 2747
4883 4884 4885 4886 4887 4888 4889 4890 4891
7339
	}

}