
###################################
# Country definition for Djibouti #
###################################

country =
{ tag                 = U80
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 10
  capital             = 1037
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 8
    political_left    = 10
    freedom           = 6
    free_market       = 5
    professional_army = 5
    defense_lobby     = 8
    interventionism   = 5
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  ownedprovinces      = { 1037 6943 }
  controlledprovinces = { 1037 6943 }
  nationalprovinces   = { 1037 6943 }

}