###############################
# Country definition for Fiji #
###############################

country =
{ tag                 = U11
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 10
  capital             = 1609
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 9
    political_left    = 2
    freedom           = 9
    free_market       = 10
    professional_army = 5
    defense_lobby     = 4
    interventionism   = 2
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  ownedprovinces      = { 1609 1611 7214 7215 7216 7217 }
  controlledprovinces = { 1609 1611 7214 7215 7216 7217 }
  nationalprovinces   = { 1609 1611 7214 7215 7216 7217 }

}