
#################################
# Country definition for Gambia #
#################################

country =
{ tag                 = U86
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 10
  capital             = 982
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 8
    political_left    = 3
    freedom           = 7
    free_market       = 7
    professional_army = 5
    defense_lobby     = 4
    interventionism   = 4
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  headofstate            = {  type = 9 id = 1245001  } 
  headofgovernment       = {  type = 9 id = 1245002  } 
  foreignminister        = {  type = 9 id = 1245003  } 
  armamentminister       = {  type = 9 id = 1245004  } 
  ministerofsecurity     = {  type = 9 id = 1245005  } 
  ministerofintelligence = {  type = 9 id = 1245006  } 
  chiefofstaff           = {  type = 9 id = 1245007  } 
  chiefofarmy            = {  type = 9 id = 1245008  } 
  chiefofnavy            = {  type = 9 id = 1245009  } 
  chiefofair             = {  type = 9 id = 1245010  } 
  
  ownedprovinces      = { 982 4463 }
  controlledprovinces = { 982 4463 }
  nationalprovinces   = { 982 4463 }

}