
##############################
# Country definition for GUI #
##############################

country =
{ tag                 = GUI
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 10
  capital             = 987
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 3
    political_left    = 3
    freedom           = 3
    free_market       = 5
    professional_army = 5
    defense_lobby     = 8
    interventionism   = 8
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  headofstate            = {  type = 9 id = 665001  } 
  headofgovernment       = {  type = 9 id = 665002  } 
  foreignminister        = {  type = 9 id = 665003  } 
  armamentminister       = {  type = 9 id = 665004  } 
  ministerofsecurity     = {  type = 9 id = 665005  } 
  ministerofintelligence = {  type = 9 id = 665006  } 
  chiefofstaff           = {  type = 9 id = 665007  } 
  chiefofarmy            = {  type = 9 id = 665008  } 
  chiefofnavy            = {  type = 9 id = 665009  } 
  chiefofair             = {  type = 9 id = 665010  } 
  
  ownedprovinces      = { 987 990 991 4465 4466 4467 4468 4469 4470 4471 4472
	}
  controlledprovinces = { 987 990 991 4465 4466 4467 4468 4469 4470 4471 4472
	}
  nationalprovinces   = { 987 990 991 983
4464 4465 4466 4467 4468 4469 4470 4471 4472
	}

}