
##############################
# Country definition for ISR #
##############################

country =
{ tag                 = ISR
    energy              = 1000
  metal               = 1000
  rare_materials      = 500
  oil                 = 500
  supplies            = 50
  money               = 100
  capital             = 1008 #2760
  manpower            = 1
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 8
    political_left    = 3
    freedom           = 8
    free_market       = 10
    professional_army = 4
    defense_lobby     = 10
    interventionism   = 10
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  ownedprovinces      = {
		1798  1881 404 406 7290 7283 7282 7286 7284 7285 1797 1799
	}
  controlledprovinces = {
		1798  1881 404 406 7290 7283 7282 7286 7284 7285 1797 1799
	}
  nationalprovinces   = {
		1798  1881 404 406 7290 7283 7282 7286 7284 7285
	}
  claimedprovinces = { 1795 1797 1799 1800 1801 2899 4604 4605 }
  
}
