##############################
# Country definition for LEB #
##############################

country =
{ tag                 = LEB
  energy              = 100
  metal               = 1000
  rare_materials      = 500
  oil                 = 500
  supplies            = 50
  money               = 100
  capital             = 1794
  manpower            = 1
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 8
    political_left    = 2
    freedom           = 3
    free_market       = 5
    professional_army = 5
    defense_lobby     = 8
    interventionism   = 8
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  headofstate            = {  type = 9 id = 375001  } 
  headofgovernment       = {  type = 9 id = 375002  } 
  foreignminister        = {  type = 9 id = 375003  } 
  armamentminister       = {  type = 9 id = 375004  } 
  ministerofsecurity     = {  type = 9 id = 375005  } 
  ministerofintelligence = {  type = 9 id = 375006  } 
  chiefofstaff           = {  type = 9 id = 375007  } 
  chiefofarmy            = {  type = 9 id = 375008  } 
  chiefofnavy            = {  type = 9 id = 375009  } 
  chiefofair             = {  type = 9 id = 375010  } 
  
  ownedprovinces      = {
		1794 1793 7359 7358 7360
	}
  controlledprovinces = {
		1794 1793 7359 7358 7360
	}
  nationalprovinces   = {
		1794 1793 7359 7358 7360
	}

}#FECHADOR
