##################################
# Country definition for Lesotho #
##################################

country =
{ tag                 = U74
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 10
  capital             = 975
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 6
    political_left    = 5
    freedom           = 3
    free_market       = 5
    professional_army = 5
    defense_lobby     = 8
    interventionism   = 8
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
  }
  ownedprovinces      = { 7436 4992 975 }
  controlledprovinces = { 7436 4992 975 }
  nationalprovinces   = { 7436 4992 975 }
  
}