#####################
# Country main data #
#####################

country =
{ tag                    = LIB
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 10
  capital                = 992
  manpower               = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
     democratic        = 4 
     political_left    = 5 
     freedom           = 3 
     free_market       = 4 
     professional_army = 3 
     defense_lobby     = 3 
     interventionism   = 1 
  }
  nationalprovinces      = { 992
2762
4476 4477 4478
  }
  ownedprovinces         = { 992
2762
4476 4477 4478
  }
  controlledprovinces    = { 992
2762
4476 4477 4478
  }

  diplomacy =
  { relation = { tag = PHI value = 200 }
    relation = { tag = USA value = 200 }
  }
  headofstate            = { type = 9 id = 69001 }
  headofgovernment       = { type = 9 id = 69002 }
  foreignminister        = { type = 9 id = 69003 }
  armamentminister       = { type = 9 id = 69004 }
  ministerofsecurity     = { type = 9 id = 69005 }
  ministerofintelligence = { type = 9 id = 69006 }
  chiefofstaff           = { type = 9 id = 69007 }
  chiefofarmy            = { type = 9 id = 69008 }
  chiefofnavy            = { type = 9 id = 69009 }
  chiefofair             = { type = 9 id = 69010 }
  
} 
 
