##################### 
# Country main data # 
##################### 
country = 
{  tag                    = U21
   capital                = 2583 

     # Resource Reserves 
   energy                 = 100 
   metal                  = 100 
   rare_materials         = 50 
   oil                    = 50 
   supplies               = 100 
   money                  = 50 
   manpower               = 100
      
   transports             = 50 
   escorts                = 0 

   diplomacy = 
   {   
   relation = {  tag = GER value = 80 access = no  }  
    } 
   SpyInfo                = {  country = "U06" NumberOfSpies = 3  } 
  
    
   nationalprovinces      = {  2583  } 
   ownedprovinces         = {  2583  } 
   controlledprovinces    = {  2583  } 
   
   inventions = {  }  
   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 7 
     political_left    = 3 
     free_market       = 8 
     freedom           = 10 
     professional_army = 1 
     defense_lobby     = 3 
     interventionism   = 2  
    } 
}