##############################
# Country definition for NEP #
##############################

country =
{ tag                    = NEP
  # Resource Reserves
  energy                 = 200
  metal                  = 200
  rare_materials         = 100
  oil                    = 200
  supplies               = 200
  money                  = 10
  capital                = 1473
  manpower               = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
     democratic        = 4 
     political_left    = 3 
     freedom           = 6 
     free_market       = 5 
     professional_army = 2 
     defense_lobby     = 2 
     interventionism   = 2 
  }
  nationalprovinces      = { 1473 2953 5177 5178 5179 6923 7912 7913 7919 7920 7921 1456 5206 5197 5207 5210 5211 1472 6922 7193 5224 5223 5222 2043
  }
  ownedprovinces         = { 1473 2953 5177 5178 5179 6923 7912 7913 7919 7920 7921
  }
  controlledprovinces    = { 1473 2953 5177 5178 5179 6923 7912 7913 7919 7920 7921
  }
  claimedprovinces 		 = {  }

  diplomacy =
  { relation = { tag = AST value = 200 }
    relation = { tag = BHU value = 200 }
    relation = { tag = CAN value = 200 }
    relation = { tag = ENG value = 200 }
    relation = { tag = FRA value = 150 }
    relation = { tag = GER value = 1 }
    relation = { tag = IRQ value = 100 }
    relation = { tag = ITA value = 1 }
    relation = { tag = NZL value = 200 }
    relation = { tag = OMN value = 150 }
    relation = { tag = SAF value = 200 }
    relation = { tag = USA value = 100 }
    relation = { tag = YEM value = 150 }
  }
} 
 
