#####################
# Country main data #
#####################

country =
{ tag                    = ROM
  intrinsic_gov_type     = stalinist
  capital                = 424
  manpower               = 200
  ai = "rom_1985.ai"
  ai_settings = {flags = {
			MOB1 = yes
			MOB2 = yes
			MOB3 = yes
			MOB4 = yes
		}
  }
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 15
  
  diplomacy = {}
  
  SpyInfo                = { country = "ENG" NumberOfSpies = 1 }
  SpyInfo                = { country = "YUG" NumberOfSpies = 2 }
  SpyInfo                = { country = "SOV" NumberOfSpies = 1 }
  SpyInfo                = { country = "CZE" NumberOfSpies = 1 }
  SpyInfo                = { country = "AUS" NumberOfSpies = 1 }
  SpyInfo                = { country = "GER" NumberOfSpies = 1 }
  SpyInfo                = { country = "HUN" NumberOfSpies = 2 }
  SpyInfo                = { country = "ALB" NumberOfSpies = 1 }
  SpyInfo                = { country = "GRE" NumberOfSpies = 2 }
  SpyInfo                = { country = "BUL" NumberOfSpies = 3 }
  SpyInfo                = { country = "ITA" NumberOfSpies = 1 }
  nationalprovinces      = {  424 425 431 426 495 496 498 427 428 429 430 432 436 433  230 434
							2603 2450 2449 2605 2604  1403 1449 1402   2602
							1571 3055
							3379	3380	3381	3382	3383	3384	3385		3387	3388	3389		
							1173 1401 435 3390 
							6511 6512
							7051 7052 7053 7054 7070 7071 7300 3386
  }
  ownedprovinces         = { 424 425 431 426 495 496 498 427 428 429 430 432 436 433
							2603 2450 2449 2604 1899 1403 1449 1402 2602 3055
							3379	3380	3381	3382	3383	3384	3385	3386	3387	3388
6511 6512
7051 7052 7053 7054 7071 7300
  }
  controlledprovinces    = { 424 425 431 426 495 496 498 427 428 429 430 432 436 433
							2603 2450 2449 2604 1899 1403 1449 1402 2602 3055
							3379	3380	3381	3382	3383	3384	3385	3386	3387	3388
6511 6512
7051 7052 7053 7054 7071 7300
  }
  claimedprovinces 		 = { 1899 }

  inventions = {  }
  policy =
  { date              = { year = 0 month = january day = 0 }
     democratic        = 1
     political_left    = 10
     freedom           = 1
     free_market       = 1
     professional_army = 3
     defense_lobby     = 8
     interventionism   = 7 
  }
  #headofstate            = { type = 9 id = 22001 }
  #headofgovernment       = { type = 9 id = 22002 }
  #foreignminister        = { type = 9 id = 22003 }
  #armamentminister       = { type = 9 id = 22004 }
  #ministerofsecurity     = { type = 9 id = 22005 }
  #ministerofintelligence = { type = 9 id = 22006 }
  #chiefofstaff           = { type = 9 id = 22007 }
  #chiefofarmy            = { type = 9 id = 22008 }
  #chiefofnavy            = { type = 9 id = 22009 }
  #chiefofair             = { type = 9 id = 22010 }
} 
 
