##############################################
# Country definition for São Tomé & Príncipe #
##############################################

country =
{ tag                 = U47
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 10
  capital             = 1090
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 8
    political_left    = 2
    freedom           = 7
    free_market       = 7
    professional_army = 7
    defense_lobby     = 4
    interventionism   = 5
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  ownedprovinces      = { 1090 }
  controlledprovinces = { 1090 }
  nationalprovinces   = { 1090 }

}