##############################
# Country definition for Suriname #
##############################

country =
{ tag                 = U67
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 10
  capital             = 874
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 9 
    political_left    = 3 
    free_market       = 9 
    freedom           = 10 
    professional_army = 3 
    defense_lobby     = 2 
    interventionism   = 2
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  nationalprovinces = {
		874 3890 3891
	}
	ownedprovinces = {
		874 3890 3891
	}
	controlledprovinces = {
		874 3890 3891
	}

}