#####################
# Country main data #
#####################

country =
{ tag                    = SCH
  capital                = 532
  manpower               = 200
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 25
  policy =
  { date              = { year = 0 month = january day = 0 }
     democratic        = 10 
     political_left    = 2 
     freedom           = 7 
     free_market       = 9 
     professional_army = 3 
     defense_lobby     = 8 
     interventionism   = 1
  }
  nationalprovinces      = { 532 530 533 372 3213 3214 3215 3216 6524 }
  ownedprovinces         = { 532 530 533 372 3213 3214 3215 3216 6524 }
  controlledprovinces    = { 532 530 533 372 3213 3214 3215 3216 6524 }

  inventions = {  }
  diplomacy =
  { relation = { tag = ENG value = 50 }
    relation = { tag = FRA value = 1 }
    relation = { tag = GER value = 50 }
    relation = { tag = AUS value = 50 }
    relation = { tag = ITA value = 1 }
    relation = { tag = SCH value = 1 }
    relation = { tag = USA value = 1 }
  }
  headofstate            = { type = 9 id = 17001 }
  headofgovernment       = { type = 9 id = 17002 }
  foreignminister        = { type = 9 id = 17003 }
  armamentminister       = { type = 9 id = 17004 }
  ministerofsecurity     = { type = 9 id = 17005 }
  ministerofintelligence = { type = 9 id = 17006 }
  chiefofstaff           = { type = 9 id = 17007 }
  chiefofarmy            = { type = 9 id = 17008 }
  chiefofnavy            = { type = 9 id = 17009 }
  chiefofair             = { type = 9 id = 17010 }
}