##############################
# Country definition for SYR #
##############################

country =
{ tag                 = SYR
  energy              = 100
  metal               = 100
  rare_materials      = 50
  oil                 = 500
  supplies            = 500
  money               = 100
  capital             = 1792
  manpower            = 1
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 4
    political_left    = 7
    freedom           = 3
    free_market       = 5
    professional_army = 5
    defense_lobby     = 8
    interventionism   = 8
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  headofstate            = {  type = 9 id = 430001  } 
  headofgovernment       = {  type = 9 id = 430002  } 
  foreignminister        = {  type = 9 id = 430003  } 
  armamentminister       = {  type = 9 id = 430004  } 
  ministerofsecurity     = {  type = 9 id = 430005  } 
  ministerofintelligence = {  type = 9 id = 430006  } 
  chiefofstaff           = {  type = 9 id = 430007  } 
  chiefofarmy            = {  type = 9 id = 430008  } 
  chiefofnavy            = {  type = 9 id = 430009  } 
  chiefofair             = {  type = 9 id = 430010  } 
  
  ownedprovinces      = {
1792 1862 1863 1795 1861 2883 2884 2885 2019 4150 4151 4152
7276 7353 7281 7355 7280 7357 7354 7279 7356 7277 7278 
  }
  controlledprovinces = {
1792 1862 1863 1795 1861 2883 2884 2885 2019 4150 4151 4152
7276 7353 7281 7355 7280 7357 7354 7279 7356 7277 7278 
  }
  nationalprovinces   = {
1792 1862 1863 1795 1861 2883 2884 2885 2019 1159 4150 4151 4152
7276 7353 7281 7355 7280 7357 7354 7279 7356 7277 7278 2876
  }
  claimedprovinces	  = { 4125 1855 4146 }

}
