	##################################
	# Country definition for Tunisia #
	##################################

	country =
	{ tag                 = TUN
	  energy              = 100
	  metal               = 100
	  rare_materials      = 500
	  oil                 = 50
	  supplies            = 500
	  money               = 10
	  capital             = 939
	  manpower            = 100
	  policy =
	  { date              = { year = 0 month = january day = 0 }
		democratic        = 6
		political_left    = 7
		freedom           = 5
		free_market       = 5
		professional_army = 5
		defense_lobby     = 8
		interventionism   = 8
	  }
	diplomacy = { 
		relation = { tag = USA value = 25 }
		}
	ownedprovinces      = { 939 934 935 936 937 938 940 941 2821 2820
	4533 4534
		}
	controlledprovinces = { 939 934 935 936 937 938 940 941 2821 2820
	4533 4534
		}
	nationalprovinces   = { 939 934 935 936 937 938 940 941 2821 2820
	4533 4534
		}

}