	#################################
	# Country definition for Uganda #
	#################################

	country = { 
	tag                 = U70
	energy              = 100
	metal               = 100
	rare_materials      = 500
	oil                 = 50
	supplies            = 500
	money               = 10
	capital             = 1064
	manpower            = 0
	dissent				= 40
	policy =
	{ date              = { year = 0 month = january day = 0 }
		democratic        = 3
		political_left    = 7
		freedom           = 4
		free_market       = 5
		professional_army = 1
		defense_lobby     = 8
		interventionism   = 8
	}
	diplomacy = { 
		relation = { tag = USA value = 25 }
		}
	ownedprovinces      = { 1064 2284
	4718 4719 4720 4721 4722 4723 4724 4725 4726
	7035
		}
	controlledprovinces = { 1064 2284
	4718 4719 4720 4721 4722 4723 4724 4725 4726
	7035
		}
	nationalprovinces   = { 1064 2284
	4718 4719 4720 4721 4722 4723 4724 4725 4726
	7035 2813 4708 4703 4638 2816 4637 1065
		}

}