	##############################
	# Country definition for UAE #
	##############################

	country =
	{ tag                 = U40
	  energy              = 1000
	  metal               = 1000
	  rare_materials      = 5000
	  oil                 = 50000
	  supplies            = 5000
	  money               = 1000
	  capital             = 1504
	  manpower            = 100
	  policy =
	  { date              = { year = 0 month = january day = 0 }
		democratic        = 2
		political_left    = 2
		freedom           = 5
		free_market       = 7
		professional_army = 5
		defense_lobby     = 1
		interventionism   = 4
	  }
	diplomacy = { 
	relation = { tag = USA value = 25 }
	}
	ownedprovinces      = { 4197 5419 1504 2853 7013 7012 }
	controlledprovinces = { 4197 5419 1504 2853 7013 7012 }
	nationalprovinces   = { 4197 5419 1504 2853 7013 7012 }

}