#####################
# Country main data #
#####################

country =
{ tag                    = VEN
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 20
  capital                = 870
  manpower               = 200
  policy =
  { date              = { year = 0 month = january day = 0 }
     democratic        = 9
     political_left    = 7 
     freedom           = 8 
     free_market       = 6 
     professional_army = 4 
     defense_lobby     = 6 
     interventionism   = 5
  }
  nationalprovinces      = { 804 802 810 811 869 870 871
2657 2658 3859 3860 3861 3862 3863 3864 3865 3866 3867 3868 3869 3870 3871 3872 3873 3874 3875
3887 3950 5423 5421 5422 5424 5425 2737
  }
  ownedprovinces         = { 804 802 810 811 869 870
2657 2658 3859 3860 3861 3862 3863 3864 3865 3866 3867 3868 3869 3870 3871 3872 3873 3874 3875 5423
  }
  controlledprovinces    = { 804 802 810 811 869 870
2657 2658 3859 3860 3861 3862 3863 3864 3865 3866 3867 3868 3869 3870 3871 3872 3873 3874 3875 5423
  }

  inventions = {  }
  
  diplomacy =
  { relation = { tag = ARG value = 10 }
    relation = { tag = BOL value = -15 }
    relation = { tag = BRA value = 10 }
    relation = { tag = CHL value = 20 }
    relation = { tag = COL value = 20 }
    relation = { tag = ECU value = 20 }
    relation = { tag = ENG value = -10 }
    relation = { tag = PAR value = 10 }
    relation = { tag = PRU value = 10 }
    relation = { tag = URU value = 10 }
    relation = { tag = USA value = 125 }
  }
}