###################################
# Country definition for Zimbabwe #
###################################

country =
{ tag                 = RHO
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 500
  supplies            = 500
  money               = 10
  capital             = 1125
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 3
    political_left    = 7
    freedom           = 4
    free_market       = 4
    professional_army = 5
    defense_lobby     = 8
    interventionism   = 8
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  ownedprovinces      = { 4978 4980 4981 4982 4972 1124 4979 2799 4977 4975 4976 4973 4974 4971 4968 2921 1125 4969 4970 }
  controlledprovinces = { 4978 4980 4981 4982 4972 1124 4979 2799 4977 4975 4976 4973 4974 4971 4968 2921 1125 4969 4970 }
  nationalprovinces   = { 4978 4980 4981 4982 4972 1124 4979 2799 4977 4975 4976 4973 4974 4971 4968 2921 1125 4969 4970 }
  
}