# Second East Turkestan Republic
 country = { 
  tag       	 = REB
  
  nationalprovinces    = {  } 
  ownedprovinces       = {  } 
  controlledprovinces  = { 845 } 
  capital	= 1981

  landunit = 
   {  location = 845
     name     = "National Resistance Army" 
     id       = {  type = 25600 id = 5  } 
     Division = 
     {  id   = {  type = 25600 id = 6 } 
       name = "Popular Resistance Army" 
       type = militia
	   strength = 20
	   model    = 3
      } 
     Division = 
     {  id   = {  type = 25600 id = 7  } 
       name = "Uganda Freedom Fighters" 
       type = militia 
	   strength = 20
	   model    = 3
      } 
    } 
}
 