
################################
# Country definition for Benin #
################################

country =
{ tag                 = BEN
  energy              = 100
  metal               = 100
  rare_materials      = 5000
  oil                 = 50
  supplies            = 500
  money               = 100
  capital             = 1006
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 1
    political_left    = 7
    freedom           = 3
    free_market       = 5
    professional_army = 5
    defense_lobby     = 8
    interventionism   = 8
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  headofstate            = {  type = 9 id = 565001  } 
  headofgovernment       = {  type = 9 id = 565002  } 
  foreignminister        = {  type = 9 id = 565003  } 
  armamentminister       = {  type = 9 id = 565004  } 
  ministerofsecurity     = {  type = 9 id = 565005  } 
  ministerofintelligence = {  type = 9 id = 565006  } 
  chiefofstaff           = {  type = 9 id = 565007  } 
  chiefofarmy            = {  type = 9 id = 565008  } 
  chiefofnavy            = {  type = 9 id = 565009  } 
  chiefofair             = {  type = 9 id = 565010  }
  
  ownedprovinces      = { 1006 1005
4505 4506 4507 4508 4509 767
	}
  controlledprovinces = { 1006 1005
4505 4506 4507 4508 4509 767
	}
  nationalprovinces   = { 1006 1005
4505 4506 4507 4508 4509 767
	}

}