
##############################
# Country definition for CAM #
##############################

country =
{ tag                 = CAM
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 10
  capital             = 2764
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 3
    political_left    = 4
    freedom           = 3
    free_market       = 5
    professional_army = 5
    defense_lobby     = 8
    interventionism   = 8
  }
  diplomacy = { 
	relation = { tag = USA value = 100 }
	}
  headofstate            = {  type = 9 id = 580001  } 
  headofgovernment       = {  type = 9 id = 580002  } 
  foreignminister        = {  type = 9 id = 580003  } 
  armamentminister       = {  type = 9 id = 580004  } 
  ministerofsecurity     = {  type = 9 id = 580005  } 
  ministerofintelligence = {  type = 9 id = 580006  } 
  chiefofstaff           = {  type = 9 id = 580007  } 
  chiefofarmy            = {  type = 9 id = 580008  } 
  chiefofnavy            = {  type = 9 id = 580009  } 
  chiefofair             = {  type = 9 id = 580010  } 
  
  ownedprovinces      = { 2764 1077 1088 1126 1087 1086 1089
4802 4803 4804 4805 4806 4807 4808 4809 4810 4811 
	}
  controlledprovinces = { 2764 1077 1088 1126 1087 1086 1089
4802 4803 4804 4805 4806 4807 4808 4809 4810 4811 
	}
  nationalprovinces   = { 2764 1077 1088 1126 1087 1086 1089
4802 4803 4804 4805 4806 4807 4808 4809 4810 4811 7348 2743 2744 7923
	}

}