    ############################## 
    # Country definition for EGY - Egypt #  
    ##############################  
    
    #####################  
    # Country main data #  
    #####################  
    
    country =  
    {  tag                    = EGY  
    #ai                     = "EGY.ai"  
    capital                = 903 # Cairo / Al-Qahirah  
      # Resource Reserves  
	energy                 = 540
	metal                  = 270
	rare_materials         = 135
    oil                    = 500  
    supplies               = 50 # No army - no supply reserves  
    money                  = 50  
    manpower               = 200 # No army - no reserves  
  
    transports             = 100  
    escorts                = 0  
         
    
        diplomacy = {   
    relation = {   tag = GER value = 80 access = no   }   
      }  
    SpyInfo                = {   country = "EGY" NumberOfSpies = 3   }  
    
      
    nationalprovinces      = { 903 2897 915 909 913 914 911 910 907 904 906 902 1800 1801 4 1025 1026 1027 1024 1023 905 1020 912 1021 2898 2633 900 901 2899
4601 4602 4603 4604 4605 4606 4607 4608 4609 4610 4611 4612 4613 4614 4615 4616 4617 7298 1799
  }  
    ownedprovinces         = { 903 2897 915 909 913 914 911 910 907 904 906 902 1800 1801 4 1025 1026 1027 1024 1023 905 1020 912 1021 2898 901 2899
4601 4602 4603 4604 4605 4606 4607 4608 4609 4610 4611 4612 4613 4614 4615 4616 4617 7298 7985 900
  }  
    controlledprovinces    = { 903 2897 915 909 913 914 911 910 907 904 906 902 1800 1801 4 1025 1026 1027 1024 1023 905 1020 912 1021 2898 901 2899 
4601 4602 4603 4604 4605 4606 4607 4608 4609 4610 4611 4612 4613 4614 4615 4616 4617 7298 7985 900
  }  
     
    inventions = {  }    
      
    policy =  
    {   date              = {   year = 0 month = january day = 0   }  
      democratic        = 7  
      political_left    = 3  
      free_market       = 8  
      freedom           = 10  
      professional_army = 6  
      defense_lobby     = 3  
      interventionism   = 2  
      }  

    headofstate            = {   type = 9 id = 340001   }
    headofgovernment       = {   type = 9 id = 340002   }
    foreignminister        = {   type = 9 id = 340003   }
    armamentminister       = {   type = 9 id = 340004   }
    ministerofsecurity     = {   type = 9 id = 340005   }
    ministerofintelligence = {   type = 9 id = 340006   }
    chiefofstaff           = {   type = 9 id = 340007   }
    chiefofarmy            = {   type = 9 id = 340008   }
    chiefofnavy            = {   type = 9 id = 340009   }
    chiefofair             = {   type = 9 id = 340010   }
     
}