
############################################
# Country definition for Equatorial Guinea #
############################################

country =
{ tag                 = EQA
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 10
  capital             = 2339
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 3
    political_left    = 3
    freedom           = 5
    free_market       = 7
    professional_army = 7
    defense_lobby     = 4
    interventionism   = 5
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  headofstate            = {  type = 9 id = 640001  } 
  headofgovernment       = {  type = 9 id = 640002  } 
  foreignminister        = {  type = 9 id = 640003  } 
  armamentminister       = {  type = 9 id = 640004  } 
  ministerofsecurity     = {  type = 9 id = 640005  } 
  ministerofintelligence = {  type = 9 id = 640006  } 
  chiefofstaff           = {  type = 9 id = 640007  } 
  chiefofarmy            = {  type = 9 id = 640008  } 
  chiefofnavy            = {  type = 9 id = 640009  } 
  chiefofair             = {  type = 9 id = 640010  } 
  
  ownedprovinces      = { 6945 1091 2339 4900 }
  controlledprovinces = { 6945 1091 2339 4900 }
  nationalprovinces   = { 6945 1091 2339 4900 }

}