
########################################
# Country definition for Guinea-Bissau #
########################################

country =
{ tag                 = U46
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 10
  capital             = 983
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 4
    political_left    = 8
    freedom           = 5
    free_market       = 7
    professional_army = 5
    defense_lobby     = 4
    interventionism   = 5
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  headofstate            = {  type = 9 id = 1045001  } 
  headofgovernment       = {  type = 9 id = 1045002  } 
  foreignminister        = {  type = 9 id = 1045003  } 
  armamentminister       = {  type = 9 id = 1045004  } 
  ministerofsecurity     = {  type = 9 id = 1045005  } 
  ministerofintelligence = {  type = 9 id = 1045006  } 
  chiefofstaff           = {  type = 9 id = 1045007  } 
  chiefofarmy            = {  type = 9 id = 1045008  } 
  chiefofnavy            = {  type = 9 id = 1045009  } 
  chiefofair             = {  type = 9 id = 1045010  } 
  
  ownedprovinces      = { 983 4464 }
  controlledprovinces = { 983 4464 }
  nationalprovinces   = { 983 4464 }

}