
######################################
# Country definition for Ivory Coast #
######################################
#Puppet francês.

country =
{ tag                 = U88
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 10
  capital             = 993
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 3
    political_left    = 4
    freedom           = 3
    free_market       = 5
    professional_army = 5
    defense_lobby     = 8
    interventionism   = 8
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  headofstate            = {  type = 9 id = 1255001  } 
  headofgovernment       = {  type = 9 id = 1255002  } 
  foreignminister        = {  type = 9 id = 1255003  } 
  armamentminister       = {  type = 9 id = 1255004  } 
  ministerofsecurity     = {  type = 9 id = 1255005  } 
  ministerofintelligence = {  type = 9 id = 1255006  } 
  chiefofstaff           = {  type = 9 id = 1255007  } 
  chiefofarmy            = {  type = 9 id = 1255008  } 
  chiefofnavy            = {  type = 9 id = 1255009  } 
  chiefofair             = {  type = 9 id = 1255010  } 
  
  ownedprovinces      = { 993 2646 2645 2822 2823 995
4479 4480 4481 4482 4483 4484 4485 4486 4487 4488 4489 4490 4491
	}
  controlledprovinces = { 993 2646 2645 2822 2823 995
4479 4480 4481 4482 4483 4484 4485 4486 4487 4488 4489 4490 4491
	}
  nationalprovinces   = { 993 2646 2645 2822 2823 995
4479 4480 4481 4482 4483 4484 4485 4486 4487 4488 4489 4490 4491
	}

}