#################################
# Country definition for Malawi #
#################################

country =
{ tag                 = U44
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 10
  capital             = 2809
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 3
    political_left    = 3
    freedom           = 4
    free_market       = 7
    professional_army = 5
    defense_lobby     = 8
    interventionism   = 8
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  ownedprovinces      = { 4946 2809 4945 1132 }
  controlledprovinces = { 4946 2809 4945 1132 }
  nationalprovinces   = { 4946 2809 4945 1132 }
  
}