#################################
# Country definition for Rwanda #
#################################

country =
{ tag                 = U95
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 10
  capital             = 1063
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 7
    political_left    = 2
    freedom           = 3
    free_market       = 5
    professional_army = 5
    defense_lobby     = 8
    interventionism   = 2
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  ownedprovinces      = { 4730 1063 7036 }
  controlledprovinces = { 4730 1063 7036 }
  nationalprovinces   = { 4730 1063 7036 }
  
}