###############################
# Country definition for Togo #
###############################

country =
{ tag                 = U99
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 10
  capital             = 1003
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 3
    political_left    = 3
    freedom           = 4
    free_market       = 1
    professional_army = 5
    defense_lobby     = 8
    interventionism   = 4
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  headofstate            = {  type = 9 id = 1310001  } 
  headofgovernment       = {  type = 9 id = 1310002  } 
  foreignminister        = {  type = 9 id = 1310003  } 
  armamentminister       = {  type = 9 id = 1310004  } 
  ministerofsecurity     = {  type = 9 id = 1310005  } 
  ministerofintelligence = {  type = 9 id = 1310006  } 
  chiefofstaff           = {  type = 9 id = 1310007  } 
  chiefofarmy            = {  type = 9 id = 1310008  } 
  chiefofnavy            = {  type = 9 id = 1310009  } 
  chiefofair             = {  type = 9 id = 1310010  } 
  
  ownedprovinces      = { 1003 1004 4503 4504 }
  controlledprovinces = { 1003 1004 4503 4504 }
  nationalprovinces   = { 1003 1004 4503 4504 }

}