#################################
# Country definition for Guyana #
#################################

country =
{ tag                 = GUY
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 10
  capital             = 873
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 9
    political_left    = 2
    freedom           = 9
    free_market       = 10
    professional_army = 5
    defense_lobby     = 4
    interventionism   = 2
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  ownedprovinces      = { 873 5421 871 3888 3889 3887 5422 }
  controlledprovinces = { 873 5421 871 3888 3889 3887 5422 }
  nationalprovinces   = { 873 5421 871 3888 3889 3887 5422 }

}