
##################################
# Country definition for Jamaica #
##################################

country =
{ tag                 = U89
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 10
  capital             = 891
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 2
    freedom           = 10
    free_market       = 10
    professional_army = 5
    defense_lobby     = 4
    interventionism   = 3
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  ownedprovinces      = { 891 }
  controlledprovinces = { 891 }
  nationalprovinces   = { 891 }

}