##############################################
# Country definition for Trinidad and Tobago #
##############################################

country =
	{ tag                 = U98
	  energy              = 100
	  metal               = 100
	  rare_materials      = 500
	  oil                 = 50
	  supplies            = 500
	  money               = 10
	  capital             = 809
	  manpower            = 100
	  policy =
	  { date              = { year = 0 month = january day = 0 }
		democratic        = 9
		political_left    = 2
		freedom           = 9
		free_market       = 10
		professional_army = 5
		defense_lobby     = 4
		interventionism   = 2
	  }
	diplomacy = { 
		relation = { tag = USA value = 25 }
		}
	ownedprovinces      = { 808 809 }
	controlledprovinces = { 808 809 }
	nationalprovinces   = { 808 809 }

}