####################################
# Country definition for Mauritius #
####################################

country =
{ tag                 = MAN
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 10
  capital             = 1136
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 8
    political_left    = 1
    freedom           = 8
    free_market       = 10
    professional_army = 1
    defense_lobby     = 1
    interventionism   = 1
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  ownedprovinces      = { 1136 5411 5100 5099 }
  controlledprovinces = { 1136 5411 5100 5099 }
  nationalprovinces   = { 1136 5411 5100 5099 }
  claimedprovinces   = { 5096 }

}