    ############################## 
    # Country definition for EGY - Egypt #  
    ##############################  
    
    #####################  
    # Country main data #  
    #####################  
    
    country =  
    {  tag                    = EGY  
    #ai                     = "EGY.ai"  
    capital                = 903 # Cairo / Al-Qahirah  
      # Resource Reserves  
	energy                 = 540
	metal                  = 270
	rare_materials         = 135
    oil                    = 500  
    supplies               = 50 # No army - no supply reserves  
    money                  = 50  
    manpower               = 200 # No army - no reserves  
  
    transports             = 100  
    escorts                = 0  
         
    
        diplomacy = {   
    relation = {   tag = GER value = 80 access = no   }   
      }  
    SpyInfo                = {   country = "EGY" NumberOfSpies = 3   }  
    
      
    nationalprovinces      = { 903 2897 915 909 913 914 911 910 907 904 906 902 1800 1801 4 1025 1026 1027 1024 1023 905 1020 912 1021 2898 2633 900 901 2899
4601 4602 4603 4604 4605 4606 4607 4608 4609 4610 4611 4612 4613 4614 4615 4616 4617 7298 1799
  }  
    ownedprovinces         = { 903 2897 915 909 913 914 911 910 907 904 906 902 1800 1801 4 1025 1026 1027 1024 1023 905 1020 912 1021 2898 901 2899
4601 4602 4603 4604 4605 4606 4607 4608 4609 4610 4611 4612 4613 4614 4615 4616 4617 7298 7985 900
  }  
    controlledprovinces    = { 903 2897 915 909 913 914 911 910 907 904 906 902 1800 1801 4 1025 1026 1027 1024 1023 905 1020 912 1021 2898 901 2899 
4601 4602 4603 4604 4605 4606 4607 4608 4609 4610 4611 4612 4613 4614 4615 4616 4617 7298 7985 900
  }  
     
    techapps = {
   ###################
   #     Infantry    #
   ###################
   #Infantry
   1010 1020 1030
   #Motorized
   1100 1110 1120
   #Mountain
   1160 1170 1180
   #Special Forces
   1250 1260 1270
   #Naval Infantry
   1560 1570 1580
   #Airborne Infantry
   1670 1680 1690
   #Air Cavalry
   1396 1400
   #Armored Cavalry
   13060 13070
   #Mechanized
   1470 1480 1490
   #Irregular Infantry
   1360 1370 1380
   #Combat Engineers
   1830 1840 1850
   #Supply and Repair
   1990 199100 199110 199130 
   ###################
   #Armor & Artillery#
   ###################
   #Main Battle Tanks
   2620 2010 2630 2640 2646
   #Infantry Fighting Vehicles	
   2100
   #Armored Cars
   2860 2870 2950 
   #Anti-Air
   2800 2450 21180
   #Armored Personnel Carriers
   2170 2180 2850 2400 
   #Field Artillery
   2290 2300 2310
   #Self-Propelled Anti-Air
   2810 2820 2510
   #Man-Portable Air-Defense Systems
   3000 3170
   #Self-Propelled Artillery
   2220 2230
   #Self-Propelled Rocket Artillery
   2980 2260 2270
   ###################
   #     Naval       #
   ###################
   #Frigates
   3110 3120 3130
   #Cruisers
   3410 3420 3430 3440
   #Destroyers
   3310 3320 3330 3340
   #Light Aircraft Carriers
   12100
   #Submarines
   3010 3020 3030
   #Transport Ships
   3900 3910 3920
   ###################
   #    Aircraft     #
   ###################
   #Attack Helicopter
   4900
   #Reconnaissance Aircraft
   4770
   #Strategic Bomber
   4800
   #Strike Bomber
   15040
   #Naval Patrol
   4610
   #ASW Bomber
   4230
   #Attack Aircraft
   4030 4060 4090
   #Multi-Role
   4500 4570 4530 4540
   #Air Superiority Fighter
   4510 4520
   #Air Transports
   4250 4260
   #AEW&C
   4450 #4180
   #Air-to-Ground Missiles
   4040
   #Air-to-Air Missiles
   4600
   #Air-to-Sea Missiles
   4740
   ###################
   #    Industry     #
   ###################
   #Light Industry
   5810 5820
   #Heavy Industry
   5130 5110
   #Material Science
   53050 63160 63070
   #Construction Eng.
   5800 5080
   #Rocketry

   #Agriculture
   5700 5710 5010
   #Oil
   5190 5220
   #Computing
   5310 54010 54020
   #Nuclear
   5470 5480 5490
   #Research
   5316
   #Cryptography
   5350 5360
   #Medicine
   5600 5610
   5630
   5660 5730
   ###################
   #  Land Doctrines #
   ###################
   6500 
   6510 6530 
   1650
   6560 #Defensive
   ###################
   # Naval Doctrines #
   ###################
   #Surface Ship Role
   81050 81060 81070 81080 81090 81100 81110 81120
   #Naval Interdiction
   8500 8510 8520 8550 8560 8570 8600 8610 8620
   #Naval Supremacy
   8100 8110 8150 8120 8160 8170 8200 8210 8220
   #Logistics Support
   82500 82510 82520 82530
   #Naval Capability
   8010
   #Amphibious Warfare
   82300
   ###################
   #  Air Doctrines  #
   ###################
   9390 9260 9400 9410
   9090 9100 9110 9120 9050 9060 9070
   9190 9200 9210 9220 9310 9320 9330 9340 9230 9240 9250
   9130 9420 9300
   } 
    inventions = {  }    
      
    policy =  
    {   date              = {   year = 0 month = january day = 0   }  
      democratic        = 7  
      political_left    = 3  
      free_market       = 8  
      freedom           = 10  
      professional_army = 6  
      defense_lobby     = 3  
      interventionism   = 2  
      }  

    headofstate            = {   type = 9 id = 340001   }
    headofgovernment       = {   type = 9 id = 340002   }
    foreignminister        = {   type = 9 id = 340003   }
    armamentminister       = {   type = 9 id = 340004   }
    ministerofsecurity     = {   type = 9 id = 340005   }
    ministerofintelligence = {   type = 9 id = 340006   }
    chiefofstaff           = {   type = 9 id = 340007   }
    chiefofarmy            = {   type = 9 id = 340008   }
    chiefofnavy            = {   type = 9 id = 340009   }
    chiefofair             = {   type = 9 id = 340010   }
     
  # #####################################
  # ARMY
  # #####################################
  landunit =
  { id       = { type = 9600 id = 1 }
    location = 904 #788
    name     = "1st Field Army"
    division =
    { id            = { type = 9600 id = 2 }
      name          = "1st Field Army HQ"
      strength      = 100
      type          = hq
      model         = 1
    }
  }
  landunit =
  { id       = { type = 9600 id = 3 }
    location = 903 #787
    name     = "1st Corps - 1st Army"
    division =
    { id            = { type = 9600 id = 4 }
      name          = "Republican Guard Armored Division"
      strength      = 100
      type          = armor
      model         = 3
 
    }
    division =
    { id            = { type = 9600 id = 5 }
      name          = "24th Mechanized Brigade"
      strength      = 100
      type          = cavalry
      model         = 3
    }
  }
  landunit =
  { id       = { type = 9600 id = 6 }
    location = 907 #789
    name     = "2nd Corps - 1st Army"
    division =
    { id            = { type = 9600 id = 7 }
      name          = "6th Mechanized Division"
      strength      = 100
      type          = infantry
      model         = 4
   
    }
    division =
    { id            = { type = 9600 id = 8 }
      name          = "18th Armored Brigade"
      strength      = 100
      type          = light_armor
      model         = 4
    }
    division =
    { id            = { type = 9600 id = 9 }
      name          = "218th Infantry Brigade"
      strength      = 100
      type          = d_06
      model         = 4
    }
  }
  landunit =
  { id       = { type = 9600 id = 10 }
    location = 1024 #794
    name     = "3rd Corps - 1st Army"
    division =
    { id            = { type = 9600 id = 11 }
      name          = "8th Mechanized Division"
      strength      = 100
      type          = infantry
      model         = 4

    }
    division =
    { id            = { type = 9600 id = 12 }
      name          = "36th Armored Brigade"
      strength      = 100
      type          = light_armor
      model         = 4
    }
    division =
    { id       = { type = 9600 id = 13 }
      name     = "222nd Airmobile Brigade"
      strength = 100
      type     = d_08
      model    = 4
    }
  }
  landunit =
  { id       = { type = 9600 id = 14 }
    location = 901 #791
    name     = "2nd Field Army"
    division =
    { id            = { type = 9600 id = 15 }
      name          = "2nd Field Army HQ"
      strength      = 100
      type          = hq
      model         = 1
    }
  }
  landunit =
  { id       = { type = 9600 id = 16 }
    location = 901 #791
    name     = "1st Corps - 2nd Army"
    division =
    { id            = { type = 9600 id = 17 }
      name          = "2nd Armored Division"
      strength      = 100
      type          = armor
      model         = 3
   
    }
    division =
    { id            = { type = 9600 id = 18 }
      name          = "7th Mechanized Division"
      strength      = 100
      type          = infantry
      model         = 4
    
    }   
    division =
    { id       = { type = 9600 id = 19 }
      name     = "412th Airborne Brigade"
      strength = 100
      type     = d_08
      model    = 4
    }
  }
  landunit =
  { id       = { type = 9600 id = 20 }
    location = 901 #791
    name     = "2nd Corps - 2nd Army"
    division =
    { id            = { type = 9600 id = 21 }
      name          = "4th Armored Division"
      strength      = 100
      type          = armor
      model         = 3
    
    }
    division =
    { id            = { type = 9600 id = 22 }
      name          = "17th Mechanized Division"
      strength      = 100
      type          = infantry
      model         = 4
    
    }
  }
  landunit =
  { id       = { type = 9600 id = 23 }
    location = 902 #786
    name     = "3rd Corps - 2nd Army"
    division =
    { id            = { type = 9600 id = 24 }
      name          = "7th Armored Division"
      strength      = 100
      type          = armor
      model         = 3
    }
    division =
    { id            = { type = 9600 id = 25 }
      name          = "19th Mechanized Division"
      strength      = 100
      type          = infantry
      model         = 4
  
    }
    division =
    { id            = { type = 9600 id = 26 }
      name          = "219th Infantry Brigade"
      strength      = 100
      type          = d_06
      model         = 4
    }
  }
  landunit =
  { id       = { type = 9600 id = 27 }
    location = 900 #900
    name     = "3rd Field Army"
    division =
    { id            = { type = 9600 id = 28 }
      name          = "3rd Field Army HQ"
      strength      = 100
      type          = hq
      model         = 1
    }
  }
  landunit =
  { id       = { type = 9600 id = 29 }
    location = 900
    name     = "1st Corps - 3rd Army"
    division =
    { id            = { type = 9600 id = 30 }
      name          = "9th Armored Division"
      strength      = 100
      type          = armor
      model         = 3
    
    }
    division =
    { id            = { type = 9600 id = 31 }
      name          = "23rd Mechanized Division"
      strength      = 100
      type          = infantry
      model         = 4

    }
    division =
    { id            = { type = 9600 id = 32 }
      name          = "94th Mechanized Brigade"
      strength      = 100
      type          = cavalry
      model         = 3
    }
    division =
    { id       = { type = 9600 id = 33 }
      name     = "224th Airmobile Brigade"
      strength = 100
      type     = d_08
      model    = 4
    }
  }
  landunit =
  { id       = { type = 9600 id = 34 }
    location = 900
    name     = "2nd Corps - 3rd Army"
    division =
    { id            = { type = 9600 id = 35 }
      name          = "36th Mechanized Division"
      strength      = 100
      type          = infantry
      model         = 4
     
    }
    division =
    { id            = { type = 9600 id = 36 }
      name          = "44th Armored Brigade"
      strength      = 100
      type          = light_armor
      model         = 4
    }
  }
  landunit =
  { id       = { type = 9600 id = 37 }
    location = 4 #796
    name     = "3rd Corps - 3rd Army"
    division =
    { id            = { type = 9600 id = 38 }
      name          = "16th Mechanized Division"
      strength      = 100
      type          = infantry
      model         = 4

    }
    division =
    { id            = { type = 9600 id = 39 }
      name          = "82nd Armored Brigade"
      strength      = 100
      type          = light_armor
      model         = 4
    }
    division =
    { id            = { type = 9600 id = 40 }
      name          = "110th Mechanized Brigade"
      strength      = 100
      type          = cavalry
      model         = 3
    }
    division =
    { id            = { type = 9600 id = 41 }
      name          = "111th Mechanized Brigade"
      strength      = 100
      type          = cavalry
      model         = 3
    }
  }
  landunit =
  { id       = { type = 9600 id = 42 }
    location = 903 #787
    name     = "Special Forces"
    division =
    { id            = { type = 9600 id = 43 }
      name          = "Sai'qa Commando Regiments"
      strength      = 100
      type          = d_03
      model         = 4
      extra         = engineer
      brigade_model = 4
    }
  }
  # ###################################
  # NAVY
  # ###################################
  navalunit =
  { id       = { type = 9600 id = 300 }
    location = 907 #789
    base     = 907 #789
    name     = "1st Fleet"
    division =
    { id    = { type = 9600 id = 301 }
      name  = "Mubarak"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 9600 id = 302 }
      name  = "Taba"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 9600 id = 303 }
      name  = "Rasheed"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 9600 id = 304 }
      name  = "El Suez"
      type  = destroyer
      model = 1
    }
  }
  navalunit =
  { id       = { type = 9600 id = 305 }
    location = 907 #789
    base     = 907 #789
    name     = "2nd Fleet"
    division =
    { id    = { type = 9600 id = 306 }
      name  = "Sharm El-Sheik"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 9600 id = 307 }
      name  = "Toushka"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 9600 id = 308 }
      name  = "El Aboukir"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 9600 id = 309 }
      name  = "Najim al Zafir"
      type  = destroyer
      model = 0
    }
  }
  navalunit =
  { id       = { type = 9600 id = 310 }
    location = 907 #789
    base     = 907 #789
    name     = "3rd Fleet"
    division =
    { id    = { type = 9600 id = 311 }
      name  = "Dumyat"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 9600 id = 312 }
      name  = "Al Nasser"
      type  = destroyer
      model = 1
    }
  }
  navalunit =
  { id       = { type = 9600 id = 313 }
    location = 907 #789
    base     = 907 #789
    name     = "Submarine Fleet"
    division =
    { id    = { type = 9600 id = 314 }
      name  = "831"
      type  = submarine
      model = 5
    }
    division =
    { id    = { type = 9600 id = 315 }
      name  = "842"
      type  = submarine
      model = 5
    }
    division =
    { id    = { type = 9600 id = 316 }
      name  = "852"
      type  = submarine
      model = 5
    }
    division =
    { id    = { type = 9600 id = 317 }
      name  = "858"
      type  = submarine
      model = 5
    }
  }
  # ####################################
  # AIR FORCE
  # ####################################
	airunit = { id = { type = 9600 id = 200 }
		location = 903 #787
		base     = 903 #787
		name     = "Air Defence Command"
		division = { id = { type = 9600 id = 202 } name = "104th Fighter Brigade" type = interceptor strength = 100 model = 3 }
		division = { id = { type = 9600 id = 203 } name = "102nd Fighter Brigade" type = interceptor strength = 100 model = 3 }
        division = { id = { type = 9600 id = 201 } name = "282nd Fighter Brigade" type = interceptor strength = 100 model = 3 }
	}
  airunit =
  { id       = { type = 9600 id = 204 }
    location = 903 #787
    base     = 903 #787
    name     = "Tactical Fighter Command"
    division =
    { id       = { type = 9600 id = 205 }
      name     = "222nd Fighter Brigade"
      type     = multi_role
      strength = 100
      model    = 5
    } 
    division =
    { id       = { type = 9600 id = 206 }
      name     = "232nd Fighter Brigade"
      type     = interceptor
      strength = 100
      model    = 3
    }
    division =
    { id       = { type = 9600 id = 207 }
      name     = "236th Fighter Brigade"
      type     = multi_role
      strength = 100
      model    = 5
    } 
    division =
    { id       = { type = 9600 id = 208 }
      name     = "242nd Fighter Brigade"
      type     = interceptor
      strength = 100
      model    = 3
    } 
    division =
    { id       = { type = 9600 id = 209 }
      name     = "252nd Fighter Brigade"
      type     = multi_role
      strength = 100
      model    = 5
    } 
    division =
    { id       = { type = 9600 id = 210 }
      name     = "262nd Fighter Brigade"
      type     = interceptor
      strength = 100
      model    = 3
    } 
    division =
    { id       = { type = 9600 id = 211 }
      name     = "272nd Fighter Brigade"
      type     = interceptor
      strength = 100
      model    = 3
    }
  }
	airunit = { id = { type = 9600 id = 223 }
		location = 903 #787
		base     = 903 #787
		name     = "Central Air Transport Command"
		division = 
		{ id = { type = 9600 id = 224 } 
		   name = "516 Transport Brigade" 
		   type     = transport_plane
		   strength = 100 
		   model = 1 
		}
        division = 
		{ id = { type = 9600 id = 225 } 
		  name = "520 Transport Brigade" 
		  type     = transport_plane
		  strength = 100 
		  model = 1 
		  }
	}
}