#####################
# Country main data #
#####################

country =
{ tag                    = MEX
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 20
  capital                = 752
  manpower               = 200
  dissent                = 20
  
  policy =
  { date              = { year = 0 month = january day = 0 }
     democratic        = 8 
     political_left    = 8 
     freedom           = 6 
     free_market       = 6 
     professional_army = 2 
     defense_lobby     = 4 
     interventionism   = 3 
  }
  nationalprovinces      = { 
756 755 754 753 752 751 750 747 749 745 742 741 744 743 740 739 737 738
2693 2694 2695 2696 2697 2698 2699 2700 2701 2702 2703 2704 2705 2706 2707
4307 4308 4309 4310 4311 4312 4313 4314 4315 4316 
4317 4318 4319 4320 4321 4322 4323 4324 4325 4326 
4327 4328 4329 4330 4331 4332 4333 4334 4335 4336 
4337 4338 4339 4340 4341 4342 4343 4344 4345 4346 
4347 4348 4349 4350 4351 4352 4353 4354 4355 4356 
4357 4358 4359 4360 4361 4362 4363 4364 4365 4366 
4367 4368 4369 4370 4371 4372 4373 4374 4375 4376 
4377 4378 4379 4380 4381 4382 6490 6533
6946 6947
7256 7375 7376 7377 7378 7379 7381 7382
  }
  ownedprovinces         = { 
756 755 754 753 752 751 750 747 749 745 742 741 744 743 740 739 737 738
2693 2694 2695 2696 2697 2698 2699 2700 2701 2702 2703 2704 2705 2706 2707
4307 4308 4309 4310 4311 4312 4313 4314 4315 4316 
4317 4318 4319 4320 4321 4322 4323 4324 4325 4326 
4327 4328 4329 4330 4331 4332 4333 4334 4335 4336 
4337 4338 4339 4340 4341 4342 4343 4344 4345 4346 
4347 4348 4349 4350 4351 4352 4353 4354 4355 4356 
4357 4358 4359 4360 4361 4362 4363 4364 4365 4366 
4367 4368 4369 4370 4371 4372 4373 4374 4375 4376 
4377 4378 4379 4380 4381 4382 6490 6533
6946 6947
7256 7375 7376 7377 7378 7379 7381 7382
  }
  controlledprovinces    = { 
756 755 754 753 752 751 750 747 749 745 742 741 744 743 740 739 737 738
2693 2694 2695 2696 2697 2698 2699 2700 2701 2702 2703 2704 2705 2706 2707
4307 4308 4309 4310 4311 4312 4313 4314 4315 4316 
4317 4318 4319 4320 4321 4322 4323 4324 4325 4326 
4327 4328 4329 4330 4331 4332 4333 4334 4335 4336 
4337 4338 4339 4340 4341 4342 4343 4344 4345 4346 
4347 4348 4349 4350 4351 4352 4353 4354 4355 4356 
4357 4358 4359 4360 4361 4362 4363 4364 4365 4366 
4367 4368 4369 4370 4371 4372 4373 4374 4375 4376 
4377 4378 4379 4380 4381 4382 6490 6533
6946 6947
7256 7375 7376 7377 7378 7379 7381 7382
  }
  claimedprovinces 		 = { 
4383
  }

  techapps = {
   ###################
   #     Infantry    #
   ###################
   #Infantry
   1010 1020 1030
   #Motorized
   1100 1110 1120
   #Mountain
   1160 1170 1180
   #Special Forces
   1250 1260 1270
   #Naval Infantry
   1560 1570 1580
   #Airborne Infantry
   1670 1680 1690
   #Air Cavalry
   1396 1400
   #Armored Cavalry
   13060 13070
   #Mechanized
   1470 1480 1490
   #Irregular Infantry
   1360 1370 1380
   #Combat Engineers
   1830 1840 1850
   #Supply and Repair
   1990 199100 199110 199130 
   ###################
   #Armor & Artillery#
   ###################
   #Main Battle Tanks
   2620 2010 2630 2640 2646
   #Infantry Fighting Vehicles	
   2100
   #Armored Cars
   2860 2870 2950 
   #Anti-Air
   2800 2450 21180
   #Armored Personnel Carriers
   2170 2180 2850 2400 
   #Field Artillery
   2290 2300 2310
   #Self-Propelled Anti-Air
   2810 2820 2510
   #Man-Portable Air-Defense Systems
   3000 3170
   #Self-Propelled Artillery
   2220 2230
   #Self-Propelled Rocket Artillery
   2980 2260 2270
   ###################
   #     Naval       #
   ###################
   #Frigates
   3110 3120 3130
   #Cruisers
   3410 3420 3430 3440
   #Destroyers
   3310 3320 3330 3340
   #Light Aircraft Carriers
   12100
   #Submarines
   3010 3020 3030
   #Transport Ships
   3900 3910 3920
   ###################
   #    Aircraft     #
   ###################
   #Attack Helicopter
   4900
   #Reconnaissance Aircraft
   4770
   #Strategic Bomber
   4800
   #Strike Bomber
   15040
   #Naval Patrol
   4610
   #ASW Bomber
   4230
   #Attack Aircraft
   4030 4060 4090
   #Multi-Role
   4500 4570 4530 4540
   #Air Superiority Fighter
   4510 4520
   #Air Transports
   4250 4260
   #AEW&C
   4450 #4180
   #Air-to-Ground Missiles
   4040
   #Air-to-Air Missiles
   4600
   #Air-to-Sea Missiles
   4740
   ###################
   #    Industry     #
   ###################
   #Light Industry
   5810 5820
   #Heavy Industry
   5130 5110
   #Material Science
   53050 63160 63070
   #Construction Eng.
   5800 5080
   #Rocketry

   #Agriculture
   5700 5710 5010
   #Oil
   5190 5220
   #Computing
   5310 54010 54020
   #Nuclear
   5470 5480 5490
   #Research
   5316
   #Cryptography
   5350 5360
   #Medicine
   5600 5610
   5630
   5660 5730
   #Renewable Energy
   5720 5040
   ###################
   #  Land Doctrines #
   ###################
   6500 
   6510 6530 
   1650
   6560 #Defensive
   ###################
   # Naval Doctrines #
   ###################
   #Surface Ship Role
   81050 81060 81070 81080 81090 81100 81110 81120
   #Naval Interdiction
   8500 8510 8520 8550 8560 8570 8600 8610 8620
   #Naval Supremacy
   8100 8110 8150 8120 8160 8170 8200 8210 8220
   #Logistics Support
   82500 82510 82520 82530
   #Naval Capability
   8010
   #Amphibious Warfare
   82300
   ###################
   #  Air Doctrines  #
   ###################
   9390 9260 9400 9410
   9090 9100 9110 9120 9050 9060 9070
   9190 9200 9210 9220 9310 9320 9330 9340 9230 9240 9250
   9130 9420 9300
   }
  inventions = {  }
  diplomacy =
  { relation = { tag = ENG value = 50 }
    relation = { tag = HOL value = 25 }
    relation = { tag = IRE value = 30 }
    relation = { tag = USA value = 125 }
  }

	# #####################################
	# ARMY
	# #####################################
	landunit = {
		id = { type = 15600 id = 1 }
		location = 752 #1974
		name = "Ejército Mexicano"
		division = {
			id = { type = 15600 id = 2 }
			name = "1a Brigada Blindada"
			strength = 100
			type = cavalry
			model = 4
		}
		division = {
			id = { type = 15600 id = 3 }
			name = "1a Brigada de Infantería"
			strength = 100
			type = d_06
			model = 4
		}
		division = {
			id = { type = 15600 id = 4 }
			name = "2nd Brigada de Infantería"
			strength = 100
			type = d_06
			model = 4
		}
        division = {
			id = { type = 15600 id = 5 }
			name = "3rd Brigada de Infantería"
			strength = 100
			type = d_06
			model = 4
		}
		division = {
			id = { type = 15600 id = 6 }
			name = "Brigada de Fusileros Paracaidistas"
			strength = 100
			type = d_08
			model = 4
		}
		division = {
			id = { type = 15600 id = 7 }
			name = "Guardia Presidencial"
			strength = 100
			type = d_03
			model = 5
		}
	}
    landunit = {
		id = { type = 15600 id = 8 }
		location = 752 #1974
		name = "Fuerzas Especiales"
		division = {
			id = { type = 15600 id = 9 }
			name = "Grupo Aeromóvil de Fuerzas Especiales"
			strength = 100
			type = d_03
			model = 5
		}
	}
	landunit = {
		id = { type = 15600 id = 10 }
		location = 752 #1974
		name = "1a Región Militar"
		division = {
			id = { type = 15600 id = 11 }
			name = "1a Región Militar"
			strength = 60
			type = garrison
			model = 4
		}
	}
	landunit = {
		id = { type = 15600 id = 12 }
		location = 737 #1981
		name = "2a Región Militar"
		division = {
			id = { type = 15600 id = 13 }
			name = "2a Región Militar"
			strength = 60
			type = garrison
			model = 4
		}
	}
    landunit = {
		id = { type = 15600 id = 14 }
		location = 743 #1980
		name = "3a Región Militar"
		division = {
			id = { type = 15600 id = 15 }
			name = "3a Región Militar"
			strength = 60
			type = garrison
			model = 4
		}
	}
	landunit = {
		id = { type = 15600 id = 16 }
		location = 745 #1975
		name = "4a Región Militar"
		division = {
			id = { type = 15600 id = 17 }
			name = "4a Región Militar"
			strength = 60
			type = garrison
			model = 4
		}
	}
    landunit = {
		id = { type = 15600 id = 18 }
		location = 738 #1982
		name = "5a Región Militar"
		division = {
			id = { type = 15600 id = 19 }
			name = "5a Región Militar"
			strength = 60
			type = garrison
			model = 4
		}
	}
	landunit = {
		id = { type = 15600 id = 20 }
		location = 753 #1968
		name = "6a Región Militar"
		division = {
			id = { type = 15600 id = 21 }
			name = "6a Región Militar"
			strength = 60
			type = garrison
			model = 4
		}
	}
    landunit = {
		id = { type = 15600 id = 22 }
		location = 755 #1965
		name = "7a Región Militar"
		division = {
			id = { type = 15600 id = 23 }
			name = "7a Región Militar"
			strength = 60
			type = garrison
			model = 4
		}
	}
	landunit = {
		id = { type = 15600 id = 24 }
		location = 740 #1970
		name = "8a Región Militar"
		division = {
			id = { type = 15600 id = 25 }
			name = "8a Región Militar"
			strength = 60
			type = garrison
			model = 4
		}
	}
    landunit = {
		id = { type = 15600 id = 26 }
		location = 751 #1972
		name = "9a Región Militar"
		division = {
			id = { type = 15600 id = 27 }
			name = "9a Región Militar"
			strength = 60
			type = garrison
			model = 4
		}
	}
	landunit = {
		id = { type = 15600 id = 28 }
		location = 756 #1966
		name = "10a Región Militar"
		division = {
			id = { type = 15600 id = 29 }
			name = "10a Región Militar"
			strength = 60
			type = garrison
			model = 4
		}
	}
    landunit = {
		id = { type = 15600 id = 30 }
		location = 756 #1976
		name = "11a Región Militar"
		division = {
			id = { type = 15600 id = 31 }
			name = "11a Región Militar"
			strength = 60
			type = garrison
			model = 4
		}
	}
	landunit = {
		id = { type = 15600 id = 32 }
		location = 747 #1973
		name = "12a Región Militar"
		division = {
			id = { type = 15600 id = 33 }
			name = "12a Región Militar"
			strength = 60
			type = garrison
			model = 4
		}
	}
	# ###################################
	# NAVY
	# ###################################
	navalunit = {
		id = { type = 15600 id = 300 }
		location = 756 #1966
		base = 756 #1966
		name = "1st Fleet"
		division = {
			id = { type = 15600 id = 301 }
			name = "ARM Allende"
			type = destroyer
			model = 1
		}
		division = {
			id = { type = 15600 id = 302 }
			name = "ARM Abasolo"
			type = destroyer
			model = 1
		}
		division = {
			id = { type = 15600 id = 303 }
			name = "ARM Netzahualcoyotl"
			type = light_cruiser
			model = 1
		}
	}
	navalunit = {
		id = { type = 15600 id = 304 }
		location = 743 #1980
		base = 743 #1980
		name = "2nd Fleet"
		division = {
			id = { type = 15600 id = 305 }
			name = "ARM Victoria"
			type = destroyer
			model = 1
		}
		division = {
			id = { type = 15600 id = 306 }
			name = "ARM Bravo"
			type = destroyer
			model = 1
		}
		division = {
			id = { type = 15600 id = 307 }
			name = "ARM Galeana"
			type = destroyer
			model = 1
		}
		division = {
			id = { type = 15600 id = 308 }
			name = "ARM Manuel Azueta"
			type = light_cruiser
			model = 1
		}
	}
	# ####################################
	# AIR FORCE
	# ####################################
	airunit = {
		id = { type = 15600 id = 200 }
		location	= 744 #1978
		base		= 744 #1978
		name = "1st Wing"
		division = 
		{ id = { type = 15600 id = 201 } 
		  name = "1st Air Transport Squadron" 
		  type     = transport_plane
		  strength = 100 
		  model = 2 
		}
	}
	airunit = {
		id = { type = 15600 id = 202 }
		location	= 744 #1970
		base		= 744 #1970
		name = "2nd Wing"
		division = { id = { type = 15600 id = 203 } name = "401st Air Squadron" type = interceptor strength = 40 model = 3 }
		division = { id = { type = 15600 id = 204 } name = "402nd Air Squadron" type = tactical_bomber strength = 70 model = 2 }
	}
}
 
