##################### 
# Country main data # 
##################### 
 
 country = 
 {  tag                    = U20
   capital                = 2300 

     # Resource Reserves 
   energy                 = 100 
   metal                  = 100 
   rare_materials         = 50 
   oil                    = 50 
   supplies               = 100 
   money                  = 50 
   manpower               = 100
   transports             = 50 
   escorts                = 0 
   
   policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 6
     political_left    = 1 
     free_market       = 4 
     freedom           = 4 
     professional_army = 1 
     defense_lobby     = 1
     interventionism   = 1 
   } 

   diplomacy = {   
   #relation = { tag = GER value = 80 access = no }  
   } 

   nationalprovinces      = {  2300  } 
   ownedprovinces         = {  2300  } 
   controlledprovinces    = {  2300  } 
   
   headofstate            = { type = 9 id = 915001 }
   headofgovernment       = { type = 9 id = 915002 }
   foreignminister        = { type = 9 id = 915003 }
   armamentminister       = { type = 9 id = 915004 }
   ministerofsecurity     = { type = 9 id = 915005 }
   ministerofintelligence = { type = 9 id = 915006 }
   chiefofstaff           = { type = 9 id = 915007 }
   chiefofarmy            = { type = 9 id = 915008 }
   chiefofnavy            = { type = 9 id = 915009 }
   chiefofair             = { type = 9 id = 915010 }
   
   techapps = {
   ###################
   #     Infantry    #
   ###################
   #Infantry
   1010 
   #Motorized
   1100 
   #Mountain
   1160 
   #Special Forces
   1250 
   #Mechanized
   1470
   #Irregular Infantry
   1360
   #Combat Engineers
   1830
   #Supply and Repair
   1990
   ###################
   #Armor & Artillery#
   ###################
   #Main Battle Tanks
   2620
   #Armored Cars
   2860
   #Anti-Air
   2800
   #Armored Personnel Carriers
   2170
   #Field Artillery
   2290 
   #Self-Propelled Anti-Air
   2810
   #Man-Portable Air-Defense Systems
   3000
   #Self-Propelled Artillery
   2220
   #Self-Propelled Rocket Artillery
   2980 
   ###################
   #     Naval       #
   ###################
   #Frigates
   3110
   #Submarines
   3010
   #Transport Ships
   3900
   ###################
   #    Aircraft     #
   ###################
   #Multi-Role
   4500
   #Air Transports
   4250
   ###################
   #    Industry     #
   ###################
   #Light Industry
   5810
   #Heavy Industry
   5130
   #Material Science
   53050
   #Construction Eng.
   5800
   #Agriculture
   5700
   #Oil
   5190
   ###################
   #  Land Doctrines #
   ###################
   6500 
   6510 6530 
   1650
   6560 #Defensive
   ###################
   #  Air Doctrines  #
   ###################
   9190 9200
   }
   inventions = {  }  
   # FRA 1936 techs 
   # ###################### 
}