#####################
# Country main data #
#####################

country =
{ tag                    = GUA
  manpower               = 100
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 10
  capital                = 757
  policy =
  { date              = { year = 0 month = january day = 0 }
     democratic        = 5 
     political_left    = 2 
     free_market       = 6 
     freedom           = 4 
     professional_army = 3 
     defense_lobby     = 5 
     interventionism   = 4
  }
  nationalprovinces      = { 757 2649 4302 4303 4304 4305 758 4306 7380 }
  ownedprovinces         = { 757 2649 4302 4303 4304 4305 7380 }
  controlledprovinces    = { 757 2649 4302 4303 4304 4305 7380 }

  diplomacy =
  { relation = { tag = HON value = 100 }
    relation = { tag = USA value = 125 }
    relation = { tag = ENG value = 50 }
  }
}
 