########## VPS

#########Warsaw Pact###########
#### Soviet stuff
## Moscow Zone Increase
province = { id = 572 ic = 14 } #Moscow +14
province = { id = 570 ic = 12 } #Zagorsk +12
province = { id = 678 ic = 12 } #Vladimir +12
province = { id = 567 ic = 12 } #Serpukhov +12
province = { id = 568 ic = 12 } #Solnecknogorsk +12
province = { id = 571 ic = 12 } #Orekhovozyevo +12
province = { id = 584 ic = 12 } #Tula +12
province = { id = 576 ic = 17 } #Kaluga +17
province = { id = 588 ic = 17 } #Bryansk +17
## Western Republics Increase
province = { id = 599 ic = 10 } #Minsk +10
province = { id = 262 ic = 10 } #Kaunas +5
province = { id = 184 ic = 10 } #Koningsberg a.k.a. Kalliningrad +10
province = { id = 264 ic = 10 } #Riga +10
province = { id = 270 ic = 10 } #Tallinn +10
province = { id = 553 ic = 10 } #Leningrad +10

### East Germany IC Increases
province = { id = 169 ic = 4 } #Magdeburg +4
province = { id = 170 ic = 5 } #Leipzig +5
province = { id = 163 ic = 5 } #Berlim +5
province = { id = 156 ic = 2 } #Neuruppin +2
province = { id = 171 ic = 5 } #Erfurt +5
## Airbases
province = { id = 309 air_base = { size = 5 current_size = 5 } } #Cottbus

### Czechslovakia IC Increases
province = { id = 199 ic = 3 } #Plzen +3
province = { id = 200 ic = 1 } #Liberec +1
province = { id = 202 ic = 1 } #Ceske Budeiovice +1
province = { id = 196 ic = 1 } #Brno +1
province = { id = 208 ic = 3 } #Bratislava +3

### Romania IC Increases
province = { id = 298 ic = 4 } #Galati +4
province = { id = 309 ic = 4 } #Braila +4
province = { id = 288 ic = 4 } #Cluj +4
province = { id = 286 ic = 4 } #Arad +4
province = { id = 295 ic = 2 } #Resita +2
province = { id = 291 ic = 2 } #Sibiu +2

### Hungary IC Increases
province = { id = 279 ic = 2 } #Gyor +3
province = { id = 277 ic = 3 } #Pecs +4
province = { id = 284 ic = 5 } #Budapest +5
province = { id = 280 ic = 3 } #Szeged +3
province = { id = 281 ic = 3 } #Debrecen +3
province = { id = 282 ic = 4 } #Miskolk +4

### Bulgaria IC Increases
province = { id = 325 ic = 3 } #Burgas +3
province = { id = 323 ic = 3 } #Pleven +3
province = { id = 321 ic = 3 } #Sofia +3
province = { id = 319 ic = 3 } #Haskovo +3
province = { id = 326 ic = 3 } #Varna +3
province = { id = 320 ic = 3 } #Gorna Dzumaja +3
province = { id = 317 ic = 3 } #Ruse +3
province = { id = 307 ic = 3 } #Dobrich +3


###########NATO##############

## USA IC Increase
province = { id = 1889 ic = 10 } #San Francisco +10
province = { id = 1884 ic = 5 } #Santa Rosa +5
province = { id = 1888 ic = 5 } #Sacramento +5
province = { id = 1883 ic = 5 } #Fresno +5
province = { id = 1887 ic = 10 } #Los Angeles +10
province = { id = 1892 ic = 5 } #San Bernadino +5
province = { id = 1886 ic = 5 } #San Diego +5
province = { id = 1885 ic = 5 } #Redding +5
province = { id = 1890 ic = 5 } #Eureka +5
province = { id = 1874 ic = 10 } #Seattle +10
province = { id = 1875 ic = 5 } #Wenatchee +5
province = { id = 1877 ic = 5 } #Tacoma +5
province = { id = 1873 ic = 5 } #Yakima +5
province = { id = 1872 ic = 5 } #Spokane +5
province = { id = 1878 ic = 10 } #Portland +10
province = { id = 1924 ic = 10 } #Dallas +10
province = { id = 1928 ic = 10 } #Houston +10
province = { id = 1913 ic = 10 } #Oklahoma City +10
province = { id = 1931 ic = 10 } #New Orleans +10
province = { id = 1953 ic = 10 } #Miami +10
province = { id = 1955 ic = 10 } #Atlanta +10
province = { id = 1809 ic = 5 } #Washington +5
province = { id = 1805 ic = 10 } #Philadelphia +10
province = { id = 1806 ic = 10 } #Pittsburgh +10
province = { id = 1795 ic = 15 } #New York +15
province = { id = 1797 ic = 15 } #Newark +15
province = { id = 1789 ic = 15 } #Boston +15
province = { id = 1845 ic = 15 } #Detroit +15
province = { id = 1832 ic = 15 } #Chicago +15
province = { id = 1784 ic = 5 } #Bangor +5
province = { id = 1786 ic = 5 } #Presque Isle +5
province = { id = 1787 ic = 5 } #Concord +5
province = { id = 1785 ic = 5 } #Lewiston +5
province = { id = 1788 ic = 5 } #Hartford +5
province = { id = 1794 ic = 5 } #Watertown +5
province = { id = 1790 ic = 5 } #Burlington +5
province = { id = 1793 ic = 5 } #Albany +5
province = { id = 1799 ic = 4 } #Newburgh +4

## Spain IC Increase
province = { id = 460 ic = 5 } #Madri +5
province = { id = 440 ic = 6 } #Barcelona +6
province = { id = 443 ic = 4 } #Bilbao +4
province = { id = 444 ic = 2 } #Oviedo +2
province = { id = 445 ic = 2 } #Santander +2
province = { id = 441 ic = 2 } #La Coruna +2
province = { id = 464 ic = 3 } #Valencia +3
province = { id = 447 ic = 2 } #Salamanca +2
province = { id = 471 ic = 2 } #Malaga +2
province = { id = 473 ic = 3 } #Cadiz +3
province = { id = 474 ic = 3 } #Sevilla +3
province = { id = 467 ic = 3 } #Cordoba +3
province = { id = 451 ic = 1 } #Burgos +1
province = { id = 442 ic = 3 } #Zaragoza +3
province = { id = 475 ic = 2 } #Palma de Maiorca +2

## France IC Increase
province = { id = 55 ic = 10 } #Paris +10
province = { id = 96 ic = 5 } #Longwy +5
province = { id = 89 ic = 5 } #Marseille +5
province = { id = 68 ic = 5 } #Bordeaux +5
province = { id = 87 ic = 5 } #Nice +5
province = { id = 37 ic = 2 } #Brest +1
province = { id = 77 ic = 1 } #Toulouse +1
province = { id = 73 ic = 1 } #Limoges +1
province = { id = 104 ic = 2 } #Metz +2

## Greece IC Increase
province = { id = 377 ic = 5 } #Athens +5
province = { id = 372 ic = 2 } #Patra +2
province = { id = 365 ic = 3 } #Tessalonika +3
province = { id = 368 ic = 2 } #Larissa +2
province = { id = 382 ic = 1 } #Iraklion +1
province = { id = 373 ic = 3 } #Corinth +3
province = { id = 363 ic = 1 } #Xanthi +1
province = { id = 367 ic = 1 } #Ioannina +1
province = { id = 383 ic = 1 } #Mytilni +1
province = { id = 376 ic = 1 } #Agrinion +1
province = { id = 364 ic = 1 } #Kavala +1


## DFR IC Increases
province = { id = 179 ic = 5 } #Munich +5
province = { id = 178 ic = 3 } #Augsburg +3
province = { id = 175 ic = 3 } #Regensburg +3
province = { id = 177 ic = 5 } #Nuremberg +5
province = { id = 132 ic = 2 } #Freiburg +2
province = { id = 134 ic = 4 } #Stuttgart +4
province = { id = 136 ic = 2 } #Karlsruhe +2
province = { id = 127 ic = 2 } #Saarbrucken +2
province = { id = 128 ic = 1 } #Trier +1
province = { id = 130 ic = 1 } #Mainz +1
province = { id = 138 ic = 4 } #Frankfurt/Main +4
province = { id = 143 ic = 2 } #Neuwied +2
province = { id = 126 ic = 3 } #Aachen +3
province = { id = 131 ic = 15 } #Cologne +15
province = { id = 142 ic = 2 } #Dusseldorf +2
province = { id = 144 ic = 2 } #Bielefeld +2
province = { id = 141 ic = 2 } #Munster +2
province = { id = 146 ic = 3 } #Hannover +3
province = { id = 147 ic = 1 } #Wilhemshafen +1
province = { id = 148 ic = 2 } #Bremen +2
province = { id = 154 ic = 15 } #Hamburg +15
province = { id = 151 ic = 1 } #Lubeck +1
province = { id = 152 ic = 1 } #Kiel +1

## UK IC Increase
province = { id = 29 ic = 1 } #London +1
province = { id = 24 ic = 1 } #Birmingham +1
province = { id = 17 ic = 1 } #Manchester +1
province = { id = 21 ic = 2 } #Cardiff +2
province = { id = 19 ic = 2 } #Bristol +2
province = { id = 26 ic = 2 } #Dover +2
province = { id = 27 ic = 1 } #Portsmouth +1
province = { id = 25 ic = 1 } #Norwich +1

## Italy IC Increase
#province = { id = 398 ic = 8 } #Turin +8
#province = { id = 396 ic = 7 } #Genoa +7
province = { id = 419 ic = 7 } #Roma +7
#province = { id = 421 ic = 5 } #Naples +5
#province = { id = 430 ic = 5 } #Palermo +5
#province = { id = 404 ic = 4 } #Trieste +4
#province = { id = 408 ic = 5 } #Parma +5
#province = { id = 411 ic = 5 } #Bologna +5
#province = { id = 410 ic = 5 } #Florencia +5
province = { id = 413 ic = 2 } #Livorno +2
province = { id = 414 ic = 2 } #Perugia +2
province = { id = 400 ic = 4 } #Venice +4
#province = { id = 393 ic = 5 } #Brescia +5
province = { id = 434 ic = 2 } #Cagliari +2
province = { id = 427 ic = 4 } #Salerno +4
province = { id = 427 ic = 4 } #Salerno +4
province = { id = 405 ic = 2 } #Udine +2
province = { id = 399 ic = 2 } #Alessandria +2
province = { id = 418 ic = 1 } #Gaeta +1
province = { id = 401 ic = 1 } #Trento +1
province = { id = 402 ic = 1 } #Bolzano +1

## Netherlands IC Increase
province = { id = 122 ic = 5 } #Amsterdam + 7
province = { id = 125 ic = 8 } #Rotterdam + 10
province = { id = 119 ic = 3 } #Arnhem +5
province = { id = 118 ic = 2 } #Eindhoven +2
province = { id = 124 ic = 2 } #Groningen +2
province = { id = 121 ic = 2 } #Maastricht +2
province = { id = 120 ic = 1 } #Nijmegen +1

##################Neutral###################

## Sweden IC Increase
province = { id = 1552 ic = 20 } #Tokyo +30
province = { id = 1550 ic = 20 } #Yokohama +20
province = { id = 1549 ic = 10 } #Sendai +10
province = { id = 1548 ic = 20 } #Kalmar +20
province = { id = 1551 ic = 20 } #Niigata +20
province = { id = 1556 ic = 10 } #Kanazawa +10
province = { id = 1557 ic = 10 } #Nagoya +10
province = { id = 1558 ic = 10 } #Kyoto +10
province = { id = 1553 ic = 10 } #Osaka +10
province = { id = 1555 ic = 10 } #Kobe +10
province = { id = 1554 ic = 10 } #Hiroshima +10
province = { id = 1560 ic = 10 } #Nagasaki +10
province = { id = 1561 ic = 10 } #Kagoshima +10
province = { id = 1559 ic = 10 } #Matsuyama +10

## Japan IC Increase
province = { id = 2159 ic = 8 } #Stockolm +8
province = { id = 2153 ic = 5 } #Goteborg +4
province = { id = 2152 ic = 5 } #Malno +4
province = { id = 2155 ic = 3 } #Kalmar +3
province = { id = 2157 ic = 3 } #Linkoping +3
province = { id = 2160 ic = 2 } #Oerebro +2
province = { id = 2158 ic = 2 } #Uppsala +2
province = { id = 2161 ic = 2 } #Karlstad +2
province = { id = 2166 ic = 2 } #Lulea +2

#naval
province = { id = 	310	naval_base = { size = 	6 	current_size = 	6 	} }
province = { id = 	694	naval_base = { size = 	2 	current_size = 	2 	} }
province = { id =	13	naval_base = { size =	6	current_size = 	6	} }
province = { id =	49	naval_base = { size =	5	current_size = 	5	} }
province = { id =	1052	naval_base = { size =	2	current_size = 	2	} }
province = { id =	34	naval_base = { size =	2	current_size = 	2	} }
province = { id =	37	naval_base = { size =	5	current_size = 	5	} }
province = { id =	43	naval_base = { size =	5	current_size = 	5	} }
province = { id =	45	naval_base = { size =	5	current_size = 	5	} }
province = { id =	115	naval_base = { size =	5	current_size = 	5	} }
province = { id =	125	naval_base = { size =	10	current_size = 	10	} }
province = { id =	122	naval_base = { size =	8	current_size = 	8	} }
province = { id =	147	naval_base = { size =	10	current_size = 	10	} }
province = { id =	153	naval_base = { size =	10	current_size = 	10	} }
province = { id =	220	naval_base = { size =	2	current_size = 	2	} }
province = { id =	2152	naval_base = { size =	6	current_size = 	6	} }
province = { id =	2159	naval_base = { size =	8	current_size = 	8	} }
province = { id =	483	naval_base = { size =	6	current_size = 	6	} }
province = { id =	488	naval_base = { size =	2	current_size = 	2	} }
province = { id =	493	naval_base = { size =	2	current_size = 	2	} }
province = { id =	495	naval_base = { size =	4	current_size = 	4	} }
province = { id =	517	naval_base = { size =	4	current_size = 	4	} }
province = { id =	525	naval_base = { size =	6	current_size = 	6	} }
province = { id =	542	naval_base = { size =	3	current_size = 	3	} }
province = { id =	553	naval_base = { size =	10	current_size = 	10	} }
province = { id =	270	naval_base = { size =	6	current_size = 	6	} }
province = { id =	264	naval_base = { size =	6	current_size = 	6	} }
province = { id =	261	naval_base = { size =	2	current_size = 	2	} }
province = { id =	641	naval_base = { size =	3	current_size = 	3	} }
province = { id =	294	naval_base = { size =	10	current_size = 	10	} }
province = { id =	151	naval_base = { size =	3	current_size = 	3	} }
province = { id =	181	naval_base = { size =	5	current_size = 	5	} }
province = { id =	68	naval_base = { size =	10	current_size = 	10	} }
province = { id =	441	naval_base = { size =	7	current_size = 	7	} }
province = { id =	472	naval_base = { size =	4	current_size = 	4	} }
province = { id =	348	naval_base = { size =	4	current_size = 	4	} }
province = { id =	473	naval_base = { size =	4	current_size = 	4	} }
province = { id =	461	naval_base = { size =	3	current_size = 	3	} }
province = { id =	440	naval_base = { size =	6	current_size = 	6	} }
province = { id =	89	naval_base = { size =	10	current_size = 	10	} }
province = { id =	94	naval_base = { size =	2	current_size = 	2	} }
province = { id =	396	naval_base = { size =	10	current_size = 	10	} }
province = { id =	400	naval_base = { size =	5	current_size = 	5	} }
province = { id =	406	naval_base = { size =	7	current_size = 	7	} }
province = { id =	347	naval_base = { size =	5	current_size = 	5	} }
province = { id =	343	naval_base = { size =	4	current_size = 	4	} }
province = { id =	359	naval_base = { size =	4	current_size = 	4	} }
province = { id =	367	naval_base = { size =	1	current_size = 	1	} }
province = { id =	373	naval_base = { size =	2	current_size = 	2	} }
province = { id =	382	naval_base = { size =	4	current_size = 	4	} }
province = { id =	379	naval_base = { size =	2	current_size = 	2	} }
province = { id =	377	naval_base = { size =	10	current_size = 	10	} }
province = { id =	1011	naval_base = { size =	3	current_size = 	3	} }
province = { id =	385	naval_base = { size =	2	current_size = 	2	} }
province = { id =	1078	naval_base = { size =	2	current_size = 	2	} }
province = { id =	326	naval_base = { size =	2	current_size = 	2	} }
province = { id =	307	naval_base = { size =	2	current_size = 	2	} }
province = { id =	409	naval_base = { size =	10	current_size = 	10	} }
province = { id =	1065	naval_base = { size =	4	current_size = 	4	} }
province = { id =	388	naval_base = { size =	4	current_size = 	4	} }
province = { id =	1056	naval_base = { size =	2	current_size = 	2	} }
province = { id =	184	naval_base = { size =	7	current_size = 	7	} }
province = { id =	410	naval_base = { size =	5	current_size = 	5	} }
province = { id =	421	naval_base = { size =	10	current_size = 	10	} }
province = { id =	422	naval_base = { size =	10	current_size = 	10	} }
province = { id =	430	naval_base = { size =	6	current_size = 	6	} }
province = { id =	432	naval_base = { size =	3	current_size = 	3	} }
province = { id =	434	naval_base = { size =	3	current_size = 	3	} }
province = { id =	475	naval_base = { size =	2	current_size = 	2	} }
province = { id =	2089	naval_base = { size =	10	current_size = 	10	} }
province = { id =	2150	naval_base = { size =	4	current_size = 	4	} }
province = { id =	2142	naval_base = { size =	5	current_size = 	5	} }
province = { id =	1797	naval_base = { size =	10	current_size = 	10	} }
province = { id =	1809	naval_base = { size =	10	current_size = 	10	} }
province = { id =	86	naval_base = { size =	10	current_size = 	10	} }
province = { id =	27	naval_base = { size =	6	current_size = 	6	} }
province = { id =	363	naval_base = { size =	6	current_size = 	6	} }
province = { id =	1812	naval_base = { size =	10	current_size = 	10	} }
province = { id =	1778	naval_base = { size =	4	current_size = 	4	} }
province = { id =	1960	naval_base = { size =	8	current_size = 	8	} }
province = { id =	1963	naval_base = { size =	8	current_size = 	8	} }
province = { id =	1952	naval_base = { size =	3	current_size = 	3	} }
province = { id =	1776	naval_base = { size =	3	current_size = 	3	} }
province = { id =	2050	naval_base = { size =	3	current_size = 	3	} }
province = { id =	1795	naval_base = { size =	10	current_size = 	10	} }
province = { id =	1944	naval_base = { size =	6	current_size = 	6	} }
province = { id =	1931	naval_base = { size =	10	current_size = 	10	} }
province = { id =	1972	naval_base = { size =	3	current_size = 	3	} }
province = { id =	1887	naval_base = { size =	10	current_size = 	10	} }
province = { id =	1874	naval_base = { size =	6	current_size = 	6	} }
province = { id =	1889	naval_base = { size =	10	current_size = 	10	} }
province = { id =	1986	naval_base = { size =	3	current_size = 	3	} }
province = { id =	1988	naval_base = { size =	3	current_size = 	3	} }
province = { id =	2040	naval_base = { size =	3	current_size = 	3	} }
province = { id =	2016	naval_base = { size =	3	current_size = 	3	} }
province = { id =	2023	naval_base = { size =	3	current_size = 	3	} }
province = { id =	2058	naval_base = { size =	3	current_size = 	3	} }
province = { id =	2052	naval_base = { size =	3	current_size = 	3	} }
province = { id =	2075	naval_base = { size =	3	current_size = 	3	} }
province = { id =	1780	naval_base = { size =	3	current_size = 	3	} }
province = { id =	969	naval_base = { size =	3	current_size = 	3	} }
province = { id =	900	naval_base = { size =	3	current_size = 	3	} }
province = { id =	1007	naval_base = { size =	4	current_size = 	4	} }
province = { id =	765	naval_base = { size =	4	current_size = 	4	} }
province = { id =	789	naval_base = { size =	6	current_size = 	6	} }
province = { id =	761	naval_base = { size =	3	current_size = 	3	} }
province = { id =	750	naval_base = { size =	5	current_size = 	5	} }
province = { id =	2078	naval_base = { size =	5	current_size = 	5	} }
province = { id =	747	naval_base = { size =	5	current_size = 	5	} }
province = { id =	736	naval_base = { size =	5	current_size = 	5	} }
province = { id =	978	naval_base = { size =	5	current_size = 	5	} }
province = { id =	718	naval_base = { size =	2	current_size = 	2	} }
province = { id =	1781	naval_base = { size =	2	current_size = 	2	} }
province = { id =	815	naval_base = { size =	4	current_size = 	4	} }
province = { id =	833	naval_base = { size =	2	current_size = 	2	} }
province = { id =	836	naval_base = { size =	4	current_size = 	4	} }
province = { id =	880	naval_base = { size =	8	current_size = 	8	} }
province = { id =	850	naval_base = { size =	4	current_size = 	4	} }
province = { id =	152	naval_base = { size =	10	current_size = 	10	} }
province = { id =	148	naval_base = { size =	10	current_size = 	10	} }
province = { id =	429	naval_base = { size =	4	current_size = 	4	} }
province = { id =	996	naval_base = { size =	1	current_size = 	1	} }
province = { id =	1001	naval_base = { size =	3	current_size = 	3	} }
province = { id =	1541	naval_base = { size =	2	current_size = 	2	} }
province = { id =	1542	naval_base = { size =	2	current_size = 	2	} }
province = { id =	1545	naval_base = { size =	5	current_size = 	5	} }
province = { id =	1544	naval_base = { size =	6	current_size = 	6	} }
province = { id =	1549	naval_base = { size =	5	current_size = 	5	} }
province = { id =	1552	naval_base = { size =	10	current_size = 	10	} }
province = { id =	1557	naval_base = { size =	10	current_size = 	10	} }
province = { id =	1553	naval_base = { size =	10	current_size = 	10	} }
province = { id =	1554	naval_base = { size =	4	current_size = 	4	} }
province = { id =	1559	naval_base = { size =	3	current_size = 	3	} }
province = { id =	1560	naval_base = { size =	3	current_size = 	3	} }
province = { id =	1562	naval_base = { size =	2	current_size = 	2	} }
province = { id =	1563	naval_base = { size =	2	current_size = 	2	} }
province = { id =	1361	naval_base = { size =	6	current_size = 	6	} }
province = { id =	1191	naval_base = { size =	5	current_size = 	5	} }
province = { id =	1447	naval_base = { size =	8	current_size = 	8	} }
province = { id =	1517	naval_base = { size =	8	current_size = 	8	} }
province = { id =	1511	naval_base = { size =	7	current_size = 	7	} }
province = { id =	1632	naval_base = { size =	1	current_size = 	1	} }
province = { id =	1565	naval_base = { size =	1	current_size = 	1	} }
province = { id =	1040	naval_base = { size =	1	current_size = 	1	} }
province = { id =	1051	naval_base = { size =	1	current_size = 	1	} }
province = { id =	1611	naval_base = { size =	1	current_size = 	1	} }
province = { id =	1612	naval_base = { size =	1	current_size = 	1	} }
province = { id =	1041	naval_base = { size =	3	current_size = 	3	} }
province = { id =	1032	naval_base = { size =	3	current_size = 	3	} }
province = { id =	1091	naval_base = { size =	3	current_size = 	3	} }
province = { id =	708	naval_base = { size =	1	current_size = 	1	} }
province = { id =	1019	naval_base = { size =	5	current_size = 	5	} }
province = { id =	1675	naval_base = { size =	4	current_size = 	4	} }
province = { id =	1661	naval_base = { size =	4	current_size = 	4	} }
province = { id =	1686	naval_base = { size =	6	current_size = 	6	} }
province = { id =	1676	naval_base = { size =	6	current_size = 	6	} }
province = { id =	1725	naval_base = { size =	7	current_size = 	7	} }
province = { id =	1726	naval_base = { size =	4	current_size = 	4	} }
province = { id =	1727	naval_base = { size =	7	current_size = 	7	} }
province = { id =	1607	naval_base = { size =	6	current_size = 	6	} }
province = { id =	715	naval_base = { size =	6	current_size = 	6	} }
province = { id =	1602	naval_base = { size =	3	current_size = 	3	} }
province = { id =	1596	naval_base = { size =	4	current_size = 	4	} }
province = { id =	1587	naval_base = { size =	3	current_size = 	3	} }
province = { id =	1590	naval_base = { size =	4	current_size = 	4	} }
province = { id =	1586	naval_base = { size =	7	current_size = 	7	} }
province = { id =	1582	naval_base = { size =	5	current_size = 	5	} }
province = { id =	1721	naval_base = { size =	6	current_size = 	6	} }
province = { id =	1722	naval_base = { size =	3	current_size = 	3	} }
province = { id =	1710	naval_base = { size =	2	current_size = 	2	} }
province = { id =	1707	naval_base = { size =	10	current_size = 	10	} }
province = { id =	1704	naval_base = { size =	10	current_size = 	10	} }
province = { id =	1705	naval_base = { size =	10	current_size = 	10	} }
province = { id =	1701	naval_base = { size =	5	current_size = 	5	} }
province = { id =	1699	naval_base = { size =	5	current_size = 	5	} }
province = { id =	1697	naval_base = { size =	2	current_size = 	2	} }
province = { id =	1698	naval_base = { size =	8	current_size = 	8	} }
province = { id =	1690	naval_base = { size =	3	current_size = 	3	} }
province = { id =	1658	naval_base = { size =	3	current_size = 	3	} }
province = { id =	1624	naval_base = { size =	4	current_size = 	4	} }
province = { id =	1631	naval_base = { size =	10	current_size = 	10	} }
province = { id =	1399	naval_base = { size =	10	current_size = 	10	} }
province = { id =	1432	naval_base = { size =	5	current_size = 	5	} }
province = { id =	1423	naval_base = { size =	6	current_size = 	6	} }
province = { id =	1641	naval_base = { size =	3	current_size = 	3	} }
province = { id =	1048	naval_base = { size =	3	current_size = 	3	} }
province = { id =	1636	naval_base = { size =	4	current_size = 	4	} }
province = { id =	1648	naval_base = { size =	4	current_size = 	4	} }
province = { id =	1647	naval_base = { size =	6	current_size = 	6	} }
province = { id =	1346	naval_base = { size =	10	current_size = 	10	} }
province = { id =	1369	naval_base = { size =	4	current_size = 	4	} }
province = { id =	1365	naval_base = { size =	6	current_size = 	6	} }
province = { id =	1230	naval_base = { size =	2	current_size = 	2	} }
province = { id =	1038	naval_base = { size =	2	current_size = 	2	} }
province = { id =	1228	naval_base = { size =	6	current_size = 	6	} }
province = { id =	1219	naval_base = { size =	4	current_size = 	4	} }
province = { id =	1241	naval_base = { size =	6	current_size = 	6	} }
province = { id =	1747	naval_base = { size =	8	current_size = 	8	} }
province = { id =	1738	naval_base = { size =	2	current_size = 	2	} }
province = { id =	1734	naval_base = { size =	8	current_size = 	8	} }
province = { id =	1749	naval_base = { size =	2	current_size = 	2	} }
province = { id =	1789	naval_base = { size =	10	current_size = 	10	} }
province = { id =	2132	naval_base = { size =	10	current_size = 	10	} }
province = { id =	2086	naval_base = { size =	2	current_size = 	2	} }
province = { id =	2080	naval_base = { size =	2	current_size = 	2	} }
province = { id =	1968	naval_base = { size =	2	current_size = 	2	} }
province = { id =	622	naval_base = { size =	5	current_size = 	5	} }#construction site of all russian dreadghnoughts of ekaterina velikaa class
province = { id =	626	naval_base = { size =	3	current_size = 	3	} }
province = { id =	663	naval_base = { size =	0	current_size = 	0	} }
province = { id =	17	naval_base = { size =	10	current_size = 	10	} }
province = { id =	154	naval_base = { size =	10	current_size = 	10	} }
province = { id =	22	naval_base = { size =	3	current_size = 	3	} }
province = { id =	1878	naval_base = { size =	6	current_size = 	6	} }

##### Tsingtau
province = {
	id = 1328
	anti_air = 2
	air_base = { size = 7 current_size = 7 }
	naval_base = { size =	8	current_size = 	8	} 
	}
province = { id = 1328 landfort = 0 coastalfort = 3 } #Tsingtau
province = { id = 1328 landfort = 1 } #Tsingtau




#### Singapore
province = {
	id = 1432
	anti_air = 4
	air_base = { size = 6 current_size = 6 }
	naval_base = { size =	10	current_size = 	10	} 
	}
province = { id = 1432 landfort = 0 coastalfort = 4 } #Singapore
province = { id = 1432 landfort = 3 } #Singapore


### Halifax coastal forts
province = { id = 2132 landfort = 0 coastalfort = 2 } #Halifax


### Airbases

province = { id =	157	air_base = { size =	5	current_size = 	5	} }
province = { id =	13	air_base = { size =	6	current_size = 	6	} }
province = { id =	49	air_base = { size =	5	current_size = 	5	} }
province = { id =	37	air_base = { size =	5	current_size = 	5	} }
province = { id =	43	air_base = { size =	5	current_size = 	5	} }
province = { id =	45	air_base = { size =	5	current_size = 	5	} }
province = { id =	17	air_base = { size =	8	current_size = 	8	} }
province = { id =	27	air_base = { size =	8	current_size = 	8	} }
province = { id =	29	air_base = { size =	10	current_size = 	10	} }
province = { id =	114	air_base = { size =	5	current_size = 	5	} }
province = { id =	125	air_base = { size =	10	current_size = 	10	} }
province = { id =	122	air_base = { size =	8	current_size = 	8	} }
province = { id =	147	air_base = { size =	10	current_size = 	10	} }
province = { id =	167	air_base = { size =	10	current_size = 	10	} }
province = { id =	151	air_base = { size =	10	current_size = 	10	} }
province = { id =	220	air_base = { size =	2	current_size = 	2	} }
province = { id =	2152	air_base = { size =	6	current_size = 	6	} }
province = { id =	2159	air_base = { size =	8	current_size = 	8	} }
province = { id =	483	air_base = { size =	6	current_size = 	6	} }
province = { id =	488	air_base = { size =	2	current_size = 	2	} }
province = { id =	493	air_base = { size =	2	current_size = 	2	} }
province = { id =	495	air_base = { size =	4	current_size = 	4	} }
province = { id =	517	air_base = { size =	4	current_size = 	4	} }
province = { id =	525	air_base = { size =	6	current_size = 	6	} }
province = { id =	542	air_base = { size =	3	current_size = 	3	} }
province = { id =	553	air_base = { size =	10	current_size = 	10	} }
province = { id =	270	air_base = { size =	6	current_size = 	6	} }
province = { id =	264	air_base = { size =	6	current_size = 	6	} }
province = { id =	258	air_base = { size =	2	current_size = 	2	} }
province = { id =	641	air_base = { size =	3	current_size = 	3	} }
province = { id =	294	air_base = { size =	10	current_size = 	10	} }
province = { id =	153	air_base = { size =	3	current_size = 	3	} }
province = { id =	163	air_base = { size =	10	current_size = 	10	} }
province = { id =	181	air_base = { size =	5	current_size = 	5	} }
province = { id =	173	air_base = { size =	10	current_size = 	10	} }
province = { id =	179	air_base = { size =	10	current_size = 	10	} }
province = { id =	460	air_base = { size =	10	current_size = 	10	} }
province = { id =	55	air_base = { size =	10	current_size = 	10	} }
province = { id =	441	air_base = { size =	7	current_size = 	7	} }
province = { id =	472	air_base = { size =	4	current_size = 	4	} }
province = { id =	348	air_base = { size =	4	current_size = 	4	} }
province = { id =	461	air_base = { size =	3	current_size = 	3	} }
province = { id =	440	air_base = { size =	6	current_size = 	6	} }
province = { id =	89	air_base = { size =	10	current_size = 	10	} }
province = { id =	94	air_base = { size =	2	current_size = 	2	} }
province = { id =	396	air_base = { size =	10	current_size = 	10	} }
province = { id =	400	air_base = { size =	5	current_size = 	5	} }
province = { id =	347	air_base = { size =	5	current_size = 	5	} }
province = { id =	343	air_base = { size =	4	current_size = 	4	} }
province = { id =	359	air_base = { size =	4	current_size = 	4	} }
province = { id =	367	air_base = { size =	1	current_size = 	1	} }
province = { id =	373	air_base = { size =	2	current_size = 	2	} }
province = { id =	382	air_base = { size =	4	current_size = 	4	} }
province = { id =	379	air_base = { size =	2	current_size = 	2	} }
province = { id =	377	air_base = { size =	10	current_size = 	10	} }
province = { id =	1011	air_base = { size =	3	current_size = 	3	} }
province = { id =	1010	air_base = { size =	2	current_size = 	2	} }
province = { id =	1078	air_base = { size =	2	current_size = 	2	} }
province = { id =	409	air_base = { size =	10	current_size = 	10	} }
province = { id =	321	air_base = { size =	2	current_size = 	2	} }
province = { id =	316	air_base = { size =	2	current_size = 	2	} }
province = { id =	1065	air_base = { size =	4	current_size = 	4	} }
province = { id =	388	air_base = { size =	4	current_size = 	4	} }
province = { id =	1056	air_base = { size =	2	current_size = 	2	} }
province = { id =	196	air_base = { size =	3	current_size = 	3	} }
province = { id = 	199	air_base = { size = 	7	current_size = 7	} }
province = { id =	184	air_base = { size =	7	current_size = 	7	} }
province = { id =	410	air_base = { size =	5	current_size = 	5	} }
province = { id =	421	air_base = { size =	10	current_size = 	10	} }
province = { id =	422	air_base = { size =	10	current_size = 	10	} }
province = { id =	430	air_base = { size =	6	current_size = 	6	} }
province = { id =	207	air_base = { size =	6	current_size = 	6	} }
province = { id =	432	air_base = { size =	3	current_size = 	3	} }
province = { id =	392	air_base = { size =	3	current_size = 	3	} }
province = { id =	434	air_base = { size =	3	current_size = 	3	} }
province = { id =	475	air_base = { size =	2	current_size = 	2	} }
province = { id =	429	air_base = { size =	4	current_size = 	4	} }
province = { id =	419	air_base = { size =	10	current_size = 	10	} }
province = { id =	2089	air_base = { size =	10	current_size = 	10	} }
province = { id =	2150	air_base = { size =	4	current_size = 	4	} }
province = { id =	2142	air_base = { size =	5	current_size = 	5	} }
province = { id =	1797	air_base = { size =	10	current_size = 	10	} }
province = { id =	1809	air_base = { size =	10	current_size = 	10	} }
province = { id =	1812	air_base = { size =	10	current_size = 	10	} }
province = { id =	1963	air_base = { size =	8	current_size = 	8	} }
province = { id =	1960	air_base = { size =	8	current_size = 	8	} }
province = { id =	1952	air_base = { size =	3	current_size = 	3	} }
province = { id =	2050	air_base = { size =	3	current_size = 	3	} }
province = { id =	1795	air_base = { size =	10	current_size = 	10	} }
province = { id =	1959	air_base = { size =	3	current_size = 	3	} }
province = { id =	1944	air_base = { size =	6	current_size = 	6	} }
province = { id =	1915	air_base = { size =	10	current_size = 	10	} }
province = { id =	1974	air_base = { size =	2	current_size = 	2	} }
province = { id =	1887	air_base = { size =	10	current_size = 	10	} }
province = { id =	1874	air_base = { size =	6	current_size = 	6	} }
province = { id =	1889	air_base = { size =	10	current_size = 	10	} }
province = { id =	2067	air_base = { size =	3 	current_size = 	3	} }
province = { id =	900	air_base = { size =	3	current_size = 	3	} }
province = { id =	790	air_base = { size =	4	current_size = 	4	} }
province = { id =	765	air_base = { size =	4	current_size = 	4	} }
province = { id =	787	air_base = { size =	3	current_size = 	3	} }
province = { id =	768	air_base = { size =	5	current_size = 	5	} }
province = { id =	747	air_base = { size =	5	current_size = 	5	} }
province = { id =	736	air_base = { size =	5	current_size = 	5	} }
province = { id =	978	air_base = { size =	5	current_size = 	5	} }
province = { id =	727	air_base = { size =	5	current_size = 	5	} }
province = { id =	715	air_base = { size =	2	current_size = 	2	} }
province = { id =	815	air_base = { size =	4	current_size = 	4	} }
province = { id =	833	air_base = { size =	2	current_size = 	2	} }
province = { id =	836	air_base = { size =	4	current_size = 	4	} }
province = { id =	880	air_base = { size =	8	current_size = 	8	} }
province = { id =	996	air_base = { size =	1	current_size = 	1	} }
province = { id =	1001	air_base = { size =	3	current_size = 	3	} }
province = { id =	1140	air_base = { size =	5	current_size = 	5	} }
province = { id =	1541	air_base = { size =	2	current_size = 	2	} }
province = { id =	1542	air_base = { size =	2	current_size = 	2	} }
province = { id =	1544	air_base = { size =	5	current_size = 	5	} }
province = { id =	1545	air_base = { size =	6	current_size = 	6	} }
province = { id =	1549	air_base = { size =	5	current_size = 	5	} }
province = { id =	1552	air_base = { size =	10	current_size = 	10	} }
province = { id =	1557	air_base = { size =	10	current_size = 	10	} }
province = { id =	1553	air_base = { size =	10	current_size = 	10	} }
province = { id =	1554	air_base = { size =	4	current_size = 	4	} }
province = { id =	1560	air_base = { size =	3	current_size = 	3	} }
province = { id =	1562	air_base = { size =	3	current_size = 	3	} }
province = { id =	1561	air_base = { size =	2	current_size = 	2	} }
province = { id =	1563	air_base = { size =	2	current_size = 	2	} }
province = { id =	1362	air_base = { size =	6	current_size = 	6	} }
province = { id =	1191	air_base = { size =	5	current_size = 	5	} }
province = { id =	1447	air_base = { size =	8	current_size = 	8	} }
province = { id =	1517	air_base = { size =	8	current_size = 	8	} }
province = { id =	1511	air_base = { size =	7	current_size = 	7	} }
province = { id =	1658	air_base = { size =	1	current_size = 	1	} }
province = { id =	1565	air_base = { size =	1	current_size = 	1	} }
province = { id =	1048	air_base = { size =	1	current_size = 	1	} }
province = { id =	1051	air_base = { size =	1	current_size = 	1	} }
province = { id =	1611	air_base = { size =	1	current_size = 	1	} }
province = { id =	1612	air_base = { size =	1	current_size = 	1	} }
province = { id =	1041	air_base = { size =	3	current_size = 	3	} }
province = { id =	1032	air_base = { size =	3	current_size = 	3	} }
province = { id =	1089	air_base = { size =	3	current_size = 	3	} }
province = { id =	708	air_base = { size =	1	current_size = 	1	} }
province = { id =	1021	air_base = { size =	1	current_size = 	1	} }
province = { id =	1675	air_base = { size =	4	current_size = 	4	} }
province = { id =	1663	air_base = { size =	4	current_size = 	4	} }
province = { id =	1686	air_base = { size =	6	current_size = 	6	} }
province = { id =	1667	air_base = { size =	10	current_size = 	10	} }
province = { id =	1676	air_base = { size =	6	current_size = 	6	} }
province = { id =	1725	air_base = { size =	7	current_size = 	7	} }
province = { id =	1726	air_base = { size =	4	current_size = 	4	} }
province = { id =	1727	air_base = { size =	7	current_size = 	7	} }
province = { id =	1607	air_base = { size =	6	current_size = 	6	} }
province = { id =	1602	air_base = { size =	3	current_size = 	3	} }
province = { id =	1596	air_base = { size =	4	current_size = 	4	} }
province = { id =	1587	air_base = { size =	3	current_size = 	3	} }
province = { id =	1593	air_base = { size =	4	current_size = 	4	} }
province = { id =	1586	air_base = { size =	7	current_size = 	7	} }
province = { id =	1582	air_base = { size =	5	current_size = 	5	} }
province = { id =	1721	air_base = { size =	6	current_size = 	6	} }
province = { id =	1722	air_base = { size =	3	current_size = 	3	} }
province = { id =	1710	air_base = { size =	2	current_size = 	2	} }
province = { id =	1707	air_base = { size =	10	current_size = 	10	} }
province = { id =	1704	air_base = { size =	10	current_size = 	10	} }
province = { id =	1701	air_base = { size =	5	current_size = 	5	} }
province = { id =	1699	air_base = { size =	5	current_size = 	5	} }
province = { id =	1697	air_base = { size =	2	current_size = 	2	} }
province = { id =	1696	air_base = { size =	8	current_size = 	8	} }
province = { id =	1690	air_base = { size =	3	current_size = 	3	} }
province = { id =	1631	air_base = { size =	3	current_size = 	3	} }
province = { id =	1615	air_base = { size =	4	current_size = 	4	} }
province = { id =	1624	air_base = { size =	10	current_size = 	10	} }
province = { id =	1399	air_base = { size =	10	current_size = 	10	} } 
province = { id =	1369	air_base = { size =	5	current_size = 	5	} }
province = { id =	1284	air_base = { size =	6	current_size = 	6	} }
province = { id =	1415	air_base = { size =	3	current_size = 	3	} }
province = { id =	1636	air_base = { size =	4	current_size = 	4	} }
province = { id =	1653	air_base = { size =	4	current_size = 	4	} }
province = { id =	1647	air_base = { size =	6	current_size = 	6	} }
province = { id =	1346	air_base = { size =	10	current_size = 	10	} }
province = { id =	1338	air_base = { size =	6	current_size = 	6	} }
province = { id =	1230	air_base = { size =	2	current_size = 	2	} }
province = { id =	1228	air_base = { size =	6	current_size = 	6	} }
province = { id =	1219	air_base = { size =	4	current_size = 	4	} }
province = { id =	1241	air_base = { size =	6	current_size = 	6	} }
province = { id =	1747	air_base = { size =	8	current_size = 	8	} }




## alb

province = {
	id = 390
	anti_air = 1
	
		}


#######
# AIR BASES IN CHINA PROPER
#######



### arg

#Bahia Blanca
province = { 
	id = 2048 
	anti_air = 2
	naval_base = {
		size = 8
		current_size = 8
	}
	air_base = { 
		size = 3 
		current_size = 3 
		} 	
	} 

#Buenos Aires
province = {
	id = 2050
	anti_air = 3
	
	}


province = { id = 2050   anti_air = 2 } #Buenos Aires
province = { id = 2049   anti_air = 1 } #Corrientes
province = { id = 2054   anti_air = 1 } #Cordoba


### arm
##
province = { id = 711   landfort = 3 anti_air = 1 }


### ast

province = { id = 1726 #Rabaul

anti_air = 2
}
province = { id = 1607 #Port Moresby

anti_air = 1
}
province = { id = 1602 #Lae
anti_air = 1
}

#Sydney
province = {
	id = 1705
	anti_air = 4
	
	air_base = {
		size = 10
		current_size = 10
		}
	}


#Perth
province = {
	id = 1690
	anti_air = 3
	
	}

# Darwin
province = {
	id = 1697
	anti_air = 2
	naval_base = {
		size = 10
		current_size = 10
		}
	air_base = {
		size = 10
		current_size = 10
		}
	}

#Brisbane 1704
province = {
	id = 1722
	anti_air = 3
	naval_base = {
		size = 10
		current_size = 10
		}
	air_base = {
		size = 10
		current_size = 10
		}
	}


province = { id = 1704 landfort = 0 coastalfort = 1 } #Brisbane
province = { id = 1708 landfort = 0 coastalfort = 1 } #Melbourne
province = { id = 1705 landfort = 0 coastalfort = 2 } #Sydney
province = { id = 1690 landfort = 0 coastalfort = 1 } #Perth

#Anti Aircraft Batteries
province = { id = 1704   anti_air = 1 } #Brisbane

province = { id = 1697   anti_air = 3 } #Darwin
province = { id = 1705   anti_air = 3 } #Sydney
province = { id = 1707   anti_air = 2 } #Canberra
province = { id = 1708   anti_air = 3 } #Melbourne
province = { id = 1712   anti_air = 2 } #Adelaide
province = { id = 1715   anti_air = 1 } #Port Augusta
province = { id = 1690   anti_air = 2 } #Perth
province = { id = 1727   anti_air = 2 } #New Britain
province = { id = 1587   anti_air = 3 } #North Solomon Islands

province = { id = 1712 ic = 2 }
province = { id = 1704 ic = 3 }
province = { id = 1703 ic = 1 }
province = { id = 1705 ic = 2 }
province = { id = 1708 ic = 2 }
province = { id = 1697 ic = 1 }

### aus

province = {
	id = 195
	anti_air = 5
	air_base = {
		size = 10
		current_size = 10
	}
	}

province = {
	id = 189
	anti_air = 2
	air_base = {
		size = 4
		current_size = 4
	}
	}

province = { id = 190   anti_air = 1 } #Graz


province = { id = 190 ic = 4 }
province = { id = 187 ic = 2 }
province = { id = 192 ic = 2 }
province = { id = 194 ic = 3 }
province = { id = 346 ic = 3 }


## bel



province = {
	id = 116
	air_base = {
		size = 6
		current_size = 6
	}
	}
province = {
	id = 115
	naval_base = {
		size = 3
		current_size = 3
	}
	}

province = { id = 114 air_base = { size = 6 current_size = 6 } 
                naval_base = {
		size = 3
		current_size = 3
	} }





### bol

province = {
	id = 2020
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
	}

### bos

province = { id = 353 ic = 2 }



##brasil
province = {
	id = 2075
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
	naval_base = {
		size = 6
		current_size = 6
		}
}

### bur

province = { id =  1410   ic =  3   }
province = { id =  1411   ic =  1   }
province = { id =  1415   ic =  1   }

### can

province = {
	id = 2137
	anti_air = 2
	air_base = {
		size = 6
		current_size = 6
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 2117
	anti_air = 2
	air_base = {
		size = 6
		current_size = 6
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 2134 
	anti_air = 2
	air_base = {
		size = 6
		current_size = 6
		}

	naval_base = {
		size = 4
		current_size = 4
		}
	}



province = {
	id = 2132 #Halifax
	anti_air = 3
	air_base = {
		size = 4
		current_size = 4
		}
		
	}

province = {
	id = 2108
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}

	}

province = {
	id = 2119
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}

	}

province = {
	id = 2106
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}

	}

province = {
	id = 2104
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}

	}



province = { id = 2108   anti_air = 2 } #Ottawa
province = { id = 2119   anti_air = 1 } #Montréal
province = { id = 2117   anti_air = 2 } #Québec
province = { id = 2111   anti_air = 1 } #Toronto
province = { id = 2089   anti_air = 1 } #Vancouver

### guy

province =
{ id        = 1997
  naval_base = { size = 10 current_size = 10 }
  air_base  = { size = 10 current_size = 10 }
}              # Georgetown



province = { id =  1997  ic =  2  }
province = { id =  1782  ic =  2  }
province = { id =  2000  ic =  2  }
province = { id =  1758  ic =  1  }

### chc

province = {	id = 1255	landfort = 3 }
province = {	id = 1259	landfort = 3 }



### chl

province = {
	id = 2023
	anti_air = 2
	
	air_base = {
		size = 4
		current_size = 4
		}
	}

### col

province = {
	id = 1986
	anti_air = 1
	air_base = {
		size = 1
		current_size = 1
		}

	naval_base = {
		size = 2
		current_size = 2
		}
	}

province = { id = 1990   anti_air = 1 } #Cartagena
province = { id = 1991   anti_air = 2 } #Bogota

### cos

province = {
	id = 2027
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}



### dom

province = {
	id = 1780
	naval_base = {
		size = 2
		current_size = 2
	}
	air_base = {
		size = 1
		current_size = 1
	}
}



### ecu


province = {
	id = 2042
	anti_air = 2
	
	air_base = {
		size = 1
		current_size = 1
	}
}


###  egy


province = { id =  787   ic =  8   }
province = { id =  789   ic =   6  }


### fin

#Mannerheim line
province = {	id = 530	landfort = 2 } #Viipuri
province = {	id = 532	landfort = 2 } #Viipuri
province = {	id = 530	anti_air = 3 }

#Coastal forts
province = {	id = 525    coastalfort = 1 }#Helsinki
province = {    id = 141    coastalfort = 1 }#Turku

province = {
	id = 524 #Turku
	anti_air = 2
	naval_base = {
		size = 5
		current_size = 5
	}
	air_base = {
		size = 10
		current_size = 10
	}
}
province = {
	id = 141 #Helsinki
	anti_air = 3
	
}
province = {
	id = 520 #Tampere
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
	}
}
province = {
	id = 527 #Oulu
	air_base = {
		size = 10
		current_size = 10
	}
}


province = {	id = 51 landfort = 4 anti_air = 2 }
province = {	id = 52 landfort = 4 anti_air = 2 }
province = {	id = 102 landfort = 4 anti_air = 2 }
province = {	id = 103 landfort = 4 anti_air = 2 }
province = {	id = 100 landfort = 6 anti_air = 2 }
province = {	id = 95 landfort = 4 anti_air = 2 }

province = {	id = 97 landfort = 3 anti_air = 1 }
province = {	id = 98 landfort = 3 anti_air = 1 }
province = {	id = 88 landfort = 3 anti_air = 1 }
province = {	id = 90 landfort = 3 anti_air = 1 }

province = {	id = 86 landfort = 3 anti_air = 1 }

province = {	id = 67 landfort = 2   }
province = {	id = 83 landfort = 2   }
province = {	id = 80 landfort = 2  anti_air = 1  }



province = {
	id = 37
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 89
	anti_air = 2
	
	}

province = {
	id = 718
	anti_air = 2
	air_base = {
		size = 4
		current_size = 4
		}

	naval_base = {
		size = 4
		current_size = 4
		}
	}

province = {
	id = 68
	anti_air = 2
	air_base = {
		size = 4
		current_size = 4
		}

	naval_base = {
		size = 6
		current_size = 6
		}
	}

province = {
	id = 978
	anti_air = 2
	}

province = {
	id = 1399
	anti_air = 2
	}

province = {
	id = 43
	anti_air = 2
	air_base = {
		size = 4
		current_size = 4
		}

	naval_base = {
		size = 6
		current_size = 6
		}
	}

province = {
	id = 747
	anti_air = 2
	
	}

province = {
	id = 727
	anti_air = 2
	air_base = {
		size = 4
		current_size = 4
		}

	naval_base = {
		size = 5
		current_size = 5
		}
	}

province = {
	id = 55
	anti_air = 5
	
	}

province = {
	id = 104
	anti_air = 3
	air_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 52
	air_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 77
	air_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 63
	air_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 39
	air_base = {
		size = 10
		current_size = 10
		}
	}


province = {
	id = 1019
	anti_air = 2
	air_base = {
		size = 4
		current_size = 4
		}

	
	}

province = {
	id = 728
	anti_air = 2
	air_base = {
		size = 4
		current_size = 4
		}

	naval_base = {
		size = 2
		current_size = 2
		}
	}

province = {
	id = 962
	anti_air = 2
	air_base = {
		size = 4
		current_size = 4
		}
	}


#Anti Aircraft Batteries
province = { id = 52   anti_air = 1 } #Lille

province = { id = 55   anti_air = 3 } #Paris
province = { id = 74   anti_air = 1 } #Vichy
province = { id = 37   anti_air = 2 } #Brest
province = { id = 57   anti_air = 2 } #Nantes
province = { id = 68   anti_air = 2 } #Bordeaux
province = { id = 89   anti_air = 3 } #Marseille

province = { id = 95   anti_air = 1 } #Chaumont
province = { id = 747  anti_air = 2 } #Tunis
province = { id = 727  anti_air = 2 } #Algiers
province = { id = 718  anti_air = 1 } #Casablanca
province = { id = 978  anti_air = 1 } #Dakar
province = { id = 1395  anti_air = 2 } #Hanoi
province = { id = 1399  anti_air = 1 } #Saigon
province = { id = 44   anti_air = 1 } #Caen
province = { id = 43   anti_air = 1 } #Cherbourg


### ger

#Westwall (1st)
province = { id = 105 landfort = 4 anti_air = 2  }
province = { id = 106 landfort = 4  anti_air = 2 }
province = { id = 96 landfort = 4 anti_air = 2 }
province = { id = 111 landfort = 4 anti_air = 2 }
province = { id = 108 landfort = 4 anti_air = 2  }

province = { id = 112 landfort = 2 anti_air = 1 }
province = { id = 114 landfort = 2 anti_air = 1 }
province = { id = 116 landfort = 2 anti_air = 1  }

# Forts in Poland
province = { id = 167 landfort = 1 anti_air = 1  }
province = { id = 239 landfort = 2 anti_air = 1  }
province = { id = 232 landfort = 2 anti_air = 2  }
province = { id = 222 landfort = 3 anti_air = 2  }
province = { id = 224 landfort = 3 anti_air = 2  }




province = {
	id = 152
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}

	
	}

province = {
	id = 137
	anti_air = 2
	air_base = {
		size = 4
		current_size = 4
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 153
	anti_air = 2
	air_base = {
		size = 4
		current_size = 4
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 184
	anti_air = 4
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 163
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}

	}


province = {
	id = 167
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}

	}


province = {
	id = 179
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}

	}

province = {
	id = 138
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}

	}

province = {
	id = 134
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}

	}

province = {
	id = 145
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}

	}

province = {
	id = 142
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}

	}

#Anti Aircraft Batteries
province = { id = 129   anti_air = 2 } #Köln
province = { id = 145   anti_air = 2 } #Essen
province = { id = 169   anti_air = 2 } #Magdeburg
province = { id = 127   anti_air = 2 } #Saarbrücken
province = { id = 130   anti_air = 2 } #Mannheim
province = { id = 134   anti_air = 1 } #Stuttgart
province = { id = 177   anti_air = 1 } #Nürnberg
province = { id = 154   anti_air = 2 } #Hamburg
province = { id = 183   supplypool = 100 } #Elbing
province = { id = 151   anti_air = 1 }
province = { id = 170   anti_air = 1 } #Leipzig




#### gre

province = {	id = 368	landfort = 2 anti_air = 1 } 

province = {	id = 369	landfort = 2 anti_air = 1 } 



province = {
	id = 377
	anti_air = 1
	
	}

province = {
	id = 382
	anti_air = 1
	
	}

### gua


province = {
	id = 2088
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}

	naval_base = {
		size = 4
		current_size = 4
		}
	}
# hai

province = {
	id = 1781
	anti_air = 1
	naval_base = {
		size = 4
		current_size = 4
	}
	air_base = {
		size = 2
		current_size = 2
	}
}


### hol




#Teloekbetoeng
province = {
	id = 1636
	anti_air = 2
	naval_base = {
		size = 7
		current_size = 7
		}
	air_base = {
		size = 4
		current_size = 4
		}
	}

#Batavia
province = {
	id = 1647
	anti_air = 2
	
	}

#Menando
province = {
	id = 1642
	anti_air = 2
	naval_base = {
		size = 3
		current_size = 3
		}
	air_base = {
		size = 2
		current_size = 2
		}
	}


province = {
	id = 122
	anti_air = 2
	naval_base = {
		size = 10
		current_size = 10
		}
	air_base = {
		size = 10
		current_size = 10
		}
	}
#Soerabaia
province = {
	id = 1653
	anti_air = 2
	naval_base = {
		size = 7
		current_size = 7
		}
	}

province = {  id = 1647 oilpool = 100 supplypool = 500 } # Batavia

province = { id = 118  anti_air = 2 } #Eindhoven


### hon

province = {
	id = 2085
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}

	naval_base = {
		size = 4
		current_size = 4
		}
	}
# Honduras


#### IND

province = { id =  1506   ic =  2   }
province = { id =  1516   ic =  2   }
province = { id =  1503   ic =  2   }
province = { id =  1481   ic =  1   }


### ire

province = {
	id = 34
	anti_air = 2
	naval_base = {
		size = 7
		current_size = 7
		}
	air_base = {
		size = 4
		current_size = 4
		}
	}




### ita


province = {
	id = 765
	anti_air = 2
	
	}

province = {
	id = 815
	anti_air = 1
	
	}

province = {
	id = 422
	anti_air = 1
	naval_base = {
		size = 10
		current_size = 10
		}
	air_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 419
	anti_air = 1

	air_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 750
	anti_air = 1
	naval_base = {
		size = 10
		current_size = 10
		}
	air_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 761
	anti_air = 1
	naval_base = {
		size = 5
		current_size = 5
		}
	air_base = {
		size = 4
		current_size = 4
		}
	}

province = {
	id = 407
	anti_air = 1
	
	air_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 396
	anti_air = 1
	naval_base = {
		size = 10
		current_size = 10
		}
	air_base = {
		size = 10
		current_size = 10
		}
	}
province = {
	id = 410
	anti_air = 1
	naval_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 432
	anti_air = 2
	naval_base = {
		size = 10
		current_size = 10
		}
	air_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 434
	anti_air = 1
	naval_base = {
		size = 2
		current_size = 2
		}
	air_base = {
		size = 4
		current_size = 4
		}
	}

province = {
	id = 400
        anti_air = 1
	
	}

province = {
	id = 379
	air_base = {
		size = 4
		current_size = 4
		}
	}



#Tobruk
province = {	id = 765	landfort = 3 }

#Anti Aircraft Batteries
province = { id = 398   anti_air = 3 } #Torino
province = { id = 396   anti_air = 2 } #Genoa
province = { id = 407   anti_air = 3 } #Milano
province = { id = 410   anti_air = 2 } #La Spezia
province = { id = 400   anti_air = 1 } #Venezia
province = { id = 411   anti_air = 1 } #Bologna
province = { id = 414   anti_air = 1 } #Firenze




###jap

province = {
id = 1219
anti_air = 2
air_base = {
size = 7
current_size = 7
}
naval_base = {
size = 5
current_size = 5
}
} 
province = {
	id = 1552
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 1547
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 1554
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 1559
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}


province = {
	id = 1561
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 1556
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}


province = {
	id = 1553
	anti_air = 2
	
	}

province = {
	id = 1554
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 1557
	anti_air = 2
	
	}

#Pusan
province = {
	id = 1232
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

#Taiwan
province = {
	id = 1362
	anti_air = 2
	air_base = {
		size = 8
		current_size = 8
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

#Hainan
province = {
	id = 1551
	anti_air = 2
	air_base = {
		size = 6
		current_size = 6
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}


#Okinawa
province = {
	id = 1564
	anti_air = 2
	air_base = {
		size = 6
		current_size = 6
		}

	naval_base = {
		size = 6
		current_size = 6
		}
	}

#Truk
province = {
	id = 1667
	anti_air = 5
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

#Einewetok
province = {
	id = 1675
	anti_air = 5
	
	}

#Kawajelein
province = {
	id = 1676
	anti_air = 5
	
	}


province = {
	id = 1395
	anti_air = 2
	air_base = {
		size = 4
		current_size = 4
		}

	naval_base = {
		size = 4
		current_size = 4
		}
	}

province = {
	id = 1221
	anti_air = 2
	air_base = {
		size = 4
		current_size = 4
		}
	}

province = {
	id = 1330
	anti_air = 2
	air_base = {
		size = 4
		current_size = 4
		}
	}




#Anti Aircraft Batteries
province = { id = 1663   anti_air = 2 } 
province = { id = 1362   anti_air = 2 } #in Taiwan
province = { id = 1563   anti_air = 2 } #Bonin Islands
province = { id = 1686   anti_air = 3 } #in Mariane Islands
province = { id = 1667   anti_air = 3 } #in Caroline Islands
province = { id = 1669   anti_air = 3 } #in Marshall Islands


#Supply Pools
province = {  id = 1541  oilpool = 100 supplypool = 500 } #Sakhalin
province = {  id = 1542  oilpool = 100 supplypool = 500 } #Sakhalin
province = {  id = 1667  oilpool = 100 supplypool = 500 } #Truk
province = {  id = 1667  oilpool = 100 supplypool = 500 } #Truk
province = {  id = 1627  oilpool = 100 supplypool = 500 } #Marianas
province = {  id = 1395  oilpool = 100 supplypool = 500 } 
province = {  id = 1399  oilpool = 100 supplypool = 500 } 
province = {  id = 1602  oilpool = 100 supplypool = 500 } #Marianas
province = {  id = 1361  oilpool = 100 supplypool = 500 } #Taiwan
province = {  id = 1362  oilpool = 100 supplypool = 500 } #Taiwan
province = {  id = 1363  oilpool = 100 supplypool = 500 } #Taiwan
province = {  id = 1673  oilpool = 100 supplypool = 500 } #Marcus Island
province = {  id = 1563  oilpool = 100 supplypool = 500 } #Okinawa
province = {  id = 1564  oilpool = 100 supplypool = 500 } #Okinawa



### ## kaz
province = { id = 706 ic = 3 }
province = { id = 1113 ic = 2 }
province = { id = 1114 ic = 1 }
province = { id = 507 ic = 2 }
province = { id = 504 ic = 3 }
province = { id = 1110 ic = 1 }


### lat

province = { id =  268   ic =  2   }
province = { id =  274   ic =  1   }
province = { id =  272   ic =  1   }
province = { id =  266   ic =  1   }



province = {
	id = 264
	anti_air = 1
	air_base = {
		size = 1
		current_size = 1
		}

	naval_base = {
		size = 3
		current_size = 3
		}
	}



### lib

province = {
	id = 969
	anti_air = 1
	naval_base = {
		size = 2
		current_size = 2
		}
	air_base = {
		size = 4
		current_size = 4
		}
	}

###   lby


province = { id = 750    ic =  4   }
province = { id = 761    ic =  2   }
province = { id = 765    ic =  1   }



### lit

province = { id =  258   ic = 4    }
province = { id =  255   ic = 1    }
province = { id =  252   ic =  2   }

province = {
	id = 261
	anti_air = 1
	naval_base = {
		size = 2
		current_size = 2
		}
	air_base = {
		size = 1
		current_size = 1
		}
	}

province = {
	id = 262
	anti_air = 1

	air_base = {
		size = 1
		current_size = 1
		}
	}

province = {
	id = 258
	anti_air = 4

	air_base = {
		size = 3
		current_size = 3
		}
	}


### man

province = {
	id = 1199
	anti_air = 2
	air_base = {
		size = 2
		current_size = 2
	}
}

province = {
	id = 1208
	anti_air = 3
	air_base = {
		size = 6
		current_size = 6
}
}

province = {
	id = 1201
	anti_air = 3
	
naval_base = {
		size = 4
		current_size = 4
		}
}

province = {
	id = 1310
	anti_air = 2
	air_base = {
		size = 2
		current_size = 2
	}
}

### mex


province = {
	id = 1972
	anti_air = 2
	air_base = {
	size = 2
	current_size = 2
	}
	naval_base = {
	size = 4
	current_size = 4
	}
}

province = { id = 1977   anti_air = 2 } #Ciudad de México
province = { id = 1975   anti_air = 1 } #Monterey
province = { id = 1974   anti_air = 4 } 




### con

province = { id =  850    ic = 4 }
province = { id =  929    ic = 1 }
province = { id =  842    ic = 1 }
province = { id =  915    ic = 1 }
province = { id =  956    ic = 1 }


province = {
	id = 956
	anti_air = 2
	air_base = {
	size = 2
	current_size = 2
	}
        naval_base = {
	size = 4
	current_size = 4
	}
}

province = {
	id = 882
	anti_air = 2
	air_base = {
	size = 2
	current_size = 2
	}
        naval_base = {
	size = 4
	current_size = 4
	}
}

#### mon


province = { id = 1124 ic = 2 }
province = { id = 1167 ic = 2 }
province = { id = 1168 ic = 2 }
province = { id = 1169 ic = 1 }
province = { id = 1119 ic = 2 }
province = { id = 1147 ic = 3 }




province = {
	id = 1124
	air_base = {
		size = 1
		current_size = 1
	}
}



#### nzl

province = {
	id = 1721
	anti_air = 2
	
}




### nic

province = {
	id = 2080
	naval_base = {
		size = 1
		current_size = 1
	}
	air_base = {
		size = 1
		current_size = 1
	}
}


### nor

province = {
	id = 495
	anti_air = 1
	
}

province = {
	id = 483
	anti_air = 2
	naval_base = {
		size = 10
		current_size = 10
	}
	air_base = {
		size = 4
		current_size = 4
	}
}

province = {
	id = 488
	anti_air = 2
	naval_base = {
		size = 10
		current_size = 10
	}
	air_base = {
		size = 5
		current_size = 5
	}
}


province = {	id = 483	landfort = 0 coastalfort = 3 }#Oslofjorden
province = {	id = 493	landfort = 0 coastalfort = 2 }#Trondheim/Agdenes
province = {	id = 485	landfort = 0  coastalfort = 3 } #Bergen



### omn

province = {
	id = 1052
	anti_air = 2
	naval_base = {
		size = 3
		current_size = 3
	}
	air_base = {
		size = 1
		current_size = 1
	}
}


### ott

province = {
	id = 1076
	anti_air = 4
	air_base = {
		size = 6
		current_size = 6
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 1075
	anti_air = 4
	air_base = {
		size = 6
		current_size = 6
		}
	}



### pak

province = { id =  1459   ic =   4  }
province = { id =  1527   ic =   1  }
province = { id =  1524   ic =   1  }
province = { id =  1525   ic =   1  }


### pan


province = {
	id = 2078
	anti_air = 2
	naval_base = {
		size = 3
		current_size = 3
	}
	air_base = {
		size = 1
		current_size = 1
	}
}




### par


province = {
	id = 2046
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
	}




###  per


province = {
	id = 1091
	anti_air = 2
	naval_base = {
		size = 3
		current_size = 3
	}
	air_base = {
		size = 1
		current_size = 1
	}
}




### par


province = { id = 1565 landfort = 1 } #Manila

province = {
	id = 1565
	anti_air = 2
	naval_base = {
		size = 8
		current_size = 8
	}
	air_base = {
		size = 1
		current_size = 1
	}
}

### pol

province = {
	id = 232
	anti_air = 2
	air_base = {
		size = 6
		current_size = 6
	}
}

province = {
	id = 181
	anti_air = 2
	naval_base = {
		size = 8
		current_size = 8
	}
	air_base = {
		size = 4
		current_size = 4
	}
}

province = {
	id = 223
	anti_air = 2
	air_base = {
		size = 4
		current_size = 4
	}
}
#Anti Aircraft Batteries
province = { id = 224   anti_air = 2 } #Poznan
province = { id = 223   anti_air = 2 } #Lodz
province = { id = 235   anti_air = 2 } #Krakow
province = { id = 258   anti_air = 1 } #Vilna
province = { id = 255   anti_air = 1 } #Grodno
province = { id = 222   anti_air = 1 } #Torun


##Extra IC

province = {
	id = 964
	anti_air = 2
	naval_base = {
		size = 3
		current_size = 3
	}
	air_base = {
		size = 4
		current_size = 4
	}
}

province = {
	id = 991
	anti_air = 2
	naval_base = {
		size = 3
		current_size = 3
	}
	air_base = {
		size = 4
		current_size = 4
	}
}

### por


province = {
	id = 995
	anti_air = 2
	naval_base = {
		size = 3
		current_size = 3
	}
	air_base = {
		size = 4
		current_size = 4
	}
}

province = {
	id = 476
	anti_air = 2
	naval_base = {
		size = 10
		current_size = 10
	}
	air_base = {
		size = 10
		current_size = 10
	}
}

province = {
	id = 1372
	naval_base = {
		size = 3
		current_size = 3
	}
	air_base = {
		size = 1
		current_size = 1
	}
}



province = {
	id = 892
	naval_base = {
		size = 3
		current_size = 3
	}
	air_base = {
		size = 1
		current_size = 1
	}
}

province = {
	id = 854
	naval_base = {
		size = 3
		current_size = 3
	}
	air_base = {
		size = 1
		current_size = 1
	}
}

province = {
	id = 1617
	naval_base = {
		size = 3
		current_size = 3
	}
	air_base = {
		size = 1
		current_size = 1
	}
}

province = {
	id = 992
	naval_base = {
		size = 3
		current_size = 3
	}
	air_base = {
		size = 1
		current_size = 1
	}
}

province = {
	id = 912
	anti_air = 2
	naval_base = {
		size = 1
		current_size = 1
	}
	air_base = {
		size = 1
		current_size = 1
	}
}

province = {
	id = 893
	naval_base = {
		size = 1
		current_size = 1
	}
	air_base = {
		size = 1
		current_size = 1
	}
}	

province = {
	id = 894
	anti_air = 2
	naval_base = {
		size = 3
		current_size = 3
	}
	air_base = {
		size = 2
		current_size = 2
	}
}

province = { id = 481   anti_air = 1 } #Porto
province = { id = 476   anti_air = 2 } #Lissabon




province = {	id = 1185	landfort = 2 }
province = {	id = 1190	landfort = 2 }


### rom



province = {
	id = 310
	anti_air = 2
	naval_base = {
		size = 3
		current_size = 3
	}
	air_base = {
		size = 1
		current_size = 1
	}
}

province = {
	id = 316
	anti_air = 2
	air_base = {
		size = 5
		current_size = 5
	}
}

#Anti Aircraft Batteries
province = { id = 304   anti_air = 1 } #Chisinau
province = { id = 311   anti_air = 3 } #Ploiesti

province = { id = 311 ic = 1 }
province = { id = 310 ic = 2 }


### rsi

province = { id = 422    ic =  3   }
province = { id = 424    ic =  2   }
province = { id = 427    ic = 3  }


### eth

province = { id = 818    ic =  1   }
province = { id = 815    ic =  1   }
province = { id = 828    ic =  3   }




province = {
	id = 535
	anti_air = 2
	naval_base = {
		size = 7
		current_size = 7
	}
	air_base = {
		size = 4
		current_size = 4
	}
}

province = {
	id = 542
	anti_air = 2
	
}

province = {
	id = 553
	anti_air = 2
	
}

province = {
	id = 641
	anti_air = 3
	naval_base = {
		size = 10
		current_size = 10
	}
	air_base = {
		size = 6
		current_size = 6
	}
}

province = {
	id = 708
	anti_air = 2
	naval_base = {
		size = 3
		current_size = 3
	}
	air_base = {
		size = 4
		current_size = 4
	}
}


province = {
	id = 1190
	air_base = {
		size = 2
		current_size = 2
	}
}

province = {
	id = 1148
	air_base = {
		size = 2
		current_size = 2
	}
}

province = {
	id = 664
	air_base = {
		size = 2
		current_size = 2
	}

}
province = {
	id = 706
	anti_air = 2
	air_base = {
		size = 4
		current_size = 4
	}
}

province = {
	id = 667
	air_base = {
		size = 2
		current_size = 2
	}
}

province = {
	id = 607
	air_base = {
		size = 2
		current_size = 2
	}
}

province = {
	id = 1191
	anti_air = 2
	naval_base = {
		size = 10
		current_size = 10
	}
	air_base = {
		size = 10
		current_size = 10
	}
}


province = {
	id = 1541
	anti_air = 2
	naval_base = {
		size = 3
		current_size = 3
	}
}

province = {
	id = 1186
	anti_air = 2
	naval_base = {
		size = 1
		current_size = 1
	}
	air_base = {
		size = 1
		current_size = 1
	}
}



province = {
	id = 1189
	air_base = {
		size = 1
		current_size = 1
	}
}



province = {
	id = 1179
	air_base = {
		size = 1
		current_size = 1
	}
}


province = {
	id = 1165
	air_base = {
		size = 1
		current_size = 1
	}
}


province = {
	id = 1138
	air_base = {
		size = 1
		current_size = 1
	}
}




province = {
	id = 663
	air_base = {
		size = 1
		current_size = 1
	}
}


province = {
	id = 617
	air_base = {
		size = 8
		current_size = 8
	}
}


province = {
	id = 599
	air_base = {
		size = 8
		current_size = 8
	}
}


province = {
	id = 566
	air_base = {
		size = 6
		current_size = 6
	}
}


province = {
	id = 572
	air_base = {
		size = 10
		current_size = 10
	}
}

province = {
	id = 581
	air_base = {
		size = 5
		current_size = 5
	}
}

province = {	id = 553	landfort = 2 coastalfort = 5 anti_air = 1 }#Leningrad
province = {	id = 572	landfort = 1 coastalfort = 0 anti_air = 2 }#Moscow

province = {	id = 641	coastalfort = 5 }#Sevestapol
province = {	id = 1191	landfort = 1 coastalfort = 3 }#Vladivostok

#Anti Aircraft Batteries
province = { id = 560   anti_air = 1 } #Novgorod
province = { id = 535   anti_air = 2 } #Murmansk
province = { id = 542   anti_air = 2 } #Archangelsk
province = { id = 590   anti_air = 2 } #Vitebsk
province = { id = 589   anti_air = 3 } #Smolensk
province = { id = 599   anti_air = 3 } #Minsk
province = { id = 588   anti_air = 2 } #Bryansk
province = { id = 576   anti_air = 1 } #Kaluga
province = { id = 635   anti_air = 2 } #Bakmut
province = { id = 617   anti_air = 3 } #Kiev
province = { id = 626   anti_air = 3 } #Odessa
province = { id = 632   anti_air = 2 } #Dnepropetrovsk
province = { id = 641   anti_air = 3 } #Sevastopol
province = { id = 636   anti_air = 1 } #Kharkov
province = { id = 644   anti_air = 2 } #Rostov
province = { id = 654  anti_air = 1 } #Voronezh
province = { id = 1191  anti_air = 3 } #Vladivostok





###  sal

province = {
	id = 2079
	naval_base = {
		size = 1
		current_size = 1
	}
	air_base = {
		size = 1
		current_size = 1
	}
	}



### sau

province = {
	id = 1048
	anti_air = 2
	naval_base = {
		size = 3
		current_size = 3
	}
	air_base = {
		size = 1
		current_size = 1
	}
}



### sia

province = {
	id = 1423
	anti_air = 2
	naval_base = {
		size = 10
		current_size = 10
	}
	air_base = {
		size = 4
		current_size = 4
	}
}


### saf

province = {
	id = 880
	anti_air = 2
	naval_base = {
		size = 10
		current_size = 10
	}
	air_base = {
		size = 10
		current_size = 10
	}
}

province = {
	id = 881
	anti_air = 2
	naval_base = {
		size = 3
		current_size = 3
	}
	air_base = {
		size = 1
		current_size = 1
	}
}

province = {
	id = 876
	anti_air = 2
	naval_base = {
		size = 3
		current_size = 3
	}
	air_base = {
		size = 1
		current_size = 1
	}
}

#Anti Aircraft Batteries
province = { id = 876   anti_air = 3 } #Johannesburg
province = { id = 881   anti_air = 1 } #Durban
province = { id = 873   anti_air = 1 } #Port Elizabeth
province = { id = 880   anti_air = 2 } #Cape Town




### spa


province = {
	id = 436
	anti_air = 2
	naval_base = {
		size = 7
		current_size = 7
	}
	air_base = {
		size = 4
		current_size = 4
	}
}

province = {
	id = 464
	anti_air = 2
	naval_base = {
		size = 3
		current_size = 3
	}
	air_base = {
		size = 2
		current_size = 2
	}
}

province = {
	id = 441
	anti_air = 2
	naval_base = {
		size = 7
		current_size = 7
	}
	air_base = {
		size = 4
		current_size = 4
	}
}

province = {
	id = 475
	anti_air = 2
	naval_base = {
		size = 7
		current_size = 7
	}
	air_base = {
		size = 4
		current_size = 4
	}
}

province = {
	id = 474
	anti_air = 2
	naval_base = {
		size = 7
		current_size = 7
	}
	air_base = {
		size = 4
		current_size = 4
	}
}

province = {
	id = 988
	anti_air = 2
	naval_base = {
		size = 2
		current_size = 2
	}
	air_base = {
		size = 2
		current_size = 2
	}
}

province = {
	id = 990
	naval_base = {
		size = 1
		current_size = 1
	}
	air_base = {
		size = 2
		current_size = 2
	}
}

province = {
	id = 715
	anti_air = 3
	air_base = {
		size = 2
		current_size = 2
	}
}

province = {
	id = 460
	anti_air = 3
	
}



### sud

province = { id =  813   ic =  4 }
province = { id =  810   ic =  1 }


### swe

province = {
	id = 2156
	anti_air = 2
	naval_base = {
		size = 7
		current_size = 7
	}
	air_base = {
		size = 4
		current_size = 4
	}
}

province = {
	id = 2153
	anti_air = 2
	naval_base = {
		size = 7
		current_size = 7
	}
	air_base = {
		size = 4
		current_size = 4
	}
}

province = {
	id = 2159
	anti_air = 2
	naval_base = {
		size = 7
		current_size = 7
	}
	air_base = {
		size = 4
		current_size = 4
	}
}

province = {
	id = 2166
	anti_air = 2
	naval_base = {
		size = 3
		current_size = 3
	}
	air_base = {
		size = 4
		current_size = 4
	}
}




province = {	id = 2159	landfort = 0 coastalfort = 3 }#Stockholms Kustartilleriförsvar
province = {	id = 2166	landfort = 3 coastalfort = 0 }#Bodens Fästning
province = {	id = 2152	landfort = 0 coastalfort = 3 }#Karlkrona Kustartilleriförsvar
province = {	id = 2153	landfort = 0 coastalfort = 1 }#Marindistrikt Öresund
province = {	id = 2155	landfort = 0 coastalfort = 3 }#Älvsborgs Kustartilleriförsvar
province = {	id = 2158	landfort = 1 coastalfort = 1 }#Karlsborgs Fästning
province = {	id = 2162	landfort = 1 coastalfort = 1 }



### sch

province = {
	id = 392
	anti_air = 2
	air_base = {
		size = 4
		current_size = 4
	}
}
#Swiss defenses
province = {	id = 392	landfort = 5 }
province = {	id = 389	landfort = 5 }
province = {	id = 390	landfort = 5 }
province = {	id = 391	landfort = 5 }

#Anti Aircraft Batteries
province = { id = 392   anti_air = 3 }
province = { id = 389   anti_air = 3 }
province = { id = 390   anti_air = 3 }
province = { id = 391   anti_air = 3 }


###   tan

province = { id = 1158 ic = 2 }
province = { id = 1146 ic = 2 }



### tra

##  eaf

province = { id = 1371  ic = 3 }
province = { id = 1338  ic = 2 }
province = { id = 1358  ic = 1 }
province = { id = 1346  ic = 1 }

province = {
	id = 1338
	naval_base = {
		size = 5
		current_size = 5
	}
}


### tun

province = { id =  747   ic =   4  }



### eng

#Aden
province = {
	id = 1053
	anti_air = 1
	
	naval_base = {
		size = 2
		current_size = 2
		}
	}
#Trincomalee
province = {
	id = 1509
	anti_air = 1
	air_base = {
		size = 2
		current_size = 2
		}

	naval_base = {
		size = 2
		current_size = 2
		}
	}
#Scapa Flow
province = {
	id = 5
	anti_air = 4
	air_base = {
		size = 4
		current_size = 4
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

#Southern England fleet&air bases
province = {
	id = 26
	anti_air = 3
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 1008
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}

	naval_base = {
		size = 2
		current_size = 2
		}
	}

# Liverpool
province = {
	id = 25
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}
	naval_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 15
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}
	naval_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 12
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}
	naval_base = {
		size = 10
		current_size = 10
		}
	}

# Portsmuth
province = {
	id = 27
	anti_air = 4
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

# Southampton
province = {
	id = 19
	anti_air = 4
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

#Gibraltar
province = {
	id = 348
	anti_air = 4
	air_base = {
		size = 4
		current_size = 4
		}

	naval_base = {
		size = 6
		current_size = 6
		}
	}


#Malta
province = {
	id = 429
	anti_air = 2
	air_base = {
		size = 4
		current_size = 4
		}

	naval_base = {
		size = 5
		current_size = 5
		}
	}


#Alexandria
province = {
	id = 789
	anti_air = 3
	air_base = {
		size = 7
		current_size = 7
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}



#Hong Kong

province = {
	id = 1371
	anti_air = 2
	air_base = {
		size = 4
		current_size = 4
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}


#Ceylon
province = {
	id = 1511
	anti_air = 2
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}


# Falklands
province = {
	id = 2045
	anti_air = 2
	air_base = {
		size = 2
		current_size = 2
		}

	naval_base = {
		size = 5
		current_size = 5
		}
	}

#Bombay
province = {
	id = 1517
	anti_air = 3
	air_base = {
		size = 10
		current_size = 10
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}
#Rangoon
province = {
	id = 1415
	anti_air = 2
	air_base = {
		size = 4
		current_size = 4
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

#Diego Garcia
province = {
	id = 998
	anti_air = 2
	air_base = {
		size = 6
		current_size = 6
		}

	naval_base = {
		size = 10
		current_size = 10
		}
	}

province = {
	id = 1773
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}

	naval_base = {
		size = 4
		current_size = 4
		}
	}


#extras
province = {
	id = 11
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
	}



province = {
	id = 929
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
	}


province = {
	id = 810
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
	}

province = {
	id = 842
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
	}

province = {
	id = 1533
	anti_air = 1
	air_base = {
		size = 8
		current_size = 8
		}
	naval_base = {
		size = 8
		current_size = 8
		}
	}
province = {
	id = 1459
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
	}
province = {
	id = 1481
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
	}
province = {
	id = 1522
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
	}

province = {
	id = 1447
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
	}

province = { 
	id = 1410
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
	}




province = {
	id = 1997
	anti_air = 1
	
	}

province = {
	id = 1758
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
        naval_base = {
		size = 2
		current_size = 2
		}
	}

province = {
	id = 850
	anti_air = 4
	air_base = {
		size = 4
		current_size = 4
		}
        
	}

province = {
	id = 716
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
        naval_base = {
		size = 2
		current_size = 2
		}
	}

province = {
	id = 1487
	
	air_base = {
		size = 4
		current_size = 4
		}
        
	}

#The Empire's Forts
province = {	id = 26		landfort = 0 coastalfort = 3 }#Dover
province = {	id = 1371	landfort = 3 coastalfort = 0 }#Hong Kong
province = {	id = 1511	landfort = 0 coastalfort = 3 }#Ceylon
province = {	id = 429	landfort = 3  coastalfort = 2 } #Gibraltar
province = {	id = 348		landfort = 0  coastalfort = 3 } #Malta


#Anti Aircraft Batteries
province = { id = 29   anti_air = 3 } #London
province = { id = 24   anti_air = 2 } #Birmingham
province = { id = 27   anti_air = 2 } #Portsmouth
province = { id = 26   anti_air = 2 } #Dover
province = { id = 23   anti_air = 2 } #Plymouth
province = { id = 25   anti_air = 2 } #Norwich
province = { id = 17   anti_air = 2 } #Liverpool
province = { id = 11   anti_air = 1 } #Glasgow
province = { id = 787  anti_air = 2 } #Cairo
province = { id = 1007 anti_air = 2 } #Suez
province = { id = 1012 anti_air = 1 } #Jerusalem
province = { id = 1371 anti_air = 2 } #Hong Kong
province = { id = 1415 anti_air = 1 } #Rangoon
province = { id = 1447 anti_air = 1 } #Calcutta
province = { id = 1459 anti_air = 1 } #Delhi
province = { id = 1487 anti_air = 1 }



#Supply pools in the empire..
province = {  id = 348  oilpool = 200 supplypool = 500 } # Gibraltar
province = {  id = 1432  oilpool = 2000 supplypool = 10000 } # Singapore
province = {  id = 429 oilpool = 100 supplypool = 500 } # Malta
province = {  id = 1371 oilpool = 100 supplypool = 500 } # Hong Kong
province = {  id = 1511  oilpool = 1000 supplypool = 2000 } # Ceylon
province = {  id = 1773 oilpool = 100 supplypool = 500 } # Bermuda
province = {  id = 964 oilpool = 1000 supplypool = 2000 } # Freetown
province = {  id = 2045 oilpool = 100 supplypool = 200 } # Falklands


### URA


province = {
	id = 2052
	anti_air = 1
	air_base = {
		size = 1
		current_size = 1
		}

	naval_base = {
		size = 6
		current_size = 6
		}
	}



### usa

# Pearl Harbor
province = {
	id = 1734
	anti_air = 3
	air_base = {
		size = 10
		current_size = 10
		}
	Naval_base = {
		size = 10
		current_size = 10
		}
}
#Clark and Bataan
province = {
	id = 1567
	anti_air = 4
	air_base = {
		size = 5
		current_size = 5
		}
	Naval_base = {
		size = 2
		current_size = 2
		}
}

province = {
	id = 1896
	anti_air = 1
	air_base = {
		size = 10
		current_size = 10
		}
}

#San Diego
province = {
	id = 1886
	anti_air = 1
	air_base = {
		size = 10
		current_size = 10
		}
	Naval_base = {
		size = 10
		current_size = 10
		}
}

# San Fransisco
province = {
	id = 1889
	anti_air = 1
	air_base = {
		size = 10
		current_size = 10
		}
	Naval_base = {
		size = 10
		current_size = 10
		}
}

# Boston
province = {
	id = 1789
	anti_air = 1
	air_base = {
		size = 10
		current_size = 10
		}
	Naval_base = {
		size = 10
		current_size = 10
		}
}
# Norfolk
province = {
	id = 1812
	anti_air = 1
	air_base = {
		size = 10
		current_size = 10
		}
	Naval_base = {
		size = 10
		current_size = 10
		}
}

#Wash DC
province = {
	id = 1809
	anti_air = 1
	
}

# New York
province = {
	id = 1795
	anti_air = 1
	
}
# Chicago
province = {
	id = 1832
	anti_air = 1
	air_base = {
		size = 10
		current_size = 10
		}
}

#Miami
province = {
	id = 1953
	anti_air = 1
	air_base = {
		size = 10
		current_size = 10
		}
	Naval_base = {
		size = 10
		current_size = 10
		}
}

# Corpus Christi
Province = {
	id = 1922
	anti_air = 1
	air_base = {
		size = 6
		current_size = 6
		}
	Naval_base = {
		size = 8
		current_size = 8
		}
}

# Anchoredge
Province = {
	id = 2142
	anti_air = 1
	
}

#Seattle
Province = {
	id = 1874
	anti_air = 1
	air_base = {
		size = 10
		current_size = 10
		}
	Naval_base = {
		size = 10
		current_size = 10
		}
}


#Wake
Province = {
	id = 1673
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
	Naval_base = {
		size = 4
		current_size = 4
		}
}

#Guam
Province = {
	id = 1683
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
	Naval_base = {
		size = 4
		current_size = 4
		}
}

#Canal Zone
Province = {
	id = 2077
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
	Naval_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 1787
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 1793
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 1806
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 1845
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 1819
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 1962
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 1960
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 1955
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 1952
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 1940
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 1831
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 1839
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 1847
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 1856
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 1838
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 1833
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 1918
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 1912
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 1860
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 1908
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 1878
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 1888
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 1887
	anti_air = 1
	

}


Province = {
	id = 1900
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 1926
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 1913
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 1928
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
}

Province = {
	id = 406
	anti_air = 6
	air_base = {
		size = 8
		current_size = 8
		}
}



province = { id = 1812   anti_air = 3 } #Norfolk
province = { id = 1809   anti_air = 3 } #Washington DC
province = { id = 1805   anti_air = 2 } #Philadelphia
province = { id = 1795   anti_air = 3 } #New York
province = { id = 1789   anti_air = 2 } #Boston
province = { id = 1832   anti_air = 2 } #Chicago
province = { id = 1887    anti_air = 2 } #Los Angeles
province = { id = 1889  anti_air = 2 } #San Francisco
province = { id = 1734   anti_air = 2 } #Honolulu
province = { id = 889   anti_air = 2 } #Colón
province = { id = 1673  anti_air = 2 } #Wake
province = { id = 1683  anti_air = 2 } #Guam

#Supplied Islands and Terr.
province = {  id = 889  supplypool = 100 } #Colon
province = {  id = 1734  supplypool = 1000 } #Pearl Harbour
province = {  id = 1739  supplypool = 100 } #Midway
province = {  id = 1738  supplypool = 1 } #Johnston
province = {  id = 1747  supplypool = 50 } #Palmyra

province = {  id = 1749  supplypool = 50 } #Samoa
province = {  id = 1673  supplypool = 100 } #Wake
province = {  id = 1683  supplypool = 100 } #Guam
province = {  id = 1765  supplypool = 50 } #Puerto Rico
province = {  id = 2150  supplypool = 500 } #Attu
province = {  id = 2141  supplypool = 1000 } #Juneau






#### ven

province = {
	id = 1988
	anti_air = 1
	air_base = {
		size = 1
		current_size = 1
		}

	naval_base = {
		size = 6
		current_size = 6
		}
	}

province = { id = 1988   anti_air = 1 } #Maracaibo
province = { id = 1993   anti_air = 2 } #Caracas


### ser
province = { id =   327  landfort = 2   }
province = { id =   330  ic =  1  landfort = 1   }
province = { id =   339  ic =  1  landfort = 2   }
province = { id =   338  landfort = 2   }
province = { id =   340  landfort = 2   }
province = { id =   342  landfort = 2   }

province = {
	id = 332		#Podgorica

	naval_base = {
		size = 3
		current_size = 3
		}
	}
province = {
	id = 350		#Split
	anti_air = 1
	air_base = {
		size = 2
		current_size = 2
		}
}
province = {
	id = 600		
	anti_air = 1
	air_base = {
		size = 5
		current_size = 5
		}

	
	}

province = {
	id = 338		#Beograd
	anti_air = 2
	air_base = {
		size = 6
		current_size = 6
		}

	}

province = {
	id = 1334		
	anti_air = 2
	air_base = {
		size = 6
		current_size = 6
		}
        naval_base = {
		size = 6
		current_size = 6
		}

	}

province = {
	id = 1218		
	anti_air = 2
	air_base = {
		size = 6
		current_size = 6
		}
        naval_base = {
		size = 6
		current_size = 6
		}

	}

province = {
	id = 825		
	anti_air = 2
	air_base = {
		size = 6
		current_size = 6
		}

	}


#Anti Aircraft Batteries
province = { id = 352   anti_air = 2 } #Zagreb
province = { id = 344   anti_air = 1 } #Osijek
province = { id = 350   anti_air = 1 } #Split
province = { id = 343   anti_air = 2 } #Dubrovnik





############
###  FRANCO-SPANISH BORDER
###########

province = {	id = 443	landfort = 3 }
province = {	id = 446	landfort = 2 }
province = {	id = 437	landfort = 3 }
province = {	id = 438	landfort = 3 }
province = {	id = 439	landfort = 3 }



province = {
	id = 1390		#Kunming
	anti_air = 1
	air_base = {
		size = 3
		current_size = 3
		}
	}

province = {
	id = 297		
	anti_air = 1
	air_base = {
		size = 3
		current_size = 3
		}
	}

province = {
	id = 242		
	anti_air = 2
	air_base = {
		size = 5
		current_size = 5
		}
	}

province = {
	id = 235		
	anti_air = 2
	air_base = {
		size = 5
		current_size = 5
		}
	}


province = {
	id = 355		
	anti_air = 2
	air_base = {
		size = 5
		current_size = 5
		}
	}

province = {
	id = 288		
	anti_air = 2
	air_base = {
		size = 5
		current_size = 5
		}
	}

province = {
	id = 636		
	anti_air = 4
	air_base = {
		size = 5
		current_size = 5
		}
	}

province = {
	id = 694		
	anti_air = 2
	air_base = {
		size = 2
		current_size = 2
		}
         naval_base = {
		size = 2
		current_size = 2
		}
	}

province = {
	id = 1081		
	anti_air = 1
	air_base = {
		size = 2
		current_size = 2
		}
         naval_base = {
		size = 2
		current_size = 2
		}
	}

province = {
	id = 1097		
	anti_air = 1
	air_base = {
		size = 2
		current_size = 2
		}
         naval_base = {
		size = 2
		current_size = 2
		}
	}


province = {
	id = 23		
	anti_air = 4
	air_base = {
		size = 4
		current_size = 4
		}
         naval_base = {
		size = 5
		current_size = 5
		}
	}

province = {
	id = 706	
	anti_air = 1
	air_base = {
		size = 4
		current_size = 4
		}
         naval_base = {
		size = 5
		current_size = 5
		}
	}

province = {
	id = 1236		
	anti_air = 2
	air_base = {
		size = 6
		current_size = 6
		}
	}

province = {
	id = 21		
	anti_air = 2
	air_base = {
		size = 4
		current_size = 4
		}
	}

province = {
	id = 1216		
	anti_air = 2
	air_base = {
		size = 5
		current_size = 5
		}
	}

province = {
	id = 1247		
	anti_air = 4
	air_base = {
		size = 6
		current_size = 6
		}
	}

province = {
	id = 1378		
	anti_air = 2
	air_base = {
		size = 4
		current_size = 4
		}
	}

province = {
	id = 1365		
	anti_air = 2
	air_base = {
		size = 4
		current_size = 4
		}
	}

province = {
	id = 1351		
	anti_air = 1
	air_base = {
		size = 2
		current_size = 2
		}
	}

province = {
	id = 1085		
	anti_air = 2
	air_base = {
		size = 3
		current_size = 3
		}
	}

province = {
	id = 326		
	
	air_base = {
		size = 3
		current_size = 3
		}
	}

province = {
	id = 363		
	
	air_base = {
		size = 3
		current_size = 3
		}
	}

