
####################################
# Country definition for Indonesia #
####################################

country =
{ tag                 = INO
  energy              = 3000
  metal               = 3000
  rare_materials      = 5000
  oil                 = 1000
  supplies            = 5000
  money               = 5000
  capital             = 1613
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 3
    political_left    = 4
    freedom           = 4
    free_market       = 5
    professional_army = 5
    defense_lobby     = 4
    interventionism   = 8
  }
  diplomacy = { 
	relation = { tag = USA value = 100 }
	}
  ownedprovinces      = {
1631 1354 1355 1356 1357 1358 1359 1635 1636 1637 1638 1639 1640 1641 
1642 1645 1648 1649 1650 1651 1652 1653 1654 1655 1656 1657 1659 1660 
1661 1662 1663 1664 1665 1673 1674
1628 1629 1630 1632 1633 1634 
1616 2938 2939 2234 2238 1613 1612 1373 661 2940 1615 1762 1658 1757 2111
5747 5748 5749 5750 5751 5752 5753 5754 5755 5756 
5757 5758 5759 5760 5761 5762 5763 5764 5765 5766 
5767 5768 5769 5770 5771 5772 5773 5774 5775 5776 
5777 5778 5779 5780 5781 5782 5783 5784 5785 5786 
5787 5788 5789 5790 5791 5792 5793 5794 5795 5796 
5797 5798 5799 5800 5801 5802 5803 5804 5805 5806 
5807 5808 5809 5810 5811 5812 5813 5814 5815 5816 
5817 5818 5819 5820 5821 5822 5823 5824 5825 5826 
5827 5828 5829 5830 5831 5832 5833 5834 5835 5837 
5838 5839 5840 5841 5842 5843 5844 5845 5846 5847 
5848 5849 5850 5851 5852
	}
  controlledprovinces = {
1631 1354 1355 1356 1357 1358 1359 1635 1636 1637 1638 1639 1640 1641 
1642 1645 1648 1649 1650 1651 1652 1653 1654 1655 1656 1657 1659 1660 
1661 1662 1663 1664 1665 1673 1674
1628 1629 1630 1632 1633 1634 
1616 2938 2939 2234 2238 1613 1612 1373 661 2940 1615 1762 1658 1757 2111
5747 5748 5749 5750 5751 5752 5753 5754 5755 5756 
5757 5758 5759 5760 5761 5762 5763 5764 5765 5766 
5767 5768 5769 5770 5771 5772 5773 5774 5775 5776 
5777 5778 5779 5780 5781 5782 5783 5784 5785 5786 
5787 5788 5789 5790 5791 5792 5793 5794 5795 5796 
5797 5798 5799 5800 5801 5802 5803 5804 5805 5806 
5807 5808 5809 5810 5811 5812 5813 5814 5815 5816 
5817 5818 5819 5820 5821 5822 5823 5824 5825 5826 
5827 5828 5829 5830 5831 5832 5833 5834 5835 5837 
5838 5839 5840 5841 5842 5843 5844 5845 5846 5847 
5848 5849 5850 5851 5852
	}
  nationalprovinces   = {
1631 1354 1355 1356 1357 1358 1359 1635 1636 1637 1638 1639 1640 1641 
1642 1645 1648 1649 1650 1651 1652 1653 1654 1655 1656 1657 1659 1660 
1661 1662 1663 1664 1665 1673 1674
1628 1629 1630 1632 1633 1634 
1616 2938 2939 2234 2238 1613 1612 1373 661 2940 1615 1762 1658 1757 2111
5747 5748 5749 5750 5751 5752 5753 5754 5755 5756 
5757 5758 5759 5760 5761 5762 5763 5764 5765 5766 
5767 5768 5769 5770 5771 5772 5773 5774 5775 5776 
5777 5778 5779 5780 5781 5782 5783 5784 5785 5786 
5787 5788 5789 5790 5791 5792 5793 5794 5795 5796 
5797 5798 5799 5800 5801 5802 5803 5804 5805 5806 
5807 5808 5809 5810 5811 5812 5813 5814 5815 5816 
5817 5818 5819 5820 5821 5822 5823 5824 5825 5826 
5827 5828 5829 5830 5831 5832 5833 5834 5835 5837 
5838 5839 5840 5841 5842 5843 5844 5845 5846 5847 
5848 5849 5850 5851 5852
7991
	}
  techapps = {
   ###################
   #     Infantry    #
   ###################
   #Infantry
   1010 1020 1030
   #Motorized
   1100 1110 1120
   #Mountain
   1160 1170 1180
   #Special Forces
   1250 1260 1270
   #Naval Infantry
   1560 1570 1580
   #Airborne Infantry
   1670 1680 1690
   #Air Cavalry
   1396 1400
   #Armored Cavalry
   13060 13070
   #Mechanized
   1470 1480 1490
   #Irregular Infantry
   1360 1370 1380
   #Combat Engineers
   1830 1840 1850
   #Supply and Repair
   1990 199100 199110 199130 
   ###################
   #Armor & Artillery#
   ###################
   #Main Battle Tanks
   2620 2010 2630 2640 2646
   #Infantry Fighting Vehicles	
   2100
   #Armored Cars
   2860 2870 2950 
   #Anti-Air
   2800 2450 21180
   #Armored Personnel Carriers
   2170 2180 2850 2400 
   #Field Artillery
   2290 2300 2310
   #Self-Propelled Anti-Air
   2810 2820 2510
   #Man-Portable Air-Defense Systems
   3000 3170
   #Self-Propelled Artillery
   2220 2230
   #Self-Propelled Rocket Artillery
   2980 2260 2270
   ###################
   #     Naval       #
   ###################
   #Frigates
   3110 3120 3130
   #Cruisers
   3410 3420 3430 3440
   #Destroyers
   3310 3320 3330 3340
   #Light Aircraft Carriers
   12100
   #Submarines
   3010 3020 3030
   #Transport Ships
   3900 3910 3920
   ###################
   #    Aircraft     #
   ###################
   #Attack Helicopter
   4900
   #Reconnaissance Aircraft
   4770
   #Strategic Bomber
   4800
   #Strike Bomber
   15040
   #Naval Patrol
   4610
   #ASW Bomber
   4230
   #Attack Aircraft
   4030 4060 4090
   #Multi-Role
   4500 4570 4530 4540
   #Air Superiority Fighter
   4510 4520
   #Air Transports
   4250 4260
   #AEW&C
   4450 #4180
   #Air-to-Ground Missiles
   4040
   #Air-to-Air Missiles
   4600
   #Air-to-Sea Missiles
   4740
   ###################
   #    Industry     #
   ###################
   #Light Industry
   5810 5820
   #Heavy Industry
   5130 5110
   #Material Science
   53050 63160 63070
   #Construction Eng.
   5800 5080
   #Rocketry

   #Agriculture
   5700 5710 5010
   #Oil
   5190 5220
   #Computing
   5310 54010 54020
   #Nuclear
   5470 5480 5490
   #Research
   5316
   #Cryptography
   5350 5360
   #Medicine
   5600 5610
   5630
   5660 5730
   ###################
   #  Land Doctrines #
   ###################
   6500 
   6510 6530 
   1650
   6560 #Defensive
   ###################
   # Naval Doctrines #
   ###################
   #Surface Ship Role
   81050 81060 81070 81080 81090 81100 81110 81120
   #Naval Interdiction
   8500 8510 8520 8550 8560 8570 8600 8610 8620
   #Naval Supremacy
   8100 8110 8150 8120 8160 8170 8200 8210 8220
   #Logistics Support
   82500 82510 82520 82530
   #Naval Capability
   8010
   #Amphibious Warfare
   82300
   ###################
   #  Air Doctrines  #
   ###################
   9390 9260 9400 9410
   9090 9100 9110 9120 9050 9060 9070
   9190 9200 9210 9220 9310 9320 9330 9340 9230 9240 9250
   9130 9420 9300
   }

  # #####################################
  # ARMY
  # #####################################
  landunit =
  { id       = { type = 12400 id = 1 }
    location = 1613 #1647
    name     = "Army Strategic Reserve Command"
    division =
    { id       = { type = 12400 id = 2 }
      name     = "1st Infantry Division"
      strength = 100
      type     = motorized
      model    = 3
    }
    division =
    { id       = { type = 12400 id = 3 }
      name     = "2nd Infantry Division"
      strength = 100
      type     = motorized
      model    = 3
    }
    division =
    { id       = { type = 12400 id = 4 }
      name     = "1st Cavalry Brigade"
      strength = 100
      type     = cavalry
      model    = 3
    }
    division =
    { id       = { type = 12400 id = 5 }
      name     = "3rd Airborne Brigade"
      strength = 100
      type     = d_08
      model    = 3
    }
  }
  landunit =
  { id       = { type = 12400 id = 6 }
    location = 1613 #1647
    name     = "Special Forces Command"
    division =
    { id       = { type = 12400 id = 7 }
      name     = "Paracommando"
      strength = 100
      type     = d_03
      model    = 4
    }
  }
  landunit =
  { id       = { type = 12400 id = 8 }
    location = 1355 #1640
    name     = "Kodam Iskandar Muda"
    division =
    { id            = { type = 12400 id = 9 }
      name          = "Kodam Iskandar Muda"
      strength      = 100
      type          = garrison
      model         = 2
    }
  }
  landunit =
  { id       = { type = 12400 id = 10 }
    location = 5776 #1637
    name     = "Kodam I/Bukit Barisan"
    division =
    { id            = { type = 12400 id = 11 }
      name          = "Kodam I/Bukit Barisan"
      strength      = 100
      type          = garrison
      model         = 2
    }
  }
  landunit =
  { id       = { type = 12400 id = 12 }
    location = 1358 #1636
    name     = "Kodam II/Sriwijaya"
    division =
    { id            = { type = 12400 id = 13 }
      name          = "Kodam I/Bukit Barisan"
      strength      = 100
      type          = garrison
      model         = 2
    }
  }
  landunit =
  { id       = { type = 12400 id = 14 }
    location = 1613 #1647
    name     = "Kodam Jaya"
    division =
    { id            = { type = 12400 id = 15 }
      name          = "Kodam Jaya"
      strength      = 100
      type          = garrison
      model         = 2
    }
  }
  landunit =
  { id       = { type = 12400 id = 16 }
    location = 1629 #1651
    name     = "Kodam III/Siliwangi"
    division =
    { id            = { type = 12400 id = 17 }
      name          = "Kodam III/Siliwangi"
      strength      = 100
      type          = garrison
      model         = 2
    }
  } 
  landunit =
  { id       = { type = 12400 id = 18 }
    location = 1631 #1654
    name     = "Kodam IV/Diponegoro"
    division =
    { id            = { type = 12400 id = 19 }
      name          = "Kodam IV/Diponegoro"
      strength      = 100
      type          = garrison
      model         = 2
    }
  }
  landunit =
  { id       = { type = 12400 id = 20 }
    location = 1632 #1653
    name     = "Kodam V/Brawijaya"
    division =
    { id            = { type = 12400 id = 21 }
      name          = "Kodam V/Brawijaya"
      strength      = 100
      type          = garrison
      model         = 2
    }
  }
  landunit =
  { id       = { type = 12400 id = 22 }
    location = 1641 #1630
    name     = "Kodam VI/Tanjungpura"
    division =
    { id            = { type = 12400 id = 23 }
      name          = "Kodam VI/Tanjungpura"
      strength      = 100
      type          = garrison
      model         = 2
    }
  }
  landunit =
  { id       = { type = 12400 id = 24 }
    location = 1640 #1657
    name     = "Kodam VII/Wirabuana"
    division =
    { id            = { type = 12400 id = 25 }
      name          = "Kodam VII/Wirabuana"
      strength      = 100
      type          = garrison
      model         = 2
    }
  }
  landunit =
  { id       = { type = 12400 id = 26 }
    location = 1635 #1643
    name     = "Kodam IX/Udayana"
    division =
    { id            = { type = 12400 id = 27 }
      name          = "Kodam IX/Udayana"
      strength      = 100
      type          = garrison
      model         = 2
    }
  }
  landunit =
  { id       = { type = 12400 id = 28 }
    location = 5810 #1622
    name     = "Kodam XVI/Pattimura"
    division =
    { id            = { type = 12400 id = 29 }
      name          = "Kodam XVI/Pattimura"
      strength      = 100
      type          = garrison
      model         = 2
    }
  }
  landunit =
  { id       = { type = 12400 id = 30 }
    location = 1665 #1596
    name     = "Kodam XVII/Cendrawasih"
    division =
    { id            = { type = 12400 id = 31 }
      name          = "Kodam XVII/Cendrawasih"
      strength      = 100
      type          = garrison
      model         = 2
    }
  }
  landunit =
  { id       = { type = 12400 id = 32 }
    location = 1632 #1653
    name     = "Eastern Fleet Marines"
    division =
    { id            = { type = 12400 id = 33 }
      name          = "1st Marine Brigade"
      strength      = 100
      type          = d_05
      model         = 4
    }
  }
  landunit =
  { id       = { type = 12400 id = 34 }
    location = 1613 #1647
    name     = "Wetern Fleet Marines"
    division =
    { id            = { type = 12400 id = 35 }
      name          = "2nd Marine Brigade"
      strength      = 100
      type          = d_05
      model         = 4
    }
  }
  # ###################################
  # NAVY
  # ###################################
  navalunit =
  { id       = { type = 12400 id = 300 }
    location = 1613 #1647
    base     = 1613 #1647
    name     = "Western Fleet"
    division =
    { id    = { type = 12400 id = 301 }
      name  = "KRI Ahmad Yani"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 12400 id = 302 }
      name  = "KRI Slamet Riyadi"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 12400 id = 303 }
      name  = "KRI Yos Sudarso"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 12400 id = 304 }
      name  = "KRI Oswald Sihaan"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 12400 id = 305 }
      name  = "KRI Abdul Halim Perdanakasuma"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 12400 id = 307 }
      name  = "KRI Hasanaddun"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 12400 id = 308 }
      name  = "KRI Samadikum"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 12400 id = 317 }
      name  = "KRI Cakra"
      type  = submarine
      model = 5
    }
  }
  navalunit =
  { id       = { type = 12400 id = 318 }
    location = 1613 #1647
    base     = 1613 #1647
    name     = "Western Fleet Transports"
    division =
    { id    = { type = 12400 id = 319 }
      name  = "1st Transport Flotilla"
      type  = transport
      model = 4
    }
    division =
    { id    = { type = 12400 id = 320 }
      name  = "2nd Transport Flotilla"
      type  = transport
      model = 4
    }
    division =
    { id    = { type = 12400 id = 321 }
      name  = "3rd Transport Flotilla"
      type  = transport
      model = 4
    }
    division =
    { id    = { type = 12400 id = 322 }
      name  = "4th Transport Flotilla"
      type  = transport
      model = 4
    }
    division =
    { id    = { type = 12400 id = 323 }
      name  = "5th Transport Flotilla"
      type  = transport
      model = 4
    }
  }
  navalunit =
  { id       = { type = 12400 id = 333 }
    location = 1632 #1653
    base     = 1632 #1653
    name     = "Eastern Fleet"
    division =
    { id    = { type = 12400 id = 334 }
      name  = "KRI Karel Satsuitubun"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 12400 id = 335 }
      name  = "KRI Fatahilah"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 12400 id = 336 }
      name  = "KRI Malahayati"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 12400 id = 337 }
      name  = "KRI Nala"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 12400 id = 338 }
      name  = "KRI Martadinata"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 12400 id = 339 }
      name  = "KRI Mongisidi"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 12400 id = 340 }
      name  = "KRI Ngurah"
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 12400 id = 349 }
      name  = "KRI Nanggala"
      type  = submarine
      model = 5
    }
  }
  navalunit =
  { id       = { type = 12400 id = 350 }
    location = 1632 #1653
    base     = 1632 #1653
    name     = "Eastern Fleet Transports"
    division =
    { id    = { type = 12400 id = 351 }
      name  = "6th Transport Flotilla"
      type  = transport
      model = 4
    }
    division =
    { id    = { type = 12400 id = 352 }
      name  = "7th Transport Flotilla"
      type  = transport
      model = 4
    }
    division =
    { id    = { type = 12400 id = 353 }
      name  = "8th Transport Flotilla"
      type  = transport
      model = 4
    }
  }
  # ####################################
  # AIR FORCE
  # ####################################
  airunit =
  { id       = { type = 12400 id = 200 }
    location = 1359 #1638
    base     = 1359 #1638
    name     = "1st Air Force"
    division =
    { id       = { type = 12400 id = 201 }
      name     = "1st Squadron"
      type     = interceptor
      strength = 100
      model    = 3
    }
    division =
    { id       = { type = 12400 id = 202 }
      name     = "2nd Squadron"
      type     = interceptor
      strength = 100
      model    = 3
    }
  }
}