#################
# Installations #
#################
province =
{ id         = 954 #633
  naval_base = { size = 1 current_size = 1 }
}
province =
{ id       = 67
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
}            # Essen
province = { id = 74 anti_air = 2 } # Saarbrücken
province = { id = 1015 anti_air = 2 }
province = { id = 3250 anti_air = 2 }
province = { id = 76 anti_air = 2 } # Dortmund
province =
{ id         = 80
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # Wilhelmshafen
province =
{ id       = 82
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
}            # Kassel
province =
{ id       = 88
  anti_air = 2
  naval_base = { size = 10 current_size = 10 }
}            # Hamburg
province = { id = 89 anti_air = 1 } # Lübeck
province =
{ id         = 90
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # Kiel
province =
{ id         = 296
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # Rostock
province = { id = 298 anti_air = 2 } # Magdeburg
province =
{ id       = 300
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
}            # Berlin
province = { id = 304 supplypool = 100 } # Elbing
province = { id = 310 anti_air = 1 } # Leipzig
province = { id = 312 anti_air = 1 } # Nuremberg
province =
{ id       = 313
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
}            # Frankfurt-am-Main
province =
{ id       = 314
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Stuttgart
province =
{ id       = 376
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
}            # Munich
province =
{ id       = 473
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
}            # Breslau
province =
{ id         = 510
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Königsberg

##############################
# Country definition for POL #
##############################

province = { id = 208 anti_air = 1 } # Wilno
province =
{ id       = 211
  air_base = { size = 3 current_size = 3 }
  anti_air = 3
}            # Lida
province =
{ id       = 229
  air_base = { size = 4 current_size = 4 }
}            # Stanislawow
province =
{ id         = 306
  anti_air   = 2
  naval_base = { size = 8 current_size = 8 }
  air_base   = { size = 4 current_size = 4 }
}              # Gdynia
province = { id = 305 anti_air = 1 } # Torun
province = { id = 307 anti_air = 2 } # Poznan
province = { id = 479 anti_air = 2 } # Cracow
province =
{ id       = 483
  anti_air = 4
  air_base = { size = 4 current_size = 4 }
}            # Lodz
province =
{ id       = 485
  anti_air = 2
  air_base = { size = 6 current_size = 6 }
}            # Warsaw
province =
{ id       = 504
  air_base = { size = 3 current_size = 3 }
}            # Brest Litovsk
province = { id = 509 anti_air = 1 } # Suwalki

##############################
# Country definition for CZE #
##############################

province =
{ id       = 469
  anti_air = 2
  air_base = { size = 3 current_size = 3 }
}            # Prague
province = { id = 470 anti_air = 2 } # Pilsen
province = { id = 475 anti_air = 2 } # Brno
province =
{ id       = 476
  anti_air = 2
  air_base = { size = 1 current_size = 1 }
  landfort = 2
  ic       = 5
}            # Bratislava
province = { id = 490 ic = 3 } # Kosice

##############################
# Country definition for AUS #
##############################

province =
{ id       = 377
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Innsbruck
province = { id = 461 anti_air = 1 } # Klagenfurt
province =
{ id       = 463
  anti_air = 4
  air_base = { size = 10 current_size = 10 }
}            # Vienna

##############################
# Country definition for HUN #
##############################

province = { id = 456 ic = 2 } # Pecs
province =
{ id       = 457
  anti_air = 2
  air_base = { size = 8 current_size = 8 }
  ic       = 2
}            # Budapest
province = { id = 497 ic = 2 } # Debrecen

##############################
# Country definition for SCH #
##############################

province = { id = 372 landfort = 4 anti_air = 3 } # Chur
province = { id = 530 landfort = 5 anti_air = 3 } # Geneva
province =
{ id       = 532
  anti_air = 5
  air_base = { size = 4 current_size = 4 }
  landfort = 5
}            # Bern
province = { id = 533 landfort = 5 anti_air = 3 } # Zürich

##############################
# Country definition for HOL #
##############################

province =
{ id         = 46
  anti_air   = 2
  naval_base = { size = 10 current_size = 10 }
}              # Rotterdam
province =
{ id         = 47
  anti_air   = 2
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
}              # Amsterdam
province = { id = 49 anti_air = 2 } # Eindhoven
province =
{ id         = 1359
  anti_air   = 2
  naval_base = { size = 7 current_size = 7 }
  air_base   = { size = 4 current_size = 4 }
  supplypool = 1
}              # Oosthaven
province =
{ id         = 1628
  anti_air   = 2
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 4 current_size = 4 }
  oilpool    = 1
  supplypool = 100
}              # Batavia
province =
{ id         = 1632
  anti_air   = 2
  naval_base = { size = 7 current_size = 7 }
}              # Soerabaja
province = { id = 1641 supplypool = 1 } # Bandjermasin
province =
{ id         = 1653
  anti_air   = 2
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 2 current_size = 2 }
}              # Menado

##############################
# Country definition for BEL #
##############################

province =
{ id         = 45
  naval_base = { size = 3 current_size = 3 }
}              # Ghent
province =
{ id       = 50
  air_base = { size = 6 current_size = 3 }
  anti_air = 2
}            # Antwerp
province =
{ id       = 51
  air_base = { size = 6 current_size = 6 }
  anti_air = 1
}            # Brussels
province = { id = 68 anti_air = 2 } # Liège
province =
{ id         = 1095
  oilpool    = 1
  supplypool = 50
  air_base   = { size = 1 current_size = 1 }
  naval_base = { size = 3 current_size = 3 }
}              # Banana

##############################
# Country definition for LIT #
##############################

province =
{ id         = 2606
  anti_air   = 1
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 1 current_size = 1 }
}              # Memel
province =
{ id       = 207
  air_base = { size = 2 current_size = 2 }
}            # Kaunas

##############################
# Country definition for LAT #
##############################

province =
{ id         = 197
  anti_air   = 1
  air_base   = { size = 1 current_size = 1 }
  naval_base = { size = 3 current_size = 3 }
}              # Riga

##############################
# Country definition for EST #
##############################

province =
{ id         = 194
  anti_air   = 2
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 2 current_size = 2 }
}              # Tallinn

##############################
# Country definition for ROM #
##############################

province =
{ id         = 423
  anti_air   = 2
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 1 current_size = 1 }
  ic         = 1
}              # Constanta
province =
{ id       = 424
  anti_air = 2
  air_base = { size = 5 current_size = 5 }
}            # Bucharest
province = { id = 431 anti_air = 3 ic = 2 } # Ploesti
province = { id = 435 anti_air = 1 } # Ismail

##############################
# Country definition for YUG #
##############################

province = { id = 382 anti_air = 2 } # Zagreb
province =
{ id         = 384
  anti_air   = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 3 current_size = 3 }
}              # Split
province = { id = 388 anti_air = 2 } # Dubrovnik
province =
{ id         = 389
  naval_base = { size = 3 current_size = 3 }
}              # Podgorica
province =
{ id       = 453
  anti_air = 3
  air_base = { size = 6 current_size = 6 }
}            # Belgrade

##############################
# Country definition for ALB #
##############################

province =
{ id         = 5466
  anti_air   = 1
  naval_base = { size = 6 current_size = 6 }
  air_base   = { size = 2 current_size = 2 }
}              # Tirana

##############################
# Country definition for BUL #
##############################

province = { id = 417 anti_air = 2 ic = 2 } # Sofia
province = { id = 420 ic = 2 } # Pleven
province =
{ id         = 422
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 5 current_size = 5 }
  ic         = 2
}              # Varna

##############################
# Country definition for GRE #
##############################

province =
{ id         = 396
  anti_air   = 1
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
}              # Crete
province =
{ id         = 401
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # Athens
province = { id = 411 anti_air = 2 } # Salonika

##############################
# Country definition for TUR #
##############################

province =
{ id         = 439
  anti_air   = 4
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 10 current_size = 10 }
}              # Izmit
province =
{ id       = 448
  anti_air = 4
  air_base = { size = 6 current_size = 6 }
}            # Ankara

##############################
# Country definition for DEN #
##############################

province =
{ id         = 1
  anti_air   = 1
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # Reykjavik
province =
{ id         = 292
  anti_air   = 1
  naval_base = { size = 1 current_size = 1 }
  air_base   = { size = 4 current_size = 4 }
}              # Aalborg
province =
{ id         = 294
  anti_air   = 2
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
}              # Copenhagen

##############################
# Country definition for NOR #
##############################

province =
{ id          = 107
  anti_air    = 2
  air_base    = { size = 4 current_size = 4 }
  landfort    = 0
  coastalfort = 3
}               # Oslo
province =
{ id          = 110
  anti_air    = 2
  naval_base  = { size = 10 current_size = 10 }
  air_base    = { size = 5 current_size = 5 }
  landfort    = 0
  coastalfort = 3
}               # Bergen
province = { id = 118 landfort = 0 coastalfort = 2 } # Trondheim
province =
{ id         = 2276
  anti_air   = 1
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 1 current_size = 1 }
}              # Narvik

##############################
# Country definition for SWE #
##############################

province =
{ id         = 101
  anti_air   = 5
  naval_base = { size = 5 current_size = 5 }
  air_base   = { size = 3 current_size = 3 }
}  

province =
{ id         = 98
  naval_base = { size = 5 current_size = 5 }
  air_base   = { size = 3 current_size = 3 }
} 

##############################
# Country definition for FIN #
##############################

province =
{ id       = 137
  air_base = { size = 10 current_size = 10 }
}            # Oulu
province =
{ id          = 141
  coastalfort = 1
  anti_air    = 2
  naval_base  = { size = 5 current_size = 5 }
  air_base    = { size = 10 current_size = 10 }
}               # Turku
province =
{ id          = 142
  coastalfort = 1
  anti_air    = 3
  naval_base  = { size = 5 current_size = 5 }
  air_base    = { size = 10 current_size = 10 }
}               # Helsinki
province =
{ id       = 143
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
}            # Tampere
province = { id = 145 anti_air = 3 } # Viipuri

##############################
# Country definition for SOV #
##############################

province =
{ id         = 133
  anti_air   = 4
  naval_base = { size = 7 current_size = 7 }
  air_base   = { size = 4 current_size = 4 }
}              # Murmansk
province =
{ id         = 154
  anti_air   = 4
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 4 current_size = 4 }
}              # Archangelsk
province =
{ id          = 163
  air_base    = { size = 4 current_size = 4 }
  landfort    = 5
  coastalfort = 0
  anti_air    = 3
}               # Stalingrad
province =
{ id          = 175
  air_base    = { size = 10 current_size = 10 }
  landfort    = 5
  coastalfort = 0
  anti_air    = 4
}               # Moscow
province =
{ id       = 181
  air_base = { size = 3 current_size = 3 }
  anti_air = 1
}            # Kaluga
province =
{ id          = 187
  anti_air    = 6
  naval_base  = { size = 10 current_size = 10 }
  air_base    = { size = 10 current_size = 10 }
  landfort    = 5
  coastalfort = 5
}               # Leningrad
province = { id = 191 anti_air = 1 } # Porkhov
province =
{ id       = 201
  air_base = { size = 6 current_size = 6 }
}            # Opochka
province =
{ id       = 217
  air_base = { size = 2 current_size = 2 }
  anti_air = 2
}            # Vitebsk
province = { id = 219 anti_air = 3 } # Smolensk
province =
{ id       = 220
  air_base = { size = 8 current_size = 8 }
}            # Mogilev
province =
{ id       = 233
  air_base = { size = 4 current_size = 4 }
  anti_air = 3
}            # Odessa
province =
{ id       = 238
  air_base = { size = 8 current_size = 8 }
  anti_air = 3
}            # Kiev
province = { id = 246 anti_air = 2 } # Zaporozhye
province =
{ id       = 248
  air_base = { size = 2 current_size = 2 }
  anti_air = 1
}            # Kharkov
province =
{ id          = 253
  anti_air    = 6
  naval_base  = { size = 10 current_size = 10 }
  air_base    = { size = 6 current_size = 6 }
  landfort    = 3
  coastalfort = 5
}               # Sevastopol
province =
{ id       = 258
  air_base = { size = 4 current_size = 4 }
  anti_air = 2
}            # Rostov
province = { id = 263 anti_air = 1 } # Svoboda
province =
{ id       = 264
  air_base = { size = 2 current_size = 2 }
}            # Pavlovsk
province =
{ id       = 273
  air_base = { size = 2 current_size = 2 }
}            # Gomel
province = { id = 277 anti_air = 2 } # Bryansk
province =
{ id       = 282
  air_base = { size = 5 current_size = 5 }
}            # Orel
province =
{ id       = 289
  air_base = { size = 2 current_size = 2 }
}            # Demyansk

province =
{ id         = 1175
  anti_air   = 2
}              # Ocha
province =
{ id       = 1368
  air_base = { size = 1 current_size = 1 }
}            # Komsomolsk-na-Amure
province =
{ id          = 1372
  anti_air    = 5
  naval_base  = { size = 10 current_size = 10 }
  air_base    = { size = 10 current_size = 10 }
  landfort    = 1
  coastalfort = 3
}               # Vladivostok
province =
{ id       = 1416
  air_base = { size = 3 current_size = 3 }
}            # Irkutsk
province = { id = 1422 ic = 6 } # Alma-Ata
province = { id = 1427 ic = 3 } # Tashkent
province = { id = 1429 ic = 5 } # Frunze
province = { id = 1485 ic = 4 } # Stalinabad
province = { id = 1490 ic = 3 } # Ashgabat
province =
{ id       = 1523
  air_base = { size = 2 current_size = 2 }
}            # Tynda
province =
{ id         = 1525
  anti_air   = 2
  air_base   = { size = 1 current_size = 1 }
}              # Okhotsk
province =
{ id       = 1538
  air_base = { size = 1 current_size = 1 }
}            # Severo-Yenisejsk
province =
{ id       = 1544
  air_base = { size = 2 current_size = 2 }
}            # Tomsk
province = { id = 1548 ic = 6 } # Novosibirsk
province =
{ id       = 1550
  air_base = { size = 2 current_size = 2 }
}            # Semipalatinsk
province =
{ id       = 1552
  air_base = { size = 1 current_size = 1 }
}            # Omsk
province = { id = 1572 ic = 4 } # Sverdlovsk
province =
{ id       = 1574
  air_base = { size = 1 current_size = 1 }
}            # Chelyabinsk
province =
{ id       = 1827
  air_base = { size = 2 current_size = 2 }
}            # Naberezhnye Chelny
province =
{ id       = 1828
  air_base = { size = 4 current_size = 4 }
}            # Kuybyshev
province =
{ id       = 1832
  air_base = { size = 3 current_size = 3 }
}            # Saratov
province =
{ id       = 1838
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Astrakhan
province =
{ id       = 1839
  air_base = { size = 2 current_size = 2 }
}            # Novouzensk
province =
{ id         = 1848
  anti_air   = 2
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 4 current_size = 4 }
}              # Batum
province = { id = 1850 ic = 7 } # Tblisi
province = { id = 1856 ic = 5 } # Yerevan

##############################
# Country definition for ENG #
##############################

province =
{ id         = 5
  anti_air   = 4
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # Scapa Flow
province =
{ id       = 9
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Glasgow
province =
{ id         = 13
  anti_air   = 2
  air_base   = { size = 10 current_size = 10 }
}              # Sheffield

province = { id = 16 anti_air = 2 } # Birmingham
province =
{ id         = 17
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Norwich
province = { id = 19 anti_air = 3 } # London
province =
{ id          = 20
  anti_air    = 5
  air_base    = { size = 10 current_size = 10 }
  naval_base  = { size = 10 current_size = 10 }
  landfort    = 0
  coastalfort = 3
}               # Dover
province =
{ id         = 21
  anti_air   = 6
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Portsmouth
province =
{ id         = 23
  anti_air   = 6
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Plymouth
province = { id = 28 oilpool = 1000 supplypool = 2000 } # Belfast
province =
{ id          = 31
  anti_air    = 2
  air_base    = { size = 4 current_size = 4 }
  naval_base  = { size = 5 current_size = 5 }
  landfort    = 0
  coastalfort = 1
  oilpool     = 1000
  supplypool  = 1000
}               # Malta
province =
{ id          = 348
  anti_air    = 6
  air_base    = { size = 4 current_size = 4 }
  naval_base  = { size = 10 current_size = 10 }
  landfort    = 6
  coastalfort = 0
  oilpool     = 1000
  supplypool  = 1000
}               # Gibraltar
province =
{ id       = 444
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Cyprus
province =
{ id         = 538
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  oilpool    = 100
  supplypool = 500
}              # Bermuda
province =
{ id         = 576
  anti_air   = 2
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 10 current_size = 10 }
}              # Newfoundland
province =
{ id       = 652
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Andros
province =
{ id         = 866
  anti_air   = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 5 current_size = 5 }
  oilpool    = 100
  supplypool = 200
}              # Falkland Islands
province =
{ id       = 873
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Georgetown
province = { id = 900 anti_air = 2 } # Suez
province = { id = 901 anti_air = 2 oilpool = 1000 supplypool = 2000 } # Port Said
province = { id = 903 anti_air = 2 } # Cairo
province =
{ id         = 907
  anti_air   = 5
  air_base   = { size = 7 current_size = 7 }
  naval_base = { size = 10 current_size = 10 }
}              # Alexandria
province =
{ id         = 988
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
  oilpool    = 1000
  supplypool = 2000
}              # Freetown
province =
{ id       = 1002
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Accra
province =
{ id       = 1008
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Lagos
province =
{ id       = 1061
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Mombasa
province =
{ id       = 1066
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Khartoum
province =
{ id       = 1296
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Mandalay
province =
{ id         = 1299
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # Rangoon
province =
{ id          = 1315
  anti_air    = 4
  air_base    = { size = 4 current_size = 4 }
  naval_base  = { size = 10 current_size = 10 }
  coastalfort = 1
  oilpool     = 1000
  supplypool  = 1000
}               # Hong Kong
province =
{ id          = 1353
  anti_air    = 6
  air_base    = { size = 8 current_size = 8 }
  naval_base  = { size = 10 current_size = 10 }
  landfort    = 0
  coastalfort = 3
  oilpool     = 1000
  supplypool  = 2000
}               # Singapore
province =
{ id       = 1457
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Calcutta
province =
{ id       = 1467
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Indore
province =
{ id       = 1469
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Delhi
province =
{ id         = 1494
  anti_air   = 1
  air_base   = { size = 8 current_size = 8 }
}              
province =
{ id         = 1505
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  oilpool    = 1000
  supplypool = 2000
}              # Bombay
province =
{ id       = 1514
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Cochin
province =
{ id          = 1517
  anti_air    = 2
  air_base    = { size = 10 current_size = 10 }
  naval_base  = { size = 10 current_size = 10 }
  landfort    = 0
  coastalfort = 3
  oilpool     = 1000
  supplypool  = 2000
}               # Colombo
province =
{ id       = 1644
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Kuching
province = { id = 1797 anti_air = 1 } # Jerusalem
province =
{ id         = 1798
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
}              # Tel Aviv
province =
{ id         = 1813
  anti_air   = 1
  naval_base = { size = 2 current_size = 2 }
}              # Aden
province =
{ id         = 1817
  anti_air   = 2
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 10 current_size = 10 }
  oilpool    = 100
  supplypool = 200
}              # Diego Garcia Island

##############################
# Country definition for IRE #
##############################

province =
{ id         = 30
  anti_air   = 2
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 4 current_size = 4 }
}              # Dublin

##############################
# Country definition for FRA #
##############################

province =
{ id         = 32
  ic         = 1
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Brest
province = { id = 35 anti_air = 2 } # Nantes
province =
{ id         = 38
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
}              # Cherbourg
province = { id = 39 anti_air = 1 } # Caen
province =
{ id         = 43
  naval_base = { size = 3 current_size = 3 }
}              # Dunkerque
province =
{ id       = 44
  air_base = { size = 10 current_size = 10 }
  anti_air = 1
}            # Lille
province =
{ id       = 56
  ic       = 1
  anti_air = 5
  air_base = { size = 10 current_size = 10 }
}            # Paris
province =
{ id       = 59
  air_base = { size = 10 current_size = 10 }
}            # Cholet
province =
{ id       = 62
  air_base = { size = 10 current_size = 10 }
}            # Auxerre
province =
{ id       = 72
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
}            # Metz
province = { id = 73 anti_air = 2 } # Strasbourg
province = { id = 316 anti_air = 2 } # Mulhouse
province = { id = 317 anti_air = 1 } # Chaumont
province = { id = 320 ic = 1 anti_air = 1 } # Vichy
province =
{ id         = 325
  anti_air   = 4
  air_base   = { size = 4 current_size = 4 }
}              # Bordeaux
province =
{ id       = 359
  air_base = { size = 10 current_size = 10 }
}            # Toulouse
province =
{ id         = 364
  ic         = 1
  anti_air   = 5
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Marseille
province = { id = 528 ic = 1 } # Lyon
province = { id = 875 supplypool = 1 } # Cayenne
province =
{ id         = 939
  anti_air   = 4
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 5 current_size = 5 }
}              # Tunis
province =
{ id         = 949
  supplypool = 500
  oilpool    = 1
  anti_air   = 4
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 5 current_size = 5 }
}              # Algiers
province =
{ id         = 953
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
}              # Oran
province =
{ id         = 958
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}              # Casablanca
province =
{ id         = 981
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
}              # Dakar
province =
{ id       = 993
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Abidjan
province = { id = 1037 supplypool = 1 } # Djibouti
province =
{ id         = 1328
  anti_air   = 4
  air_base   = { size = 4 current_size = 4 }
}              # Hanoi
province =
{ id         = 1337
  supplypool = 100
  oilpool    = 1
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}              # Saigon
province =
{ id         = 1794
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
}              # Beirut

##############################
# Country definition for SPR #
##############################

province =
{ id         = 1157
  naval_base = { size = 5 current_size = 7 }
}              
province =
{ id         = 334
  anti_air   = 2
  naval_base = { size = 7 current_size = 7 }
  air_base   = { size = 4 current_size = 4 }
}              # La Coruña
province =
{ id       = 341
  anti_air = 3
  air_base = { size = 2 current_size = 2 }
}            # Madrid
province =
{ id         = 347
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
}              # Seville
province =
{ id         = 354
  anti_air   = 2
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 2 current_size = 2 }
}              # València
province =
{ id         = 356
  anti_air   = 2
  naval_base = { size = 7 current_size = 7 }
  air_base   = { size = 4 current_size = 4 }
}              # Tarragona
province =
{ id         = 535
  anti_air   = 2
  naval_base = { size = 7 current_size = 7 }
  air_base   = { size = 4 current_size = 4 }
}              # Mallorca
province =
{ id         = 963
  naval_base = { size = 1 current_size = 1 }
  air_base   = { size = 2 current_size = 2 }
}              # Gran Canaria
province =
{ id         = 972
  anti_air   = 2
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 2 current_size = 2 }
}              # Villa Cisneros

##############################
# Country definition for POR #
##############################

province = { id = 335 anti_air = 1 } # Oporto
province =
{ id         = 336
  anti_air   = 4
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
}              # Lissabon
province =
{ id         = 983
  anti_air   = 2
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 1 current_size = 1 }
}              # Bissão
province =
{ id         = 1090
  anti_air   = 2
  naval_base = { size = 1 current_size = 1 }
  air_base   = { size = 1 current_size = 1 }
}              # São Tomé
province =
{ id         = 1094
  naval_base = { size = 1 current_size = 1 }
  air_base   = { size = 1 current_size = 1 }
}              # Cabinda
province =
{ id         = 1101
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 1 current_size = 1 }
}              # Benguella
province =
{ id         = 1123
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 1 current_size = 1 }
}              # Inhambane
province =
{ id         = 1146
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 1 current_size = 1 }
}              # Cap Verde Islands
province =
{ id         = 1316
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 1 current_size = 1 }
}              # Macao
province =
{ id         = 1658
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 1 current_size = 1 }
}              # East Timor
province =
{ id         = 1867
  anti_air   = 2
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 4 current_size = 4 }
}              # The Azores

##############################
# Country definition for ITA #
##############################

province =
{ id         = 368
  anti_air   = 3
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
}              # Genoa
province =
{ id         = 369
  anti_air   = 3
  naval_base = { size = 10 current_size = 10 }
}              # La Spezia
province =
{ id       = 370
  air_base = { size = 4 current_size = 4 }
  anti_air = 3
}            # Milan
province =
{ id         = 378
  anti_air   = 2
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
}              # Venice
province =
{ id       = 399
  air_base = { size = 4 current_size = 4 }
}            # Rhodes
province = { id = 512 anti_air = 1 } # Bologna
province = { id = 513 anti_air = 1 } # Florence
province =
{ id       = 515
  anti_air = 1
  air_base = { size = 10 current_size = 10 }
}            # Rome
province =
{ id       = 521
  air_base = { size = 4 current_size = 4 }
}            # Naples
province =
{ id         = 523
  anti_air   = 1
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
}              # Taranto
province =
{ id         = 525
  anti_air   = 2
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
}              # Palermo
province = { id = 531 anti_air = 3 } # Turin
province =
{ id         = 534
  anti_air   = 1
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 4 current_size = 4 }
  oilpool    = 100
  supplypool = 500
}              # Sardinia
province =
{ id         = 919
  anti_air   = 2
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 2 current_size = 2 }
}              # Tobruk
province =
{ id         = 924
  anti_air   = 1
  naval_base = { size = 5 current_size = 5 }
  air_base   = { size = 4 current_size = 4 }
}              # Bengazi
province =
{ id         = 932
  anti_air   = 1
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
  oilpool    = 100
  supplypool = 500
}              # Tripoli
province =
{ id         = 1033
  anti_air   = 1
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 4 current_size = 4 }
  oilpool    = 100
  supplypool = 500
}              # Massaua
province = { id = 1056 oilpool = 100 supplypool = 500 } # Mogadishu

##############################
# Country definition for LIB #
##############################

province =
{ id         = 992
  anti_air   = 1
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 4 current_size = 4 }
}              # Monrovia

##############################
# Country definition for ETH #
##############################

province =
{ id         = 1046
  air_base   = { size = 4 current_size = 4 }
} 

##############################
# Country definition for OMN #
##############################

province =
{ id         = 1819
  anti_air   = 2
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 1 current_size = 1 }
}              # Mascate

##############################
# Country definition for SAU #
##############################

province =
{ id         = 2862
  anti_air   = 2
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 1 current_size = 1 }
}              

##############################
# Country definition for IRQ #
##############################

province =
{ id         = 1823
  anti_air   = 2
  naval_base = { size = 4 current_size = 4 }
}              # Basrah
province = { id = 1864 anti_air = 1 } # Mosul
province =
{ id       = 1866
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Baghdad

##############################
# Country definition for PER #
##############################

province =
{ id         = 1497
  anti_air   = 2
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 1 current_size = 1 }
}              # Bandar Abbas

##############################
# Country definition for SIA #
##############################

province =
{ id         = 1343
  anti_air   = 2
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 4 current_size = 4 }
}    

##############################
# Country definition for PHI #
##############################

province =
{ id         = 1737
  anti_air   = 2
  naval_base = { size = 8 current_size = 8 }
  air_base   = { size = 1 current_size = 1 }
}              # Manila
province =
{ id         = 1739
  anti_air   = 4
  air_base   = { size = 5 current_size = 5 }
  Naval_base = { size = 2 current_size = 2 }
}              # Clark Field

##############################
# Country definition for MON #
##############################

province =
{ id       = 1404
  air_base = { size = 1 current_size = 1 }
}            # Ulan Bator

##############################
# Country definition for CHC #
##############################

##############################
# Country definition for CHI #
##############################


province =
{ id         = 1237
  naval_base = { size = 10 current_size = 10 }
}              # Shanghai
province =
{ id       = 1238
  air_base = { size = 10 current_size = 10 }
}            # Hangzhou
province =
{ id       = 1244
  air_base = { size = 1 current_size = 1 }
}            # Fuzhou
province =
{ id       = 1251
  air_base = { size = 10 current_size = 10 }
}            # Nanchang
province =
{ id       = 1360
  air_base = { size = 3 current_size = 3 }
}            # Chengdu

##############################
# Country definition for CSX #
##############################

province =
{ id       = 1225
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Jinan

##############################
# Country definition for CGX #
##############################

province = { id = 1248 supplypool = 500 oilpool = 50 } # Shantou
province =
{ id         = 1313
  air_base   = { size = 3 current_size = 3 }
  naval_base = { size = 5 current_size = 5 }
}              # Guangzhou
province =
{ id         = 1320
  naval_base = { size = 5 current_size = 5 }
}              # Zhanjiang
province =
{ id         = 1321
  anti_air   = 2
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 10 current_size = 10 }
}              # Hainan

##############################
# Country definition for JAP #
##############################

province =
{ id         = 1181
  anti_air   = 2
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Akita
province = { id = 1182 anti_air = 2 } # Fukushima
province =
{ id         = 1184
  ic         = 7
  anti_air   = 2
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Tokyo
province =
{ id         = 1185
  ic         = 3
  anti_air   = 2
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Nagoya
province =
{ id         = 1186
  anti_air   = 2
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Kanazawa
province =
{ id         = 1187
  ic         = 2
  anti_air   = 2
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Osaka
province =
{ id         = 1188
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Hiroshima
province =
{ id         = 1189
  ic         = 3
  anti_air   = 2
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Shikoku
province =
{ id         = 1190
  anti_air   = 2
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Fukuoka
province =
{ id         = 1193
  anti_air   = 2
  air_base   = { size = 6 current_size = 6 }
  naval_base = { size = 6 current_size = 6 }
  supplypool = 1000
}              # Okinawa
province =
{ id         = 1197
  anti_air   = 2
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  supplypool = 5000
  oilpool    = 100
}              # Busan
province =
{ id         = 3090
  anti_air   = 4
  naval_base = { size = 5 current_size = 5 }
  air_base   = { size = 7 current_size = 7 }
  supplypool = 500
  oilpool    = 100
}              
province = { id = 1184 supplypool = 1000 oilpool = 100 } # Tangshan
province =
{ id         = 1322
  anti_air   = 2
  air_base   = { size = 8 current_size = 8 }
  naval_base = { size = 10 current_size = 10 }
  supplypool = 1000
  oilpool    = 100
}              # Kaohsiung
province = { id = 1323 anti_air = 2 } # Taipei
province =
{ id       = 1391
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Hyesan
province = { id = 1599 supplypool = 500 } # Iwo Jima
province =
{ id         = 1601
  anti_air   = 5
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
  supplypool = 500
}              # Eniwetok
province = { id = 1199 anti_air = 3 } # Majuro
province =
{ id         = 1608
  anti_air   = 5
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
  supplypool = 2000
}              # Kwajalein
province = { id = 1199 supplypool = 500 } # Ponape
province =
{ id         = 1199
  anti_air   = 5
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
  supplypool = 500
}              # Truk
province = { id = 1618 supplypool = 500 } # Ulithi
province = { id = 1619 anti_air = 3 supplypool = 500 } # Yap
province = { id = 1621 supplypool = 500 } # Palau
province = { id = 1625 supplypool = 500 } # Rota
province = { id = 1626 supplypool = 500 } # Tinian
province = { id = 1627 anti_air = 3 supplypool = 500 } # Saipan
province = { id = 1784 anti_air = 2 } # Bonin Islands
province = { id = 1785 supplypool = 500 } # Marcus Island

##############################
# Country definition for AST #
##############################

province =
{ id         = 1670
  naval_base = { size = 7 current_size = 7 }
  air_base   = { size = 2 current_size = 2 }
  anti_air   = 2
}              # Rabaul
province =
{ id       = 1672
  air_base = { size = 1 current_size = 1 }
  anti_air = 1
}            # Lae
province =
{ id         = 1677
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 2 current_size = 2 }
  anti_air   = 1
  oilpool    = 1
  supplypool = 50
}              # Port Moresby
province =
{ id         = 1703
  anti_air   = 5
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
  ic         = 1
}              # Darwin
province =
{ id          = 1712
  anti_air    = 5
  naval_base  = { size = 10 current_size = 10 }
  air_base    = { size = 10 current_size = 10 }
  landfort    = 0
  coastalfort = 1
}               # Perth
province = { id = 1718 anti_air = 1 } # Port Augusta
province =
{ id          = 1722
  anti_air    = 4
  naval_base  = { size = 10 current_size = 10 }
  air_base    = { size = 10 current_size = 10 }
  landfort    = 0
  coastalfort = 1
  ic          = 3
}               # Brisbane
province = { id = 1724 ic = 1 } # Newcastle
province = { id = 1724 anti_air = 3 } # Wentworth
province =
{ id          = 1723
  anti_air    = 4
  naval_base  = { size = 10 current_size = 10 }
  air_base    = { size = 10 current_size = 10 }
  landfort    = 0
  coastalfort = 2
  ic          = 2
}               # Sydney

province = { id = 1730 landfort = 0 coastalfort = 1 anti_air = 3 ic = 2 } # Melbourne
province = { id = 1733 anti_air = 2 ic = 2 } # Adelaide

##############################
# Country definition for NZL #
##############################

province =
{ id         = 1871
  anti_air   = 2
  naval_base = { size = 5 current_size = 5 }
  air_base   = { size = 3 current_size = 3 }
}              # Wellington

##############################
# Country definition for CAN #
##############################

province =
{ id         = 541
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # Vancouver
province =
{ id       = 569
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Winnipeg
province =
{ id         = 579
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # Halifax

province =
{ id       = 585
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # Montréal

province =
{ id       = 588
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
}            # Ottawa
province = { id = 589 anti_air = 1 } # Toronto
province =
{ id       = 797
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Calgary

##############################
# Country definition for USA #
##############################

province =
{ id         = 894
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 10 current_size = 4 }
}              # Guantanamo

province =
{ id         = 549
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 4 current_size = 4 }
}              # Anchorage
province = { id = 553 supplypool = 1000 } # Juneau
Province =
{ id       = 592
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Plattsburgh
province =
{ id       = 595
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Concord
province =
{ id         = 600
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # Boston
province =
{ id         = 602
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # New York
province =
{ id         = 606
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # Washington D.C.
province = { id = 608 anti_air = 2 } # Philadelphia
province =
{ id       = 614
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Pittsburgh
province =
{ id       = 616
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Detroit
province =
{ id       = 620
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
}            # Chicago
province =
{ id       = 621
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Milwaukee
province =
{ id         = 632
  anti_air   = 4
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # Norfolk
Province =
{ id       = 637
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Charlotte
province =
{ id       = 640
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Louisville
province =
{ id       = 644
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Charleston
Province =
{ id       = 648
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Jacksonville
province =
{ id         = 651
  anti_air   = 1
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # Miami
province = { id = 662 supplypool = 100 } # Midway Island
province =
{ id         = 663
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
  supplypool = 1000
}              # Pearl Harbour
province =
{ id       = 670
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Atlanta
Province =
{ id       = 673
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Memphis
Province =
{ id       = 678
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Biloxi
province =
{ id       = 684
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Little Rock
province =
{ id       = 689
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # St. Louis
province =
{ id       = 693
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Minneapolis
province =
{ id       = 698
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Bismarck
province =
{ id       = 707
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Denver
Province =
{ id       = 713
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Oklahoma City
province =
{ id       = 716
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Houston
Province =
{ id       = 725
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Santa Fe
province =
{ id       = 730
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Phoenix
province =
{ id       = 733
  anti_air = 1
  air_base = { size = 10 current_size = 10 }
}            # Salt Lake City
Province =
{ id         = 748
  anti_air   = 1
  air_base   = { size = 6 current_size = 6 }
  Naval_base = { size = 8 current_size = 8 }
}              # Corpus Christi
province =
{ id         = 761
  anti_air   = 1
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # San Diego
province =
{ id         = 762
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 8 current_size = 8 }
}              # Los Angeles
province =
{ id       = 764
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Sacramento
province =
{ id         = 765
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # San Francisco
province =
{ id         = 780
  anti_air   = 1
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # Seattle
province =
{ id       = 783
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Portland
province =
{ id       = 789
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Omaha
province =
{ id       = 793
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Tulsa
province =
{ id         = 889
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 4 current_size = 4 }
  supplypool = 100
}              # Colon
province = { id = 895 supplypool = 50 } # Puerto Rico
province =
{ id         = 1624
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 4 current_size = 4 }
  supplypool = 100
}              # Guam
province = { id = 1765 supplypool = 50 } # Palmyra
province = { id = 1766 supplypool = 1 } # Johnson Island
province =
{ id         = 1786
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 4 current_size = 4 }
  supplypool = 100
}              # Wake Island

##############################
# Country definition for MEX #
##############################

province = { id = 747 anti_air = 1 } # Monterrey
province = { id = 751 anti_air = 1 } # Guadalajara
province = { id = 752 anti_air = 2 } # Mexico City
province =
{ id         = 751
  anti_air   = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 }
}              # Acapulco

##############################
# Country definition for GUA #
##############################

province =
{ id         = 2649
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}              # Guatemala

##############################
# Country definition for SAL #
##############################

province =
{ id         = 759
  naval_base = { size = 1 current_size = 1 }
  air_base   = { size = 1 current_size = 1 }
}              # San Salvador

##############################
# Country definition for HON #
##############################

province =
{ id         = 4299
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}              # Tegucigalpa

##############################
# Country definition for NIC #
##############################

province =
{ id         = 539
  naval_base = { size = 1 current_size = 1 }
  air_base   = { size = 1 current_size = 1 }
}              # Managua

##############################
# Country definition for COS #
##############################

province =
{ id         = 540
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # San José

##############################
# Country definition for PAN #
##############################

province =
{ id         = 888
  anti_air   = 2
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 1 current_size = 1 }
}              # Panamá

##############################
# Country definition for CUB #
##############################

province =
{ id         = 654
  anti_air   = 1
  naval_base = { size = 4 current_size = 4 }
}              # Havana

##############################
# Country definition for HAI #
##############################

province =
{ id         = 892
  anti_air   = 1
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 2 current_size = 2 }
}              # Port-au-Prince

##############################
# Country definition for DOM #
##############################

province =
{ id         = 893
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 1 current_size = 1 }
}              # Santo Domingo

##############################
# Country definition for COL #
##############################

province =
{ id         = 890
  anti_air   = 2
  air_base   = { size = 1 current_size = 1 }
  naval_base = { size = 2 current_size = 2 }
}              # Barranquilla
province = { id = 812 anti_air = 2 } # Bogotá

##############################
# Country definition for VEN #
##############################

province =
{ id         = 804
  anti_air   = 2
  air_base   = { size = 1 current_size = 1 }
  naval_base = { size = 6 current_size = 6 }
}              # Maracaibo
province = { id = 870 anti_air = 2 } # Caracas

##############################
# Country definition for ECU #
##############################

province =
{ id         = 814
  naval_base = { size = 3 current_size = 3 }
}     
 province =
{ id         = 815
  anti_air   = 2
  air_base   = { size = 1 current_size = 1 }
}      

##############################
# Country definition for PRU #
##############################

province =
{ id         = 830
  anti_air   = 2
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 1 current_size = 1 }
}              # Lima

##############################
# Country definition for BOL #
##############################

province =
{ id       = 832
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # La Paz

##############################
# Country definition for CHL #
##############################

province =
{ id         = 856
  anti_air   = 2
  naval_base = { size = 8 current_size = 8 }
  air_base   = { size = 4 current_size = 4 }
}             

##############################
# Country definition for ARG #
##############################

             
province =
{ id         = 851
  anti_air   = 5
  naval_base = { size = 8 current_size = 5 }
  air_base   = { size = 3 current_size = 3 }
}  #Buenos Aires
			 
province =
{ id         = 667
  anti_air   = 2
  naval_base = { size = 8 current_size = 8 }
  air_base   = { size = 3 current_size = 3 }
}              # Bahia Blanca

##############################
# Country definition for URU #
##############################

province =
{ id         = 849
  anti_air   = 1
  air_base   = { size = 1 current_size = 1 }
  naval_base = { size = 6 current_size = 6 }
}              # Montevideo

##############################
# Country definition for PAR #
##############################

province =
{ id       = 846
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # Asunción

##############################
# Country definition for BRA #
##############################

province = { id = 847 anti_air = 1 } # Curitiba
province =
{ id         = 4053
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 8 current_size = 8 }
}              # Rio Grande
province = { id = 883 anti_air = 2 } # Goiás
province =
{ id         = 885
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
}              # Rio de Janeiro
province =
{ id         = 6491
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
}              # Santos

##############################
# Country definition for SAF #
##############################

province =
{ id         = 1108
  anti_air   = 2
  air_base   = { size = 1 current_size = 1 }
}              # Walvis Bay
province =
{ id         = 1116
  anti_air   = 4
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
}              # Cape Town
province = { id = 1117 anti_air = 1 } # Port Elisabeth
province =
{ id         = 1119
  anti_air   = 3
  air_base   = { size = 1 current_size = 1 }
}              # Durban
province = { id = 1120 anti_air = 3 } # Johannesburg

############################## 
# Country definition for U06 Free City of Danzig # 
############################## 

 province = 
 {  id         = 303 
   anti_air   = 2 
   naval_base = {  size =  8 current_size =  8  } 
   air_base   = {  size =  4 current_size =  4  } 
  }              # Danzig 

##############################
# Country definition for MAN #
##############################

province =
{ id       = 1379
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}            # Harbin

 province = 
 {  id         = 2305 
   naval_base = {  size =  5 current_size =  5  }  
  } 

 province = 
 {  id         = 1036 
   naval_base = {  size =  5 current_size =  5  }  
  }








