#####################
# Country main data #
#####################

country =
{ tag                    = CHI
  capital                = 1323 # Taipei
  # Resource Reserves
  energy                 = 10000
  metal                  = 10000
  rare_materials         = 10000
  oil                    = 5000
  supplies               = 5000
  money                  = 8000
  manpower               = 500
  dissent                = 0
  transports             = 10
  escorts                = 2
  diplomacy =
  { relation = { tag = CHC value = -200 }
    relation = { tag = CGX value = 200 }
    relation = { tag = CSX value = 200 access = yes }
    relation = { tag = CXB value = 200 access = yes }
    relation = { tag = CYN value = 200 }
    relation = { tag = JAP value = -100 }
    relation = { tag = MAN value = -100 }
  }
  SpyInfo                = { country = "ENG" NumberOfSpies = 1 }
  SpyInfo                = { country = "FRA" NumberOfSpies = 1 }
  SpyInfo                = { country = "SOV" NumberOfSpies = 3 }
  SpyInfo                = { country = "GER" NumberOfSpies = 1 }
  SpyInfo                = { country = "CBX" NumberOfSpies = 2 }
  SpyInfo                = { country = "CHC" NumberOfSpies = 5 }
  SpyInfo                = { country = "JAP" NumberOfSpies = 3 }
  SpyInfo                = { country = "CYN" NumberOfSpies = 2 }
  SpyInfo                = { country = "CSX" NumberOfSpies = 2 }
  SpyInfo                = { country = "CXB" NumberOfSpies = 1 }
  # Fujian		
  nationalprovinces      = { 1275 1276 1277 1440 1441 1267 1268 1269 1270 1271 1222 1223 1224 1227 1228 1229 1230 1273 1274 1439 1207 1208 1272
                             1209 1225 1226 1203 1204 1205 1206 1210 1211 1212 1213 1216 1386 1398 1388 1397 1202 1377 1387 1389 1390 1394
                             1395 1396 1374 1375 1378 1379 1380 1381 1382 1530 1218 1221 1233 1234 1217 1219 1220 1235 1236 1237 1263 1265 1279 1280
                             1360 1361 1231 1232 1253 1264 1266 1238 1239 1240 1241 1262 1363 1364 1365 1255 1256 1257 1259 1260 1261 1242 1250 1251
                             1252 1254 1243 1244 1245 1246 1247 1293 1294 1307 1308 1327 1362 1281 1282 1283 1448 1450 1451 1452 1453 1442 1443
                             1444 1421 1430 1431 1432 1433 1435 1445 1446 1447 1258 1309 1310 1311 1319 1325 1248 1249 1312 1313 1314 1317 1318 1320
                             1321 1322 1323 1324 1385 1404 1419 1420 1434 1438
							 1903 2559 1984 1993 2560
							 2551 2000 2311 1913 2561
							 2550 2505 1996 2502 1997
							 1995 1910 1922 1921 1914
							 2507 2516 2515 2513 2508
							 1966 2556 2558 1965 1964
							 1939 2571 1936 1937 2572
							 2570 2568 2573 2574 2567
							 2569 1941 1938
							 1728 1406 1878 1877
							 1905 1918 1978 1928 1983
							 695 674 559 557 720 
							 568 570 1880 1912 746
							 1923 696 1316 1315 2503 2504
							 2517 2518 2520 2525 2527
							 2526 2576 2523 2528 2534
							 2522 2533 2531 1215 2530 2529 1214
							 2318 2317 2347 2348 2349 
							 2346 2345 2340 2341 2344
							 2338 2333 2487 2241 2511 2337 2246
							 2486 2281 2485 3133 2941 2942 3090 3110
							 3750 3751 3752 3753 3754 3775
							 3737 3738 3739 3740 3741 3742 3743 3744 3745 3746 3747 3748 3749
3755 3756 3757 3758 3759 3760 3774
3762 3763 3764 3765 3766 3767 3768 3769 3770 3771 3772 3773
3761 1418 3594 3595 5184 5205 
5472 5473 5474 5475 5476 5477 5478 5479 5480 5481 
5482 5483 5484 5485 5486 5487 5488 5489 5490 5491 
5492 5493 5494 5495 5496 5497 5498 5499 5500 5501 
5502 5503 5504 5505 5506 5507 5508 5509 5510 5511 
5512 5513 5514 5515 5516 5517 5518 5519 5520 5521 
5522 5523 5524 5525 5526 5527 5528 5529 5530 5531 
5532 5533 5534 5535 5536 5537 5538 5539 5540 5541 
5542 5543 5544 5545 5546 5547 5548 5549 5550 5551 
5552 5553 5554 5555 5556 5557 5558 5559 5560 5561 
5562 5563 5564 5565 5566 5567 5568 5569 5570 5571 
5572 5573 5574 5575 5576 5577 5578 5579 5580 5581 
5582 5583 5584 5585 5586 5587 5588 5589 5590 5591 
5592 5593 5594 5595 5596 5597 5598 5599 5600 5601 
5602 5603 5604 5605 5606 5607 5608 5609 5610 5611 
5612 5613 5614 5615 5616 5617 5618 5619 5620 5621 
5622 5623 5624 5625 5626 5627 5628 5629 5630 5631 
5632 5633 5634 5635 5636 5637 5638 5639 5640 5641 
5642 5643 5644 5645 5646 5647 5648 5649 5650 5651 
5652 5655 5656 5657 5658 5659 5660 5661 
5662 5663 5664 5665 5666 5667 5668 5669 5670 5671 
5672 5673 5674 5675 5676 5677 5678 5679 5680 5681 
5682 5683 5684 5685 5686 5687 5688 5689 5690 5691 
5692 5693 6497 6498 6916
7911 7918 7917 6920 5185
                           }
  ownedprovinces         = { 1323 1324 1923 3133 1322 5649 5651 5652 }
  controlledprovinces    = { 1323 1324 1923 3133 1322 5649 5651 5652 }
  
  claimedprovinces 		 = { 1487 3485 5872 5836 5873 5891 5892 5893 6953 }
  techapps = {
   ###################
   #     Infantry    #
   ###################
   #Infantry
   1010 1020 1030
   #Motorized
   1100 1110 1120
   #Mountain
   1160 1170 1180
   #Special Forces
   1250 1260 1270
   #Naval Infantry
   1560 1570 1580
   #Airborne Infantry
   1670 1680 1690
   #Air Cavalry
   1396 1400
   #Armored Cavalry
   13060 13070
   #Mechanized
   1470 1480 1490
   #Irregular Infantry
   1360 1370 1380
   #Combat Engineers
   1830 1840 1850
   #Supply and Repair
   1990 199100 199110 199130 
   ###################
   #Armor & Artillery#
   ###################
   #Main Battle Tanks
   2620 2010 2630 2640 2646
   #Infantry Fighting Vehicles	
   2100
   #Armored Cars
   2860 2870 2950 
   #Anti-Air
   2800 2450 21180
   #Armored Personnel Carriers
   2170 2180 2850 2400 
   #Field Artillery
   2290 2300 2310
   #Self-Propelled Anti-Air
   2810 2820 2510
   #Man-Portable Air-Defense Systems
   3000 3170
   #Self-Propelled Artillery
   2220 2230
   #Self-Propelled Rocket Artillery
   2980 2260 2270
   ###################
   #     Naval       #
   ###################
   #Frigates
   3110 3120 3130
   #Cruisers
   3410 3420 3430 3440
   #Destroyers
   3310 3320 3330 3340
   #Light Aircraft Carriers
   12100
   #Submarines
   3010 3020 3030
   #Transport Ships
   3900 3910 3920
   ###################
   #    Aircraft     #
   ###################
   #Attack Helicopter
   4900
   #Reconnaissance Aircraft
   4770
   #Strategic Bomber
   4800
   #Strike Bomber
   15040
   #Naval Patrol
   4610
   #ASW Bomber
   4230
   #Attack Aircraft
   4030 4060 4090
   #Multi-Role
   4500 4570 4530 4540
   #Air Superiority Fighter
   4510 4520
   #Air Transports
   4250 4260
   #AEW&C
   4450 #4180
   #Air-to-Ground Missiles
   4040
   #Air-to-Air Missiles
   4600
   #Air-to-Sea Missiles
   4740
   ###################
   #    Industry     #
   ###################
   #Light Industry
   5810 5820
   #Heavy Industry
   5130 5110
   #Material Science
   53050 63160 63070
   #Construction Eng.
   5800 5080
   #Rocketry

   #Agriculture
   5700 5710 5010
   #Oil
   5190 5220
   #Computing
   5310 54010 54020
   #Nuclear
   5470 5480 5490
   #Research
   5316
   #Cryptography
   5350 5360
   #Medicine
   5600 5610
   5630
   5660 5730
   #Renewable Energy
   5720
   ###################
   #  Land Doctrines #
   ###################
   6500 
   6510 6530 
   1650
   6560 #Defensive
   ###################
   # Naval Doctrines #
   ###################
   #Surface Ship Role
   81050 81060 81070 81080 81090 81100 81110 81120
   #Naval Interdiction
   8500 8510 8520 8550 8560 8570 8600 8610 8620
   #Naval Supremacy
   8100 8110 8150 8120 8160 8170 8200 8210 8220
   #Logistics Support
   82500 82510 82520 82530
   #Naval Capability
   8010
   #Amphibious Warfare
   82300
   ###################
   #  Air Doctrines  #
   ###################
   9390 9260 9400 9410
   9090 9100 9110 9120 9050 9060 9070
   9190 9200 9210 9220 9310 9320 9330 9340 9230 9240 9250
   9130 9420 9300
   }
  inventions = {  }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 3
    political_left    = 4
    free_market       = 9
    freedom           = 4
    professional_army = 3
    defense_lobby     = 8
    interventionism   = 4
  }
  headofstate            = { type = 9 id = 52001 }
  headofgovernment       = { type = 9 id = 52002 }
  foreignminister        = { type = 9 id = 52003 }
  armamentminister       = { type = 9 id = 52004 }
  ministerofsecurity     = { type = 9 id = 52005 }
  ministerofintelligence = { type = 9 id = 52006 }
  chiefofstaff           = { type = 9 id = 52007 }
  chiefofarmy            = { type = 9 id = 52008 }
  chiefofnavy            = { type = 9 id = 52009 }
  chiefofair             = { type = 9 id = 52010 }
  dormant_leaders        = { 50370 50377 }
  # ####################################
  # ARMY
  # ####################################
	landunit = {
		id = { type = 21000 id = 1 }
		location = 1323
		name = "Aviation and Special Forces Command"
		division = {
			experience = 10
			id = { type = 21000 id = 2 }
			name = "Special Forces Brigade"
			strength = 100
			type = d_03
			model = 5
			extra = engineer
			brigade_model = 5
		}
		division = {
			id = { type = 21000 id = 3 }
			name = "601st Air Cavalry Brigade"
			strength = 100
			type = d_04
			model = 4
		}
		division = {
			id = { type = 21000 id = 4 }
			name = "603rd Air Cavalry Brigade"
			strength = 100
			type = d_04
			model = 4
		}
	}
	landunit = {
		id = { type = 21000 id = 6 }
		location = 1323
		name = "Marine Corps Command"
		division = {
			id = { type = 21000 id = 7 }
			name = "66th Marine Brigade"
			strength = 100
			type = d_05
			model = 5
		}
		division = {
			id = { type = 21000 id = 8 }
			name = "77th Marine Brigade"
			strength = 100
			type = d_05
			model = 5
		}
		division = {
			id = { type = 21000 id = 9 }
			name = "99th Marine Brigade"
			strength = 100
			type = d_05
			model = 5
		}
	}
	landunit = {
		id = { type = 21000 id = 10 }
		location = 1323
		name = "6th Army Corps"
		division = {
			id = { type = 21000 id = 13 }
			name = "542nd Armor Brigade"
			strength = 100
			type = light_armor
			model = 3
		}
		division = {
			id = { type = 21000 id = 14 }
			name = "584th Armor Brigade"
			strength = 100
			type = light_armor
			model = 3
		}
                division = {
			id = { type = 21000 id = 12 }
			name = "269th Mechanized Brigade"
			strength = 100
			type = d_06
			model = 5
		}
		division = {
			id = { type = 21000 id = 15 }
			name = "3rd Infantry Brigade"
			strength = 100
			type = d_01
			model = 5
		}
	}
	landunit = {
		id = { type = 21000 id = 24 }
		location = 1323
		name = "Hua-Tung Defense Command"
		division = {
			id = { type = 21000 id = 25 }
			name = "1st Infantry Brigade"
			strength = 100
			type = d_01
			model = 5
			#locked = yes
		}
		division = {
			id = { type = 21000 id = 26 }
			name = "2nd Infantry Brigade"
			strength = 100
			type = d_01
			model = 5
			#locked = yes
		}
	}
	landunit = {
		id = { type = 21000 id = 27 }
		location = 1323
		name = "Kinmen Defense Command"
		division = {
			id = { type = 21000 id = 28 }
			name = "3rd Infantry Brigade"
			strength = 100
			type = d_01
			model = 5
			#locked = yes
		}
		division = {
			id = { type = 21000 id = 29 }
			name = "4th Infantry Brigade"
			strength = 100
			type = d_01
			model = 5
			#locked = yes
		}
		division = {
			id = { type = 21000 id = 30 }
			name = "5th Infantry Brigade"
			strength = 100
			type = d_01
			model = 5
			#locked = yes
		}
		division = {
			id = { type = 21000 id = 31 }
			name = "5th Armored Brigade"
			strength = 100
			type = light_armor
			model = 3
			#locked = yes
		}
	}
	landunit = {
		id = { type = 21000 id = 32 }
		location = 1323
		name = "Matzu Defense Command"
		division = {
			id = { type = 21000 id = 33 }
			name = "6th Infantry Brigade"
			strength = 100
			type = d_01
			model = 5
			#locked = yes
		}
		division = {
			id = { type = 21000 id = 34 }
			name = "7th Infantry Brigade"
			strength = 100
			type = d_01
			model = 5
			#locked = yes
		}
	}
	# ####################################
	# NAVY
	# ####################################
	navalunit = {
		id = { type = 21000 id = 200 }
		location = 1323
		base = 1323
		name = "124th Attack Squadron"
		division = {
			id = { type = 21000 id = 201 }
			name = "Kang Ding"
			type = destroyer
			model = 0
		}
		division = {
			id = { type = 21000 id = 203 }
			name = "Si Ning"
			type = destroyer
			model = 0
		}
		division = {
			id = { type = 21000 id = 204 }
			name = "Wu Chang"
			type = destroyer
			model = 0
		}
		division = {
			id = { type = 21000 id = 205 }
			name = "Di Hua"
			type = destroyer
			model = 0
		}
		division = {
			id = { type = 21000 id = 206 }
			name = "Kun Ming"
			type = destroyer
			model = 0
		}
		division = {
			id = { type = 21000 id = 207 }
			name = "Cheng Du"
			type = destroyer
			model = 0
		}
	}
	navalunit = {
		id = { type = 21000 id = 208 }
		location = 1323
		base = 1323
		name = "146th Attack Squadron"
		division = {
			id = { type = 21000 id = 209 }
			name = "Cheng Kung"
			type = destroyer
			model = 0
		}
		division = {
			id = { type = 21000 id = 210 }
			name = "Cheng Ho"
			type = destroyer
			model = 0
		}
		division = {
			id = { type = 21000 id = 211 }
			name = "Chi Kuang"
			type = destroyer
			model = 0
		}
		division = {
			id = { type = 21000 id = 212 }
			name = "Yueh Fei"
			type = destroyer
			model = 0
		}
		division = {
			id = { type = 21000 id = 213 }
			name = "Tzu I"
			type = destroyer
			model = 0
		}
		division = {
			id = { type = 21000 id = 214 }
			name = "Pan Chao"
			type = destroyer
			model = 0
		}
		division = {
			id = { type = 21000 id = 215 }
			name = "Chang Chien"
			type = destroyer
			model = 0
		}
		division = {
			id = { type = 21000 id = 216 }
			name = "Tian Dan"
			type = destroyer
			model = 0
		}
	}
	navalunit = {
		id = { type = 21000 id = 217 }
		location = 1323
		base = 1323
		name = "131st Patrol Squadron"
		division = {
			id = { type = 21000 id = 218 }
			name = "Chien Yang"
			type = light_cruiser
			model = 4
		}
		division = {
			id = { type = 21000 id = 219 }
			name = "Liao Yang"
			type = light_cruiser
			model = 4
		}
		division = {
			id = { type = 21000 id = 220 }
			name = "Shao Yang"
			type = light_cruiser
			model = 4
		}
		division = {
			id = { type = 21000 id = 221 }
			name = "Te Yang"
			type = light_cruiser
			model = 4
		}
	}
	navalunit = {
		id = { type = 21000 id = 234 }
		location = 1323
		base = 1323
		name = "168th Patrol Squadron"
		division = {
			id = { type = 21000 id = 235 }
			name = "Chen Yang"
			type = light_cruiser
			model = 4
		}
		division = {
			id = { type = 21000 id = 236 }
			name = "Shen Yang"
			type = light_cruiser
			model = 4
		}
		division = {
			id = { type = 21000 id = 237 }
			name = "Yun Yang"
			type = light_cruiser
			model = 4
		}
		division = {
			id = { type = 21000 id = 238 }
			name = "Chi Yang"
			type = destroyer
			model = 0
		}
		division = {
			id = { type = 21000 id = 239 }
			name = "Fong Yang"
			type = destroyer
			model = 0
		}
		division = {
			id = { type = 21000 id = 240 }
			name = "Fen Yang"
			type = destroyer
			model = 0
		}
		division = {
			id = { type = 21000 id = 241 }
			name = "Lan Yang"
			type = destroyer
			model = 0
		}
		division = {
			id = { type = 21000 id = 242 }
			name = "Hae Yang"
			type = destroyer
			model = 0
		}
		division = {
			id = { type = 21000 id = 243 }
			name = "Hwai Yang"
			type = destroyer
			model = 0
		}
		division = {
			id = { type = 21000 id = 244 }
			name = "Ning Yang"
			type = destroyer
			model = 0
		}
		division = {
			id = { type = 21000 id = 245 }
			name = "Yi Yang"
			type = destroyer
			model = 0
		}
	}
	navalunit = {
		id = { type = 21000 id = 246 }
		location = 1323
		base = 1323
		name = "27th Amphibious Squadron"
		division = {
			id = { type = 21000 id = 247 }
			name = "1st Transport Fleet"
			type = transport
			model = 5
		}
		division = {
			id = { type = 21000 id = 251 }
			name = "2nd Transport Fleet"
			type = transport
			model = 5
		}
		division = {
			id = { type = 21000 id = 256 }
			name = "3rd Transport Fleet"
			type = transport
			model = 5
		}
	}
	# ####################################
	# AIR FORCE
	# ####################################
	airunit = {
		id = { type = 21000 id = 100 }
		location = 1323
		base = 1323
		name = "401th Tactical Fighter Wing"
		division = {
			id = { type = 21000 id = 101 }
			name = "367th Fighter Squadron"
			type = interceptor
			strength = 100
			model = 4
		}
		division = {
			id = { type = 21000 id = 102 }
			name = "345th Fighter Squadron"
			type = interceptor
			strength = 100
			model = 4
		}
		division = {
			id = { type = 21000 id = 103 }
			name = "382nd Fighter Squadron"
			type = interceptor
			strength = 100
			model = 4
		}
	}
	airunit = {
		id = { type = 21000 id = 104 }
		location = 1323
		base = 1323
		name = "427th Tactical Fighter Wing"
		division = {
			id = { type = 21000 id = 105 }
			name = "288th Fighter Squadron"
			type = interceptor
			strength = 100
			model = 4
		}
		division = {
			id = { type = 21000 id = 106 }
			name = "210th Fighter Squadron"
			type = interceptor
			strength = 100
			model = 4
		}
		division = {
			id = { type = 21000 id = 107 }
			name = "233rd Fighter Squadron"
			type = interceptor
			strength = 100
			model = 4
		}
	}
	airunit = {
		id = { type = 21000 id = 108 }
		location = 1323
		base = 1323
		name = "443rd Tactical Fighter Wing"
		division = {
			id = { type = 21000 id = 109 }
			name = "109th Fighter Squadron"
			type = interceptor
			strength = 100
			model = 4
		}
		division = {
			id = { type = 21000 id = 110 }
			name = "55th Fighter Squadron"
			type = interceptor
			strength = 100
			model = 4
		}
		division = {
			id = { type = 21000 id = 111 }
			name = "173rd Fighter Squadron"
			type = interceptor
			strength = 100
			model = 4
		}
	}
	airunit = {
		id = { type = 21000 id = 112 }
		location = 1323
		base = 1323
		name = "455th Tactical Fighter Wing"
		division = {
			id = { type = 21000 id = 113 }
			name = "453rd Fighter Squadron"
			type = interceptor
			strength = 100
			model = 4
		}
		division = {
			id = { type = 21000 id = 114 }
			name = "432nd Fighter Squadron"
			type = interceptor
			strength = 100
			model = 4
		}
		division = {
			id = { type = 21000 id = 115 }
			name = "499th Fighter Squadron"
			type = multi_role
			strength = 100
			model = 6
		}
	}
	airunit = {
		id = { type = 21000 id = 116 }
		location = 1323
		base = 1323
		name = "737th Tactical Fighter Wing"
		division = {
			id = { type = 21000 id = 117 }
			name = "444th Fighter Squadron"
			type = multi_role
			strength = 100
			model = 6
		}
		division = {
			id = { type = 21000 id = 118 }
			name = "421st Fighter Squadron"
			type = interceptor
			strength = 100
			model = 4
		}
		division = {
			id = { type = 21000 id = 119 }
			name = "427th Fighter Squadron"
			type = interceptor
			strength = 100
			model = 4
		}
	}
	airunit = {
		id = { type = 21000 id = 120 }
		location = 1323
		base = 1323
		name = "1st Transport Wing"
		division = {
			id = { type = 21000 id = 121 }
			name = "1st Transport Regiment"
			type     = transport_plane
			strength = 100
			model = 2
		}
	}
} 
 