#################################
# Country definition for Zambia #
#################################

country =
{ tag                 = U45
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 500
  supplies            = 500
  money               = 100
  capital             = 1129
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 3
    political_left    = 7
    freedom           = 4
    free_market       = 4
    professional_army = 5
    defense_lobby     = 8
    interventionism   = 8
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  ownedprovinces      = { 1104 4947 4948 4949 4950 4954 7340 4952 4951 4956 2801 4953 4957 4955 4958 4959 2803 4960 4961 4962 4963 4964 4965 2802 1128 1129 1099 }
  controlledprovinces = { 1104 4947 4948 4949 4950 4954 7340 4952 4951 4956 2801 4953 4957 4955 4958 4959 2803 4960 4961 4962 4963 4964 4965 2802 1128 1129 1099 }
  nationalprovinces   = { 1104 4947 4948 4949 4950 4954 7340 4952 4951 4956 2801 4953 4957 4955 4958 4959 2803 4960 4961 4962 4963 4964 4965 2802 1128 1129 1099 }
  
  techapps = {
   ###################
   #     Infantry    #
   ###################
   #Infantry
   1010 
   #Motorized
   1100 
   #Mountain
   1160 
   #Special Forces
   1250 
   #Mechanized
   1470
   #Irregular Infantry
   1360
   #Combat Engineers
   1830
   #Supply and Repair
   1990
   ###################
   #Armor & Artillery#
   ###################
   #Main Battle Tanks
   2620
   #Armored Cars
   2860
   #Anti-Air
   2800
   #Armored Personnel Carriers
   2170
   #Field Artillery
   2290 
   #Self-Propelled Anti-Air
   2810
   #Man-Portable Air-Defense Systems
   3000
   #Self-Propelled Artillery
   2220
   #Self-Propelled Rocket Artillery
   2980 
   ###################
   #     Naval       #
   ###################
   #Frigates
   3110
   #Submarines
   3010
   #Transport Ships
   3900
   ###################
   #    Aircraft     #
   ###################
   #Multi-Role
   4500
   #Air Transports
   4250
   ###################
   #    Industry     #
   ###################
   #Light Industry
   5810
   #Heavy Industry
   5130
   #Material Science
   53050
   #Construction Eng.
   5800
   #Agriculture
   5700
   #Oil
   5190
   ###################
   #  Land Doctrines #
   ###################
   6500 
   6510 6530 
   1650
   6560 #Defensive
   ###################
   #  Air Doctrines  #
   ###################
   9190 9200
   }
}