#####################
# Country main data #
#####################

country =
{ tag                    = ARG
  manpower               = 200
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 20
  capital                = 851
  policy =
  { date              = { year = 0 month = january day = 0 }
     democratic        = 7
     political_left    = 8 
     free_market       = 8 
     freedom           = 8 
     professional_army = 4 
     defense_lobby     = 7 
     interventionism   = 6 
  }
  nationalprovinces      = { 667 853 852 843 844 845 851 854 855 857 858 859 862 863 850 
2554 2653 2654 2655 2860 2931 2998 
2932 2933 2934 2935 2954 2955 2956 2957 2958 2959 2490 1943
3893 3894 3895 3896 3897 3898 3899 3900 3901 3902 3903 3904 
3905 3906 3907 3908 3909 3910 3911 3912 3913 3914 3915 3916 
3917 3918 3919 3920 3921 3922 3923 3924 3925 3926 3927 3928 
3929 3930 3931 3932 3933 3934 3935 3936 3937 3938 3939 3940 
3941 3942 3943 3944 3945 3946 3947 3948 3949 5447 5448 5449 5450 5451 837 5444 7423
  }
  ownedprovinces         = { 667 853 852 843 844 845 851 854 855 857 858 859 862 863 850
2554 2653 2654 2655 2860 2931 2998
2932 2933 2934 2935 2954 2955 2956 2957 2958 2959 2490 1943 
3893 3894 3895 3896 3897 3898 3899 3900 3901 3902 3903 3904 
3905 3906 3907 3908 3909 3910 3911 3912 3913 3914 3915 3916 
3917 3918 3919 3920 3921 3922 3923 3924 3925 3926 3927 3928 
3929 3930 3931 3932 3933 3934 3935 3936 3937 3938 3939 3940 
3941 3942 3943 3944 3945 3946 3947 3948 3949 5447 5448 5449 5450 7423
  }
  controlledprovinces    = { 667 853 852 843 844 845 851 854 855 857 858 859 862 863 850
2554 2653 2654 2655 2860 2931 2998
2932 2933 2934 2935 2954 2955 2956 2957 2958 2959 2490 1943 
3893 3894 3895 3896 3897 3898 3899 3900 3901 3902 3903 3904 
3905 3906 3907 3908 3909 3910 3911 3912 3913 3914 3915 3916 
3917 3918 3919 3920 3921 3922 3923 3924 3925 3926 3927 3928 
3929 3930 3931 3932 3933 3934 3935 3936 3937 3938 3939 3940 
3941 3942 3943 3944 3945 3946 3947 3948 3949 5447 5448 5449 5450 7423
  }
  claimedprovinces = { 866 5456 5462 }

  techapps = {
   ###################
   #     Infantry    #
   ###################
   #Infantry
   1010 1020 1030
   #Motorized
   1100 1110 1120
   #Mountain
   1160 1170 1180
   #Special Forces
   1250 1260 1270
   #Naval Infantry
   1560 1570 1580
   #Airborne Infantry
   1670 1680 1690
   #Air Cavalry
   1396 1400
   #Armored Cavalry
   13060 13070
   #Mechanized
   1470 1480 1490
   #Irregular Infantry
   1360 1370 1380
   #Combat Engineers
   1830 1840 1850
   #Supply and Repair
   1990 199100 199110 199130 
   ###################
   #Armor & Artillery#
   ###################
   #Main Battle Tanks
   2620 2010 2630 2640 2646
   #Infantry Fighting Vehicles	
   2100
   #Armored Cars
   2860 2870 2950 
   #Anti-Air
   2800 2450 21180
   #Armored Personnel Carriers
   2170 2180 2850 2400 
   #Field Artillery
   2290 2300 2310
   #Self-Propelled Anti-Air
   2810 2820 2510
   #Man-Portable Air-Defense Systems
   3000 3170
   #Self-Propelled Artillery
   2220 2230
   #Self-Propelled Rocket Artillery
   2980 2260 2270
   ###################
   #     Naval       #
   ###################
   #Frigates
   3110 3120 3130
   #Cruisers
   3410 3420 3430 3440
   #Destroyers
   3310 3320 3330 3340
   #Light Aircraft Carriers
   12100
   #Submarines
   3010 3020 3030
   #Transport Ships
   3900 3910 3920
   ###################
   #    Aircraft     #
   ###################
   #Attack Helicopter
   4900
   #Reconnaissance Aircraft
   4770
   #Strategic Bomber
   4800
   #Strike Bomber
   15040
   #Naval Patrol
   4610
   #ASW Bomber
   4230
   #Attack Aircraft
   4030 4060 4090
   #Multi-Role
   4500 4570 4530 4540
   #Air Superiority Fighter
   4510 4520
   #Air Transports
   4250 4260
   #AEW&C
   4450 #4180
   #Air-to-Ground Missiles
   4040
   #Air-to-Air Missiles
   4600
   #Air-to-Sea Missiles
   4740
   ###################
   #    Industry     #
   ###################
   #Light Industry
   5810 5820
   #Heavy Industry
   5130 5110
   #Material Science
   53050 63160 63070
   #Construction Eng.
   5800 5080
   #Rocketry
   5560 5910
   #Agriculture
   5700 5710 5010
   #Oil
   5190 5220
   #Computing
   5310 54010 54020
   #Nuclear
   5470 5480 5490
   #Research
   5316
   #Cryptography
   5350 5360
   #Medicine
   5600 5610
   5630
   5660 5730
   ###################
   #  Land Doctrines #
   ###################
   6500 
   6510 6530 
   1650
   6560 #Defensive
   ###################
   # Naval Doctrines #
   ###################
   #Surface Ship Role
   81050 81060 81070 81080 81090 81100 81110 81120
   #Naval Interdiction
   8500 8510 8520 8550 8560 8570 8600 8610 8620
   #Naval Supremacy
   8100 8110 8150 8120 8160 8170 8200 8210 8220
   #Logistics Support
   82500 82510 82520 82530
   #Naval Capability
   8010
   #Amphibious Warfare
   82300
   ###################
   #  Air Doctrines  #
   ###################
   9390 9260 9400 9410
   9090 9100 9110 9120 9050 9060 9070
   9190 9200 9210 9220 9310 9320 9330 9340 9230 9240 9250
   9130 9420 9300
   }
  inventions = {  }
  diplomacy =
  { relation = { tag = BOL value = 50 }
    relation = { tag = BRA value = -10 }
    relation = { tag = CHL value = -20 }
    relation = { tag = COL value = 10 }
    relation = { tag = ENG value = 75 }
    relation = { tag = ECU value = 10 }
    relation = { tag = GER value = 75 }
    relation = { tag = IRE value = 20 }
    relation = { tag = ITA value = 30 }
    relation = { tag = PAR value = 50 }
    relation = { tag = PRU value = 20 }
    relation = { tag = URU value = -50 }
    relation = { tag = USA value = 75 }
    relation = { tag = VEN value = 10 }
  }
 
  # #####################################
  # ARMY
  # #####################################
  landunit =
  { id       = { type = 5500 id = 1 }
    location = 851 #2050
    name     = "Estado Mayor General del Ejército"
    division =
    { id       = { type = 5500 id = 2 }
      name     = "JEMGE HQ"
      strength = 100
      type     = hq
      model    = 0
     }
    division =
    { id       = { type = 5500 id = 3 }
      name     = "1a Brigada Blindada"
      strength = 100
      type     = light_armor
      model    = 1
    }
    division =
    { id       = { type = 5500 id = 4}
      name     = "4a Brigada Paracaidista"
      strength = 100
      type     = d_08
      model    = 4
    }
    division =
    { id       = { type = 5500 id = 5 }
      name     = "10a Brigada Mecanizada"
      strength = 100
      type     = cavalry
      model    = 2
    }
  }
  landunit =
  { id       = { type = 5500 id = 6 }
    location = 850 #2049
    name     = "II Cuerpo de Ejército"
    division =
    { id       = { type = 5500 id = 7 }
      name     = "2a Brigada Blindada"
      strength = 100
      type     = light_armor
      model    = 1
    }
    division =
    { id       = { type = 5500 id = 8 }
      name     = "12a Brigada de Monte"  # jungle warfare
      strength = 100
      type     = d_03
      model    = 2
    }
  }
  landunit =
  { id       = { type = 5500 id = 9 }
    location = 2935 #2054
    name     = "III Cuerpo de Ejército"
    division =
    { id       = { type = 5500 id = 10 }
      name     = "5a Brigada de Montaña"
      strength = 100
      type     = d_09
      model    = 5
    }
    division =
    { id       = { type = 5500 id = 11 }
      name     = "6a Brigada de Montaña"
      strength = 100
      type     = d_09
      model    = 5
    }
    division =
    { id       = { type = 5500 id = 12 }
      name     = "8a Brigada de Montaña"
      strength = 100
      type     = d_09
      model    = 5
    }
  }
  landunit =
  { id       = { type = 5500 id = 13 }
    location = 851 #2050
    name     = "V Cuerpo de Ejército"
    division =
    { id       = { type = 5500 id = 14 }
      name     = "9a Brigada Mecanizada"
      strength = 100
      type     = cavalry
      model    = 2
    }
    division =
    { id       = { type = 5500 id = 15 }
      name     = "11a Brigada Mecanizada"
      strength = 100
      type     = cavalry
      model    = 2
    }
  }
  landunit =
  { id       = { type = 5500 id = 16 }
    location = 851 #2050
    name     = "Comando de la Infantería de Marina"
    division =
    { id       = { type = 5500 id = 17 }
      name     = "1a Brigada de Marina"
      strength = 50
      type     = d_05
      model    = 4
    }
  }
  # #####################################
  # NAVY
  # #####################################
  navalunit =
  { id       = { type = 5500 id = 200 }
    location = 857
    base     = 857
    name     = "Flota de Mar"
    division =
    { id    = { type = 5500 id = 201 }
      name  = "ARA Almirante Brown"
	  strength = 100
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 5500 id = 202 }
      name  = "ARA La Argentina"
	  strength = 100
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 5500 id = 203 }
      name  = "ARA Heroína"
	  strength = 100
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 5500 id = 204 }
      name  = "ARA Sarandí"
	  strength = 100
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 5500 id = 206 }
      name  = "ARA Espora"
	  strength = 100
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 5500 id = 207 }
      name  = "ARA Rosales"
	  strength = 100
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 5500 id = 208 }
      name  = "ARA Spiro"
	  strength = 100
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 5500 id = 209 }
      name  = "ARA Parker"
	  strength = 100
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 5500 id = 210 }
      name  = "ARA Robinson"
	  strength = 100
      type  = destroyer
      model = 1
    }
    division =
    { id    = { type = 5500 id = 211 }
      name  = "ARA Gómez Roca"
	  strength = 100
      type  = destroyer
      model = 1
    }
  }
  navalunit =
  { id       = { type = 5500 id = 212 }
    location = 851 #2050
    base     = 851 #2050
    name     = "Comando Naval Anfibio"
    division =
    { id    = { type = 5500 id = 213 }
      name  = "ARA Hércules"
	  strength = 100
      type  = transport
      model = 5
    }
    division =
    { id    = { type = 5500 id = 214 }
      name  = "1a Escuadrilla de Transporte"
	  strength = 100
      type  = transport
      model = 5
    }
    division =
    { id    = { type = 5500 id = 215 }
      name  = "2a Escuadrilla de Transporte"
	  strength = 100
      type  = transport
      model = 5
    }
  }
  navalunit =
  { id       = { type = 5500 id = 220 }
    location = 851 #2050
    base     = 851 #2050
    name     = "Comando de la Fuerza de Submarinos"
    division =
    { id    = { type = 5500 id = 221 }
      name  = "ARA Santa Cruz"
	  strength = 100
      type  = submarine
      model = 5
    }
    division =
    { id    = { type = 5500 id = 222 }
      name  = "ARA San Juan"
	  strength = 100
      type  = submarine
      model = 5
    }
    division =
    { id    = { type = 5500 id = 223 }
      name  = "ARA Salta"
	  strength = 100
      type  = submarine
      model = 5
    }
  }
  # #####################################
  # AIR FORCE
  # #####################################
  airunit =
  { id       = { type = 5500 id = 100 }
    location = 851 #2050
    base     = 851 #2050
    name     = "Fuerza Aérea Argentina"
    division =
    { id       = { type = 5500 id = 101 }
      name     = "3a Brigada Aérea"
      type     = tactical_bomber
      strength = 100
      model    = 2
    }
    division =
    { id       = { type = 5500 id = 102 }
      name     = "5a Brigada Aérea"
      type     = tactical_bomber
      strength = 100
      model    = 2
    }
    division =
    { id       = { type = 5500 id = 103 }
      name     = "6a Brigada Aérea"
      type     = multi_role
      strength = 100
      model    = 5
    }
  }
  airunit =
  { id       = { type = 5500 id = 104 }
    location = 851 #2050
    base     = 851 #2050
    name     = "Brigada Aérea de Transporte"
    division =
    { id       = { type = 5500 id = 105 }
      name     = "1a Brigada Aérea"
      type     = transport_plane
      strength = 100
      model    = 2
    }
  }
}
 