#####################
# Country main data #
#####################

 province = { id =	606	naval_base = { size =	8 current_size = 8 } } # washington

country =
{ tag                    = USA
  capital                = 606
  manpower               = 1000
  # Resource Reserves
  energy                 = 30000
  metal                  = 20000
  rare_materials         = 7000
  oil                    = 10000
  supplies               = 10000
  money                  = 100000
  transports             = 5000
  escorts                = 3000
  
  peacetime_ic_mod       = 0.5
  
  diplomacy = {
		relation = { tag = JAP value = 150 access = yes guaranteed = { day = 21 month = december year = 2012 } }
  }
  
  SpyInfo                = { country = "ENG" NumberOfSpies = 2 }
  SpyInfo                = { country = "FRA" NumberOfSpies = 1 }
  SpyInfo                = { country = "SOV" NumberOfSpies = 5 }
  SpyInfo                = { country = "AST" NumberOfSpies = 1 }
  SpyInfo                = { country = "VEN" NumberOfSpies = 3 }
  SpyInfo                = { country = "SPR" NumberOfSpies = 3 }
  SpyInfo                = { country = "POL" NumberOfSpies = 1 }
  SpyInfo                = { country = "PAN" NumberOfSpies = 5 }
  SpyInfo                = { country = "ECU" NumberOfSpies = 1 }
  SpyInfo                = { country = "BOL" NumberOfSpies = 1 }
  SpyInfo                = { country = "CAN" NumberOfSpies = 3 }
  SpyInfo                = { country = "CUB" NumberOfSpies = 4 }
  SpyInfo                = { country = "SCH" NumberOfSpies = 2 }
  SpyInfo                = { country = "DOM" NumberOfSpies = 3 }
  SpyInfo                = { country = "GUA" NumberOfSpies = 2 }
  SpyInfo                = { country = "HAI" NumberOfSpies = 2 }
  SpyInfo                = { country = "ARG" NumberOfSpies = 1 }
  SpyInfo                = { country = "GER" NumberOfSpies = 1 }
  SpyInfo                = { country = "NIC" NumberOfSpies = 1 }
  SpyInfo                = { country = "SAL" NumberOfSpies = 1 }
  SpyInfo                = { country = "PRO" NumberOfSpies = 1 }
  SpyInfo                = { country = "JAP" NumberOfSpies = 1 }
  SpyInfo                = { country = "PHI" NumberOfSpies = 3 }
  SpyInfo                = { country = "BOL" NumberOfSpies = 2 }
  SpyInfo                = { country = "CAN" NumberOfSpies = 1 }
  SpyInfo                = { country = "CHL" NumberOfSpies = 1 }
  SpyInfo                = { country = "ITA" NumberOfSpies = 1 }
  SpyInfo                = { country = "CHI" NumberOfSpies = 1 }
  SpyInfo                = { country = "MEX" NumberOfSpies = 4 }
  nationalprovinces      = { 651 650 649 648 677 676 672 646 647 670 644 645 634 636 637 643 633 632 638 639 606
607 605 604 603 612 602 598 592 608 609 610 594 595 596 582 583 600 601 613 614 629
630 640 641 642 671 673 675 678 679 615 628 617 616 618 619 627 680 681 682 683 684
686 688 689 626 625 620 621 624 623 622 690 691 692 693 694 698 699 787 788 789 790
792 793 711 712 713 715 716 717 719 721 748 724 725 727 728 730 731 732 733 706 707
708 709 705 704 701 770 772 776 779 780 782 783 784 786 778 768 734 735 761 762
763 764 765 766 553 550 549 548 718 1278 2365 2367 2377 2261 2259 2255 1971 2676 2677
2678 2679 2680 2681 2682 2683 2684 2685 2686 2687 2688 2689 2690 2691 2692 2708 2709
2710 2711 2712 2713 2714 2715 2716 2717 2718 2719 2720 2721 2722 2723 2724 3558 889
6089 6090 6091 6092 6093 6094 6095 6096 6097 6098 
6099 6100 6101 6102 6103 6104 6105 6106 6107 6108 
6109 6110 6111 6112 6113 6114 6115 6116 6117 6118 
6119 6120 6121 6122 6123 6124 6125 6126 6127 6128 
6129 6130 6131 6132 6133 6134 6135 6136 6137 6138 
6139 6140 6141 6142 6143 6144 6145 6146 6147 6148 
6149 6150 6151 6152 6153 6154 6155 6156 6157 6158 
6159 6160 6161 6162 6163 6164 6165 6166 6167 6168 
6169 6170 6171 6172 6173 6174 6175 6176 6177 6178 
6179 6180 6181 6182 6183 6184 6185 6186 6187 6188 
6189 6190 6191 6192 6193 6194 6195 6196 6197 6198 
6199 6200 6201 6202 6203 6204 6205 6206 6207 6208 
6209 6210 6211 6212 6213 6214 6215 6216 6217 6218 
6219 6220 6221 6222 6223 6224 6225 6226 6227 6228 
6229 6230 6231 6232 6233 6234 6235 6236 6237 6238 
6239 6240 6241 6242 6243 6244 6245 6246 6247 6248 
6249 6250 6251 6252 6253 6254 6255 6256 6257 6258 
6259 6260 6261 6262 6263 6264 6265 6266 6267 6268 
6269 6270 6271 6272 6273 6274 6275 6276 6277 6278 
6279 6280 6281 6282 6283 6284 6285 6286 6287 6288 
6289 6290 6291 6292 6293 6294 6295 6296 6297 6298 
6299 6300 6301 6302 6303 6304 6305 6306 6307 6308 
6309 6310 6311 6312 6313 6314 6315 6316 6317 6318 
6319 6320 6321 6322 6323 6324 6325 6326 6327 6328 
6329 6330 6331 6332 6333 6334 6335 6336 6337 6338 
6339 6340 6341 6342 6343 6344 6345 6346 6347 6348 
6349 6350 6351 6352 6353 6354 6355 6356 6357 6358 
6359 6360 6361 6362 6363 6364 6365 6366 6367 6368 
6369 6370 6371 6372 6373 6374 6375 6376 6377 6378 
6379 6380 6381 6382 6383 6384 6385 6386 6387 6388 
6389 6390 6391 6392 6393 6394 6395 6396 6397 6398 
6399 6400 6401 6402 6403 6404 6405 6406 6407 6408 
6409 6410 6411 6412 6413 6414 6415 6416 6417 6418 
6419 6420 6421 6422 6423 6424 6425 6426 6427 6428 
6429 6430 6431 6432 6433 6434 6435 6436 6437 6438 
6439 6440 6441 6442 6443 6444 6445 6446 6447 6448 
6449 6450 6451 6452 6453 6454 6455 6456 6457 6458 
6459 6460 6461 6462 6463 6464 6465 6466 6467 6468 
6469 6470 6471 6472 6473 6474 6475 6476 6477 6478 
6479 6480 6481 6482 6483 6484 6485 6486 6487 6488
6843 6844 6845 6846 6847 6848 6849 6850 6851 6852 
6853 6854 6855 6856 6857 6858 6859 6860 6861 6862 
6863 6864 6865 6866 6867 6868 6869 6870 6871 6872 
6873 6874 6875 6876 6877 6878 6879 6880 6881
7242 7299
                       }
  ownedprovinces         = { 651  650  649  648  677  676  672  646  647    670  644  645  634    636  637  643  633  632    638  639  606 
                             607  605  604  603  612  602  598    592  608  609  610    594    595  596  582  583    600  601  613  614 
                             629  630  640  641  642  671  673   675  678  679  615  628  617  616  618  619  627  680  681  682  683  684   
                             686    688  689  626  625  620  621  624  623  622  690  691  692  693  694        698  699  787  788  789 
                             790    792  793    711  712  713    715  716  717  719   721  748   724  725  727  728    730 
                             731  732  733  706  707  708  709  705  704      701        770    772    776    779  780   
                             782  783  784    786  778    768  734    735  761  762  763  764  765  766  553   550  549  548   
                                       718      895  889  658  659  660    662  663  1766  1786 1624 
							   1765
							 1755 1760 1763
							 894 794 1278
							 2365 2367 2377 2261 2259 2255 1971
							 2676 2677 2678 2679 2680 2681 2682 2683 2684 2685
2686 2687 2688 2689 2690 2691 2692 2708 2709 2710
2711 2712 2713 2714 2715 2716 2717 2718 2719 2720
2721 2722 2723 2724 3558
6089 6090 6091 6092 6093 6094 6095 6096 6097 6098 
6099 6100 6101 6102 6103 6104 6105 6106 6107 6108 
6109 6110 6111 6112 6113 6114 6115 6116 6117 6118 
6119 6120 6121 6122 6123 6124 6125 6126 6127 6128 
6129 6130 6131 6132 6133 6134 6135 6136 6137 6138 
6139 6140 6141 6142 6143 6144 6145 6146 6147 6148 
6149 6150 6151 6152 6153 6154 6155 6156 6157 6158 
6159 6160 6161 6162 6163 6164 6165 6166 6167 6168 
6169 6170 6171 6172 6173 6174 6175 6176 6177 6178 
6179 6180 6181 6182 6183 6184 6185 6186 6187 6188 
6189 6190 6191 6192 6193 6194 6195 6196 6197 6198 
6199 6200 6201 6202 6203 6204 6205 6206 6207 6208 
6209 6210 6211 6212 6213 6214 6215 6216 6217 6218 
6219 6220 6221 6222 6223 6224 6225 6226 6227 6228 
6229 6230 6231 6232 6233 6234 6235 6236 6237 6238 
6239 6240 6241 6242 6243 6244 6245 6246 6247 6248 
6249 6250 6251 6252 6253 6254 6255 6256 6257 6258 
6259 6260 6261 6262 6263 6264 6265 6266 6267 6268 
6269 6270 6271 6272 6273 6274 6275 6276 6277 6278 
6279 6280 6281 6282 6283 6284 6285 6286 6287 6288 
6289 6290 6291 6292 6293 6294 6295 6296 6297 6298 
6299 6300 6301 6302 6303 6304 6305 6306 6307 6308 
6309 6310 6311 6312 6313 6314 6315 6316 6317 6318 
6319 6320 6321 6322 6323 6324 6325 6326 6327 6328 
6329 6330 6331 6332 6333 6334 6335 6336 6337 6338 
6339 6340 6341 6342 6343 6344 6345 6346 6347 6348 
6349 6350 6351 6352 6353 6354 6355 6356 6357 6358 
6359 6360 6361 6362 6363 6364 6365 6366 6367 6368 
6369 6370 6371 6372 6373 6374 6375 6376 6377 6378 
6379 6380 6381 6382 6383 6384 6385 6386 6387 6388 
6389 6390 6391 6392 6393 6394 6395 6396 6397 6398 
6399 6400 6401 6402 6403 6404 6405 6406 6407 6408 
6409 6410 6411 6412 6413 6414 6415 6416 6417 6418 
6419 6420 6421 6422 6423 6424 6425 6426 6427 6428 
6429 6430 6431 6432 6433 6434 6435 6436 6437 6438 
6439 6440 6441 6442 6443 6444 6445 6446 6447 6448 
6449 6450 6451 6452 6453 6454 6455 6456 6457 6458 
6459 6460 6461 6462 6463 6464 6465 6466 6467 6468 
6469 6470 6471 6472 6473 6474 6475 6476 6477 6478 
6479 6480 6481 6482 6483 6484 6485 6486 6487 6488
6503
6843 6844 6845 6846 6847 6848 6849 6850 6851 6852 
6853 6854 6855 6856 6857 6858 6859 6860 6861 6862 
6863 6864 6865 6866 6867 6868 6869 6870 6871 6872 
6873 6874 6875 6876 6877 6878 6879 6880 6881
7242 7299
#Pacific Islands
7202 1603 7199 7201 1608 1602 7198 1600 7200 1617 
1601 1604 7197 1618 7196 1619 1620 1621 7195 1625 
1626 1627 7194
                           }
  controlledprovinces    = { 651  650  649  648  677  676  672  646  647   670  644  645  634    636  637  643  633  632    638  639  606 
                             607  605  604  603  612  602  598    592  608  609  610   594    595  596  582  583    600  601  613  614 
                             629  630  640  641  642  671  673    675  678  679  615  628  617  616  618  619  627  680  681  682  683  684   
                             686    688  689  626  625  620  621  624  623  622  690  691  692  693  694        698  699  787  788  789 
                             790    792  793    711  712  713    715  716  717  719    721  748   724  725  727  728    730 
                             731  732  733  706  707  708  709  705  704      701        770    772    776    779  780  
                             782  783  784    786  778    768  734    735  761  762  763  764  765  766  553    550  549  548   
                                       718      895  889  658  659  660    662  663  1766  1786 1624  1765
 							 1755 1760 1763
							 894 794 1278
							 2365 2367 2377 2261 2259 2255 1971
							 2676 2677 2678 2679 2680 2681 2682 2683 2684 2685
2686 2687 2688 2689 2690 2691 2692 2708 2709 2710
2711 2712 2713 2714 2715 2716 2717 2718 2719 2720
2721 2722 2723 2724 3558
6089 6090 6091 6092 6093 6094 6095 6096 6097 6098 
6099 6100 6101 6102 6103 6104 6105 6106 6107 6108 
6109 6110 6111 6112 6113 6114 6115 6116 6117 6118 
6119 6120 6121 6122 6123 6124 6125 6126 6127 6128 
6129 6130 6131 6132 6133 6134 6135 6136 6137 6138 
6139 6140 6141 6142 6143 6144 6145 6146 6147 6148 
6149 6150 6151 6152 6153 6154 6155 6156 6157 6158 
6159 6160 6161 6162 6163 6164 6165 6166 6167 6168 
6169 6170 6171 6172 6173 6174 6175 6176 6177 6178 
6179 6180 6181 6182 6183 6184 6185 6186 6187 6188 
6189 6190 6191 6192 6193 6194 6195 6196 6197 6198 
6199 6200 6201 6202 6203 6204 6205 6206 6207 6208 
6209 6210 6211 6212 6213 6214 6215 6216 6217 6218 
6219 6220 6221 6222 6223 6224 6225 6226 6227 6228 
6229 6230 6231 6232 6233 6234 6235 6236 6237 6238 
6239 6240 6241 6242 6243 6244 6245 6246 6247 6248 
6249 6250 6251 6252 6253 6254 6255 6256 6257 6258 
6259 6260 6261 6262 6263 6264 6265 6266 6267 6268 
6269 6270 6271 6272 6273 6274 6275 6276 6277 6278 
6279 6280 6281 6282 6283 6284 6285 6286 6287 6288 
6289 6290 6291 6292 6293 6294 6295 6296 6297 6298 
6299 6300 6301 6302 6303 6304 6305 6306 6307 6308 
6309 6310 6311 6312 6313 6314 6315 6316 6317 6318 
6319 6320 6321 6322 6323 6324 6325 6326 6327 6328 
6329 6330 6331 6332 6333 6334 6335 6336 6337 6338 
6339 6340 6341 6342 6343 6344 6345 6346 6347 6348 
6349 6350 6351 6352 6353 6354 6355 6356 6357 6358 
6359 6360 6361 6362 6363 6364 6365 6366 6367 6368 
6369 6370 6371 6372 6373 6374 6375 6376 6377 6378 
6379 6380 6381 6382 6383 6384 6385 6386 6387 6388 
6389 6390 6391 6392 6393 6394 6395 6396 6397 6398 
6399 6400 6401 6402 6403 6404 6405 6406 6407 6408 
6409 6410 6411 6412 6413 6414 6415 6416 6417 6418 
6419 6420 6421 6422 6423 6424 6425 6426 6427 6428 
6429 6430 6431 6432 6433 6434 6435 6436 6437 6438 
6439 6440 6441 6442 6443 6444 6445 6446 6447 6448 
6449 6450 6451 6452 6453 6454 6455 6456 6457 6458 
6459 6460 6461 6462 6463 6464 6465 6466 6467 6468 
6469 6470 6471 6472 6473 6474 6475 6476 6477 6478 
6479 6480 6481 6482 6483 6484 6485 6486 6487 6488
6503
6843 6844 6845 6846 6847 6848 6849 6850 6851 6852 
6853 6854 6855 6856 6857 6858 6859 6860 6861 6862 
6863 6864 6865 6866 6867 6868 6869 6870 6871 6872 
6873 6874 6875 6876 6877 6878 6879 6880 6881
7242 7299
#Pacific Islands
7202 1603 7199 7201 1608 1602 7198 1600 7200 1617 
1601 1604 7197 1618 7196 1619 1620 1621 7195 1625 
1626 1627 7194
							 }

  techapps = {
   ###################
   #     Infantry    #
   ###################
   #Infantry
   1010 1020 1030 1040 1050
   #Motorized
   1100 1110 1120 1130 1140
   #Mountain
   1160 1170 1180 1190 1200
   #Special Forces
   1250 1260 1270 1280 1290
   #Naval Infantry
   1560 1570 1580 1590 1600
   #Airborne Infantry
   1670 1680 1690 1700 1710
   #Air Cavalry
   1396 1400 1410 1420
   #Armored Cavalry
   13060 13070 13080 1310
   #Mechanized
   1470 1480 1490 1500 1510
   #Irregular Infantry
   1360 1370 1380 1390 1530
   #Combat Engineers
   1830 1840 1850 1860 1870
   #Supply and Repair
   1990 199100 199110 199130 
   ###################
   #Armor & Artillery#
   ###################
   #Main Battle Tanks
   2620 2010 2630 2640 2646 2650 2030
   #Infantry Fighting Vehicles
   2100 2110 2120
   #Armored Cars
   2860 2870 2950 
   #Anti-Air
   2800 2450 21180 21190
   #Armored Personnel Carriers
   2170 2180 2850 2400 
   #Field Artillery
   2290 2300 2310 2900 
   #Self-Propelled Anti-Air
   2810 2820 2510 2520
   #Man-Portable Air-Defense Systems
   3000 3170 3180
   #Self-Propelled Artillery
   2220 2230 2240 2250 
   #Self-Propelled Rocket Artillery
   2980 2260 2270 2280 
   ###################
   #     Naval       #
   ###################
   #Frigates
   3110 3120 3130 3140 3150
   #Cruisers
   3410 3420 3430 3440 3450 3456 3460
   #Nuclear Cruisers
   3470 3480 12040 3770 3780
   #Destroyers
   3310 3320 3330 3340 3350 12030 3710
   #Light Aircraft Carriers
   12100 12110
   #Helicopter Carrier
   3210 3220 3230
   #Aircraft Carriers
   3510 3520 3530 
   #Supercarriers
   3540 3560 12060 3570
   #Submarines
   3010 3020 3030 3060 3070 3090
   #Nuclear Submarines
   12000 3080 3610 3680 3690
   #Nuclear Ballistic Submarines
   3620 3630 3640 3650
   #Transport Ships
   3900 3910 3920 3930 3940 3950
   ###################
   #    Aircraft     #
   ###################
   #Attack Helicopter
   4900 4910 4920 4930
   #Reconnaissance Aircraft
   4770 4780
   #Strategic Bomber
   4800 4810
   #Strike Bomber
   15040 15050 4360
   #Naval Patrol
   4610 4620
   #ASW Bomber
   4230 4240
   #Attack Aircraft
   4030 4060 4090 15000 15010 15020
   #Multi-Role
   4500 4570 4530 4540 4550 4010 4020
   #Air Superiority Fighter
   4510 4520 4300 4310 4320
   #Carrier Air Groups
   #ACAG
   2320 2330 2340 2350
   #MRCAG
   2140 2150 2160 2190 2200
   #FCAG
   2020 2070 2080 2090 2130
   #Air Transports
   4250 4260 4270 4290
   #AEW&C
   4450 4180
   #VTOL Aircraft
   4350
   #Air-to-Ground Missiles
   4040
   #Air-to-Air Missiles
   4600
   #Air-to-Sea Missiles
   4740
   ###################
   #    Industry     #
   ###################
   #Light Industry
   5810 5820 5050
   #Heavy Industry
   5130 5110 5120
   #Material Science
   53050 63160 63070 #63080
   #Construction Eng.
   5800 5080 5090
   #Rocketry
   5560 5910 5410 53030 5450 5460 
   5426 5440 5430 #5476 Moon Landing
   #Agriculture
   5700 5710 5010
   #Oil
   5190 5220
   #Computing
   5310 54010 54020 54030 5320 53116 5330 53060 #5340 5920
   #Nuclear
   5470 5480 5490 5500 5510 5520 5530 5540
   #Research
   5316
   #Cryptography
   5350 5360 5370 5380
   #Medicine
   5600 5610 5680
   5630
   5660 5730
   ###################
   #  Land Doctrines #
   ###################
   6500 
   6510 6530 
   1650
   6900 6730 6750 6820 6740 6810 6760 6210 6220 6230 6240 6250 6260 6270 6280 6290 14100 
   ###################
   #  Secret Weapons #
   ###################
   #Stealth Fighter
   3390
   #
   
   #
   ###################
   # Naval Doctrines #
   ###################
   #Carrier Supremacy
   8900 8910 8920 8930 8940 8950 8960
   #Surface Ship Role
   81050 81060 81070 81080 81090 81100 81110 81120
   #Naval Interdiction
   8500 8510 8520 8550 8560 8570 8600 8610 8620 8630 8640 8650 8660 8700 8710 8720 8730 8740 8750
   #Naval Supremacy
   8100 8110 8150 8120 8160 8170 8200 8210 8220 8230 8240 8250 8260 8300 8310 8320 8330 8340 8350
   #Logistics Support
   82500 82510 82520 82530
   #Naval Capability
   8010 8020 8030
   #Amphibious Warfare
   82300 82310 82320 82330
   ###################
   #  Air Doctrines  #
   ###################
   9390 9260 9400 9410
   9090 9100 9110 9120 9050 9060 9070
   9190 9200 9210 9220 9310 9320 9330 9340 9230 9240 9250
   9130 9420 9300
   27320 27330 27350 27360 27380 27390
   27000 27140 27150 27160 27170 27180 27190 27200
   9270 27070 27080 27090 27100 27110 27120 27130
  }
  inventions = {}
  
  policy =
  { date              = { year = 0 month = january day = 0 }
     democratic        = 10 
     political_left    = 2  
     freedom           = 10  
     free_market       = 10  
     professional_army = 4  
     defense_lobby     = 7  
     interventionism   = 10
  }
  
  #US Army
  landunit =  
  { location = 670 #Ft McPherson, GA - Atlanta
	name     = "FORSCOM HQ"  
    id       = {  type = 14800 id = 3  }  
    Division =  
	{	id   = {  type = 14800 id = 4  }  
		name = "FORSCOM HQ"
		strength = 100	
		type = hq
		model = 4
		}  
    }  
  landunit =  
  { location = 6464 #Ft Meade, MD - Annapolis
	name     = "First US Army"  
    id       = {  type = 14800 id = 5  }  
    Division =  
	{	id   = {  type = 14800 id = 6  }  
		name = "First US Army"
		strength = 100	
		type = hq
		model = 4
		}  
    }
  landunit =  
  { location = 670 #Ft Gillem, GA - Atlanta
	name     = "Second US Army"  
    id       = {  type = 14800 id = 7  }  
    Division =  
	{	id   = {  type = 14800 id = 8  }  
		name = "Second US Army"
		strength = 100	
		type = hq
		model = 4
		}  
    }
  landunit =  
  { location = 670 #Ft McPherson, GA - Atlanta
	name     = "Third US Army"  
    id       = {  type = 14800 id = 9  }  
    Division =  
	{	id   = {  type = 14800 id = 10  }  
		name = "Third US Army"
		strength = 100	
		type = hq
		model = 4
		}  
    }
  landunit =  
  { location = 620 #Ft Sheridan, IL - Chicago
	name     = "Fourth US Army"  
    id       = {  type = 14800 id = 11  }  
    Division =  
	{	id   = {  type = 14800 id = 12  }  
		name = "Fourth US Army"
		strength = 100	
		type = hq
		model = 4
		}  
    }
  landunit =  
  { location = 717 #Ft Sam Houston, TX - San Antonio
	name     = "Fifth US Army"  
    id       = {  type = 14800 id = 13  }  
    Division =  
	{	id   = {  type = 14800 id = 14  }  
		name = "Fifth US Army"
		strength = 100	
		type = hq
		model = 4
		}  
    }
  landunit =  
  { location = 765 #San Francisco, CA
	name     = "Sixth US Army"  
    id       = {  type = 14800 id = 15  }  
    Division =  
	{	id   = {  type = 14800 id = 16  }  
		name = "Sixth US Army"
		strength = 100	
		type = hq
		model = 4
		}  
    }
  landunit =  
  { location = 782 #Ft Lewis, WA - Tacoma
	name     = "I US Corps HQ"  
    id       = {  type = 14800 id = 17  }  
    Division =  
	{	id   = {  type = 14800 id = 18  }  
		name = "I US Corps HQ"
		strength = 100	
		type = hq
		model = 4
		extra = anti_air
		brigade_model = 4
		}  
	Division =  
	{	id   = {  type = 14800 id = 19  } #Colocar CAB
		name = "9th Infantry Division"
		strength = 100	
		type = motorized
		model = 5
		}
	}
  landunit =  
  { location = 6126 #Ft Ord, CA - Salinas
	name     = "7th Infantry Division"  
    id       = {  type = 14800 id = 20  }  
    Division =  
	{	id   = {  type = 14800 id = 21  } #Colocar CAB  
		name = "7th Infantry Division"
		strength = 100	
		type = infantry
		model = 5
		}  
	}
  landunit =  
  { location = 6254 #Ft Hood, TX - Killeen
	name     = "III US Corps HQ"  
    id       = {  type = 14800 id = 22  }  
    Division =  
	{	id   = {  type = 14800 id = 23  }  
		name = "III US Corps HQ"
		strength = 100	
		type = hq
		model = 4
		extra = anti_air
		brigade_model = 4
		}  
	Division =  
	{	id   = {  type = 14800 id = 24  } #Colocar CAB  
		name = "1st Cavalry Division"
		strength = 100	
		type = cavalry
		model = 5
		}
	Division =  
	{	id   = {  type = 14800 id = 25  } #Colocar CAB  
		name = "2nd Armored Division"
		strength = 100	
		type = armor
		model = 5
		}
	}
  landunit =  
  { location = 6235 #Ft Riley, KS - Manhattan (The Little Apple)
	name     = "1st Infantry Division"  
    id       = {  type = 14800 id = 26  }  
	Division =  
	{	id   = {  type = 14800 id = 27  } #Colocar CAB  
		name = "1st Infantry Division"
		strength = 100	
		type = motorized
		model = 5
		}
	}
  landunit =  
  { location = 709 #Ft Carson, CO - Colorado Springs
	name     = "4th Infantry Division"  
    id       = {  type = 14800 id = 28  }  
	Division =  
	{	id   = {  type = 14800 id = 29  } #Colocar CAB  
		name = "4th Infantry Division"
		strength = 100	
		type = mechanized
		model = 5
		}
	}
  landunit =  
  { location = 6277 #Ft. Polk, LA - Alexandria
	name     = "5th Infantry Division"  
    id       = {  type = 14800 id = 30  }  
	Division =  
	{	id   = {  type = 14800 id = 31  } #Colocar CAB  
		name = "5th Infantry Division"
		strength = 100	
		type = mechanized
		model = 5
		}
	}
  landunit =  
  { location = 718 #Ft Bliss, TX - El Paso
	name     = "3rd Armored Cavalry Regiment"  
    id       = {  type = 14800 id = 32  }  
	Division =  
	{	id   = {  type = 14800 id = 33  } #Colocar CAB  
		name = "3rd Armored Cavalry Regiment"
		strength = 100	
		type = cavalry
		model = 5
		}
	}
  landunit =  
  { location = 6254 #Ft Hood, TX - Killeen
	name     = "6th Cavalry Brigade"  
    id       = {  type = 14800 id = 34  }  
	Division =  
	{	id   = {  type = 14800 id = 35  }  
		name = "6th Cavalry Brigade"
		strength = 100	
		type = d_04
		model = 5
		}
	}
  landunit =  
  { location = 636 #Ft Bragg, NC - Raleigh
	name     = "XVIII US Airborne Corps HQ"  
    id       = {  type = 14800 id = 36  }  
	Division =  
	{	id   = {  type = 14800 id = 37  }  
		name = "XVIII US Airborne Corps HQ"
		strength = 100	
		type = hq
		model = 4
		}
	Division =  
	{	id   = {  type = 14800 id = 38  } #Colocar CAB  
		name = "82nd Airborne Division"
		strength = 100	
		type = paratrooper
		model = 5
		}
	}
  landunit =  
  { location = 6454 #Ft Campbell, KY - Clarksville
	name     = "101st Airborne Division"  
    id       = {  type = 14800 id = 39  }  
	Division =  
	{	id   = {  type = 14800 id = 40  } #Colocar CAB  
		name = "101st Airborne Division"
		strength = 100	
		type = paratrooper
		model = 5
		}
	}
  landunit =  
  { location = 6328 #Ft Drum, NY - Watertown
	name     = "10th Mountain Division"  
    id       = {  type = 14800 id = 41  }  
	Division =  
	{	id   = {  type = 14800 id = 42  } #Colocar CAB  
		name = "10th Mountain Division"
		strength = 100	
		type = bergsjaeger
		model = 5
		}
	}
  landunit =  
  { location = 646 #Ft Stewart, GA - Savannah
	name     = "24th Infantry Division"  
    id       = {  type = 14800 id = 43  }  
	Division =  
	{	id   = {  type = 14800 id = 44  } #Colocar CAB  
		name = "24th Infantry Division"
		strength = 100	
		type = mechanized
		model = 5
		}
	}
  landunit =  
  { location = 641 #Ft Knox, KY - Louisville
	name     = "194th Armored Brigade"  
    id       = {  type = 14800 id = 45  }  
	Division =  
	{	id   = {  type = 14800 id = 46  }  
		name = "194th Armored Brigade"
		strength = 100	
		type = light_armor
		model = 5
		}
	}
  landunit =  
  { location = 6444 #Ft Benning, GA - Columbus, GA
	name     = "197th Infantry Brigade"  
    id       = {  type = 14800 id = 47  }  
	Division =  
	{	id   = {  type = 14800 id = 48  }  
		name = "197th Infantry Brigade"
		strength = 100	
		type = d_06
		model = 5
		}
	}
  landunit =  
  { location = 6119 #Ft. Irwin, CA - Barstow
	name     = "177th Armored Brigade"  
    id       = {  type = 14800 id = 49  }  
	Division =  
	{	id   = {  type = 14800 id = 50  }  
		name = "177th Armored Brigade"
		strength = 100	
		type = light_armor
		model = 5
		}
	}
  #1st SPECIAL OPERATIONS COMMAND
  landunit =  
  { location = 636 #Ft Bragg, NC - Raleigh
	name     = "SOCOM HQ"  
    id       = {  type = 14800 id = 51  }  
	Division =  
	{	id   = {  type = 14800 id = 52  }  
		name = "SOCOM HQ" 
		strength = 100	
		type = hq
		model = 4
		}
	Division =  
	{	id   = {  type = 14800 id = 53  }  
		name = "Delta Force" 
		strength = 100	
		type = d_03
		model = 5
		}
	}
  landunit =  
  { location = 6444 #Ft Benning, GA - Columbus, GA
	name     = "75th Ranger Regiment"  
    id       = {  type = 14800 id = 54  }  
	Division =  
	{	id   = {  type = 14800 id = 55  }  
		name = "75th Ranger Regiment"
		strength = 100	
		type = d_03
		model = 5
		}
	}
  #US ARMY - EUROPE
  landunit =  
  { location = 1014 #Heidelberg, FRG - Karlsruhe
	name     = "7th US Army HQ"  
    id       = {  type = 14800 id = 56  }  
	Division =  
	{	id   = {  type = 14800 id = 57  }  
		name = "7th US Army HQ"
		strength = 100	
		type = hq
		model = 4
		}
	}
  landunit =  
  { location = 300 #Berlin, GDR
	name     = "Berlin Brigade"  
    id       = {  type = 14800 id = 58  }  
	Division =  
	{	id   = {  type = 14800 id = 59  }  
		name = "Berlin Brigade"
		strength = 100	
		type = d_01
		model = 5
		}
	}
  landunit =  
  { location = 313 #Frankfurt, FRG
	name     = "V US Corps HQ"  
    id       = {  type = 14800 id = 60  }  
	Division =  
	{	id   = {  type = 14800 id = 61  }  
		name = "V US Corps HQ"
		strength = 100	
		type = hq
		model = 4
		}
	Division =  
	{	id   = {  type = 14800 id = 62  } #Colocar CAB  
		name = "3rd Armored Division"
		strength = 100
		type = armor
		model = 5
		}
	}
  landunit =  
  { location = 1015 #Bad Kreuznach, FRG - Mainz
	name     = "8th Infantry Division"  
    id       = {  type = 14800 id = 63  }  
	Division =  
	{	id   = {  type = 14800 id = 64  } #Colocar CAB  
		name = "8th Infantry Division"
		strength = 100
		type = mechanized
		model = 5
		}
	}
  landunit =  
  { location = 2627 #Fulda, FRG
	name     = "11th Armored Cavalry Regiment"  
    id       = {  type = 14800 id = 65  }  
	Division =  
	{	id   = {  type = 14800 id = 66  } #Colocar CAB  
		name = "11th Armored Cavalry Regiment"
		strength = 100
		type = cavalry
		model = 5
		}
	}
  landunit =  
  { location = 314 #Stuttgart, FRG
	name     = "VII US Corps HQ"  
    id       = {  type = 14800 id = 67  }  
	Division =  
	{	id   = {  type = 14800 id = 68  }  
		name = "VII US Corps HQ"
		strength = 100
		type = hq
		model = 4
		}
	}
  landunit =  
  { location = 312 #Ansbach, FRG - Nürnberg
	name     = "1st Armored Division"  
    id       = {  type = 14800 id = 69  }  
	Division =  
	{	id   = {  type = 14800 id = 70  }  
		name = "1st Armored Division"
		strength = 100
		type = armor
		model = 5
		}
	}
  landunit =  
  { location = 547 #Wurzburg, FRG
	name     = "3rd Infantry Division"  
    id       = {  type = 14800 id = 71  }  
	Division =  
	{	id   = {  type = 14800 id = 72  } #Colocar CAB  
		name = "3rd Infantry Division"
		strength = 100
		type = mechanized
		model = 5
		}
	}
  #US ARMY - PACIFIC
  landunit =  
  { location = 663 #Ft Shafter, HI - Honolulu
	name     = "US Army Pacific HQ"  
    id       = {  type = 14800 id = 73  }  
	Division =  
	{	id   = {  type = 14800 id = 74  }  
		name = "US Army Pacific HQ"
		strength = 100
		type = hq
		model = 4
		}
	Division =  
	{	id   = {  type = 14800 id = 75  }	#Light
		name = "25th Infantry Division"
		strength = 100
		type = infantry
		model = 5
		}
	}
  landunit =  
  { location = 549 #Ft Richardson, Alaska - Anchorage
	name     = "6th Infantry Division"  
    id       = {  type = 14800 id = 76  }  
	Division =  
	{	id   = {  type = 14800 id = 77  }	#Light + CAB
		name = "6th Infantry Division"
		strength = 100
		type = infantry
		model = 5
		}
	}
  #US ARMY - JAPAN
  landunit =  
  { location = 1182 #Camp Zama, Japan - Yokohama
	name     = "IX US Corps HQ"  
    id       = {  type = 14800 id = 78  }  
	Division =  
	{	id   = {  type = 14800 id = 79  }
		name = "IX US Corps HQ"
		strength = 100
		type = hq
		model = 4
		}
	}
  #US ARMY - KOREA
  landunit =  
  { location = 1199 #Seoul, South Korea
	name     = "Eighth US Army HQ"  
    id       = {  type = 14800 id = 80  }  
	Division =  
	{	id   = {  type = 14800 id = 81  }
		name = "Eighth US Army HQ"
		strength = 100
		type = hq
		model = 4
		}
	Division =  
	{	id   = {  type = 14800 id = 82  }
		name = "2nd Infantry Division"
		strength = 100
		type = infantry
		model = 5
		}
	}
  #US ARMY - SOUTH
  landunit =  
  { location = 889 #Ft Clayton, Panama - Balboa
	name     = "SOUTHCOM HQ"  
    id       = {  type = 14800 id = 83  }  
	Division =  
	{	id   = {  type = 14800 id = 84  }
		name = "SOUTHCOM HQ"
		strength = 100
		type = hq
		model = 4
		}
	}
  #################novapaddy jan 2014########
  # FLEET MARINE FORCES PACIFIC
  #
  # US MARINE CORPS San Diego, El Toro 
  ###########################################
  landunit =  
  { location = 761 #san diego 
    name     = "1st Marine Expeditionary Force"  
    id       = {  type = 14800 id = 85  }  
    Division =  
    {   id   = {  type = 14800 id = 86  }  
        name = "1st Marine Division"
	    strength = 90		
        type = marine  
	    model    = 5
		}
	Division =  
    {  id   = {  type = 14800 id = 87  }  
        name = "5th Exped. Brigade"
		strength = 90		
        type = d_05  
		model    = 5
		}
	Division =  
    {  id   = {  type = 14800 id = 88  }  
        name = "7th Exped. Brigade"
		strength = 90		
        type = d_05  
		model    = 5
		}
	Division =  
    {  id   = {  type = 14800 id = 89  }  
        name = "3rd Mech. Marine Brigade"
		strength = 90		
        type = d_06  
		model    = 5
		}
  }
 ########################################
 # US MARINE CORPS Keneohe Bay, Honolulu 
 ########################################
 landunit =  
 {  location = 663 #honolulu 
    name     = "1st Marine Exped. Brigade"  
    id       = {  type = 14800 id = 94  }  
    Division =  
    {	id   = {  type = 14800 id = 95  }  
        name = "3rd Marine"
		strength = 90		
		type	= d_05  
		model	= 5
		}
 }
  ##################################
  # US MARINE CORPS Okinawa, Japan
  ##################################
  landunit =  
  { location = 1193 #Okinawa
    name     = "3rd Marine Exped. Force"  
    id       = {  type = 14800 id = 100  }  
    Division =  
    {	id   = {  type = 14800 id = 101  }  
		name = "3rd Marine Division"
		strength = 90		
		type = marine  
		model    = 5
		}
	Division =  
    {	id   = {  type = 14800 id = 102  }  
		name = "9th Exped. Brigade"
		strength = 90		
		type = d_05  
		model    = 5
		}
	Division =  
    {	id   = {  type = 14800 id = 103  }  
		name = "13th Exped. Brigade"
		strength = 90		
		type = d_05  
		model    = 5
		}
	Division =  
    {	id   = {  type = 14800 id = 104  }  
		name = "1st Assault Brigade"
		strength = 90		
		type = d_06  
		model    = 5
		}
  }
 ############################################################
 # FLEET MARINE FORCES ATLANTIC
 #
 # US MARINE CORPS camp lejeune, North Carolina
 ############################################################
 landunit =  
 {	location = 648 #jacksonville 
	name     = "11th Marine Expeditionary Force"  
	id       = {  type = 14800 id = 109  }  
	Division =  
    {	id   = {  type = 14800 id = 110  }  
		name = "2nd Marine Division"
		strength = 90		
		type = marine  
		model    = 5
		}
	Division =  
    {	id   = {  type = 14800 id = 111  }  
		name = "4th Exped. Brigade"
		strength = 90		
		type = d_05  
		model    = 5
		}
	Division =  
    {	id   = {  type = 14800 id = 112  }  
		name = "6th Exped. Brigade"
		strength = 90		
		type = d_05  
		model    = 5
		}
	Division =  
    {  id   = {  type = 14800 id = 113  }  
       name = "22nd Exped. Unit"
	   strength = 90		
       type = d_06
	   model    = 5
		}
	Division =  
    {	id   = {  type = 14800 id = 114  }  
		name = "3rd Recon Marine Brigade"
		strength = 90		
		type = d_06 
		model    = 5
		}
  }
  ##########################
  # US MARINE CORPS Reserve
  ##########################
  landunit =  
  { location = 679 #new orleans
    name     = "Marine Forces Reserve"  
    id       = {  type = 14800 id = 121  }  
    Division =  
    {	id   = {  type = 14800 id = 122  }  
		name = "4th Marine Division"
		strength = 90		
		type = marine  
		model    = 5
	}
  }
#####################
##US NAVY
###################
navalunit =  {
		name = "Carrier Group 1"  
		id = {  type = 14800 id = 123 }  
		location = 632  
		base     = 632  
		division = {
			id = {  type = 14800 id = 124  }  
			name = "Midway"  
			type = carrier 
			model = 4
		}
		division = {
			id = {  type = 14800 id = 125  }  
			name = "Chicago"  
			type = heavy_cruiser 
			model = 6
		}
		division = {
			id = {  type = 14800 id = 126  }  
			name = "Bronstein"  
			type = light_cruiser
			model = 4
		}
		division = {
			id = {  type = 14800 id = 127  }  
			name = "Spruance"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 128  }  
			name = "Tattnall"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 129  }  
			name = "Farragut"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 130  }  
			name = "Mahan"  
			type = destroyer
			model = 6
			}
	}
##############
navalunit =  {
		name = "Carrier Group 2"  
		id = {  type = 14800 id = 131 }  
		location = 765  
		base     = 765  
		division = {
			id = {  type = 14800 id = 132  }  
			name = "Coral Sea"  
			type = carrier 
			model = 4
		}
		division = {
			id = {  type = 14800 id = 133  }  
			name = "Leahy"  
			type = heavy_cruiser 
			model = 6
		}
		division = {
			id = {  type = 14800 id = 134  }  
			name = "Garcia"  
			type = light_cruiser
			model = 4
		}
		division = {
			id = {  type = 14800 id = 135  }  
			name = "Kidd"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 136  }  
			name = "Mitscher"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 137  }  
			name = "Yorktown"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 138  }  
			name = "Arleigh Burke"  
			type = destroyer
			model = 6
			}
	}
##############
navalunit =  {
		name = "Carrier Group 3"  
		id = {  type = 14800 id = 139 }  
		location = 600  
		base     = 600  
		division = {
			id = {  type = 14800 id = 140  }  
			name = "Forrestal"  
			type = carrier 
			model = 4
		}
		division = {
			id = {  type = 14800 id = 141  }  
			name = "Josephus Daniels"  
			type = heavy_cruiser 
			model = 6
		}
		division = {
			id = {  type = 14800 id = 142  }  
			name = "Brooke"  
			type = light_cruiser
			model = 4
		}
		division = {
			id = {  type = 14800 id = 143 }  
			name = "Prebie"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 144  }  
			name = "Barney"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 145  }  
			name = "Lawrence"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 146  }  
			name = "Biddle"  
			type = destroyer
			model = 6
			}
	}
##############
navalunit =  {
		name = "Carrier Group 4"  
		id = {  type = 14800 id = 147 }  
		location = 600  
		base     = 600  
		division = {
			id = {  type = 14800 id = 148  }  
			name = "Saratoga"  
			type = carrier 
			model = 4
		}
		division = {
			id = {  type = 14800 id = 149  }  
			name = "Ticonderoga"  
			type = heavy_cruiser 
			model = 6
		}
		division = {
			id = {  type = 14800 id = 150  }  
			name = "Underwood"  
			type = light_cruiser
			model = 4
		}
		division = {
			id = {  type = 14800 id = 151 }  
			name = "Henry B. Wilson"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 152  }  
			name = "Lynde McCormick"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 153  }  
			name = "Towers"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 154  }  
			name = "Sampson"  
			type = destroyer
			model = 6
			}
	}
##############
navalunit =  {
		name = "Carrier Group 5"  
		id = {  type = 14800 id = 155 }  
		location = 606  
		base     = 606  
		division = {
			id = {  type = 14800 id = 156  }  
			name = "Ranger"  
			type = carrier 
			model = 4
		}
		division = {
			id = {  type = 14800 id = 157  }  
			name = "Vincennes"  
			type = heavy_cruiser 
			model = 6
		}
		division = {
			id = {  type = 14800 id = 158  }  
			name = "Oliver Hazard"  
			type = light_cruiser
			model = 4
		}
		division = {
			id = {  type = 14800 id = 159 }  
			name = "Sellers"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 160  }  
			name = "Robison"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 161  }  
			name = "Hoel"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 162  }  
			name = "Buchanan"  
			type = destroyer
			model = 6
			}
	}
##############
navalunit =  {
		name = "Carrier Group 6"  
		id = {  type = 14800 id = 163 }  
		location = 1193  
		base     = 1193  
		division = {
			id = {  type = 14800 id = 164  }  
			name = "Independence"  
			type = carrier 
			model = 4
		}
		division = {
			id = {  type = 14800 id = 165  }  
			name = "Bainbridge"  
			type = heavy_cruiser 
			model = 6
		}
		division = {
			id = {  type = 14800 id = 166  }  
			name = "McCloy"  
			type = light_cruiser
			model = 4
		}
		division = {
			id = {  type = 14800 id = 167 }  
			name = "Berkeley"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 168  }  
			name = "Joseph Strauss"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 169  }  
			name = "Conyngham"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 170  }  
			name = "Semmes"  
			type = destroyer
			model = 6
			}
	}
##############		
navalunit =  {
		name = "Carrier Group 7"  
		id = {  type = 14800 id = 171 }  
		location = 1624  
		base     = 1624  
		division = {
			id = {  type = 14800 id = 172  }  
			name = "Kitty Hawk"  
			type = carrier 
			model = 4
		}
		division = {
			id = {  type = 14800 id = 173  }  
			name = "Truxtun"  
			type = heavy_cruiser 
			model = 6
		}
		division = {
			id = {  type = 14800 id = 174  }  
			name = "Bradley"  
			type = light_cruiser
			model = 4
		}
		division = {
			id = {  type = 14800 id = 175 }  
			name = "Tattnall"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 176  }  
			name = "Goldsborough"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 177  }  
			name = "Cochrane"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 178  }  
			name = "Ben Stoddert"  
			type = destroyer
			model = 6
			}
	}
##############
navalunit =  {
		name = "Carrier Group 8"  
		id = {  type = 14800 id = 179 }  
		location = 761  
		base     = 761  
		division = {
			id = {  type = 14800 id = 180  }  
			name = "Constellation"  
			type = carrier 
			model = 4
		}
		division = {
			id = {  type = 14800 id = 181  }  
			name = "California"  
			type = heavy_cruiser 
			model = 6
		}
		division = {
			id = {  type = 14800 id = 182  }  
			name = "Brumby"  
			type = light_cruiser
			model = 4
		}
		division = {
			id = {  type = 14800 id = 183 }  
			name = "Richard E Byrd"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 184  }  
			name = "Decatur"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 185  }  
			name = "John Paul Jones"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 186  }  
			name = "Parsons"  
			type = destroyer
			model = 6
			}
	}
##############
navalunit =  {
		name = "Carrier Group 9"  
		id = {  type = 14800 id = 187 }  
		location = 780  
		base     = 780  
		division = {
			id = {  type = 14800 id = 188  }  
			name = "America"  
			type = carrier 
			model = 4
		}
		division = {
			id = {  type = 14800 id = 189  }  
			name = "Virginia"  
			type = heavy_cruiser 
			model = 6
		}
		division = {
			id = {  type = 14800 id = 190  }  
			name = "Davidson"  
			type = light_cruiser
			model = 4
		}
		division = {
			id = {  type = 14800 id = 191 }  
			name = "Somers"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 192  }  
			name = "John S. McCain"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 193  }  
			name = "Luce"  
			type = destroyer
			model = 6
		}
		division = {
			id = {  type = 14800 id = 194  }  
			name = "Macdonough"  
			type = destroyer
			model = 6
			}
	}
#Transports
navalunit =  {
		name = "Pacific Transport Fleet"  
		id = {  type = 10848 id = 300  }  
		location = 765 #San Francisco
		base     = 765
		division = {
			id = {  type = 10848 id = 301  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 302  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 303  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 304  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 305  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 306  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 307 }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 308  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 309  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 310  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 311  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 312  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 313  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 314  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 315  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 316  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 317  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 318  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 319  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 320  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 321  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 322 }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 323  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 324  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 325  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 326  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 327  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 328  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 329  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 330  }  
			name = "Transport"  
			type = transport
			model = 5
		}
	}
navalunit =  {
		name = "Pacific Transport Fleet"  
		id = {  type = 10848 id = 400  }  
		location = 762 #Los Angeles
		base     = 762
		division = {
			id = {  type = 10848 id = 401  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 402  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 403  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 404  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 405  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 406  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 407 }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 408  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 409  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 410  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 411  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 412  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 413  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 414  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 415  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 416  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 417  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 418  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 419  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 420  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 421  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 422 }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 423  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 424  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 425  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 426  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 427  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 428  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 429  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 430  }  
			name = "Transport"  
			type = transport
			model = 5
		}
	}
navalunit =  {
		name = "Atlantic Transport Fleet"  
		id = {  type = 10848 id = 500  }  
		location = 600 #Boston
		base     = 600
		division = {
			id = {  type = 10848 id = 501  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 502  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 503  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 504  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 505  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 506  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 507 }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 508  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 509  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 510  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 511  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 512  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 513  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 514  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 515  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 516  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 517  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 518  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 519  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 520  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 521  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 522 }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 523  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 524  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 525  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 526  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 527  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 528  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 529  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 530  }  
			name = "Transport"  
			type = transport
			model = 5
		}
	}
navalunit =  {
		name = "Atlantic Transport Fleet"  
		id = {  type = 10848 id = 600  }  
		location = 632 #Norfolk
		base     = 632
		division = {
			id = {  type = 10848 id = 601  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 602  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 603  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 604  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 605  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 606  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 607 }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 608  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 609  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 610  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 611  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 612  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 613  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 614  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 615  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 616  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 617  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 618  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 619  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 620  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 621  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 622 }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 623  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 624  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 625  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 626  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 627  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 628  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 629  }  
			name = "Transport"  
			type = transport
			model = 5
		}
		division = {
			id = {  type = 10848 id = 630  }  
			name = "Transport"  
			type = transport
			model = 5
		}
	}
############################
##airforce
#############################
	airunit = {
	id = { type = 14800 id = 195 }
	name = "9th Air Force"
	location = 606 
	base = 606 
	division = {
	id = { type = 14800 id = 196 }
		name = "TacWing 1"
		strength = 100
		type = interceptor
		model = 5
			}
	division = {
	id = { type = 14800 id = 197 }
		name = "27th TacFighter Squadron"
		strength = 100
		type = interceptor
		model = 5
	}
	division = {
	id = { type = 14800 id = 198 }
		name = "71st TFS"
		strength = 100
		type = multi_role
		model = 7
	}
	division = {
	id = { type = 14800 id = 199 }
		name = "94th TFS"
		strength = 100
		type = interceptor
		model = 5
	}
	division = {
	id = { type = 14800 id = 200 }
		name = "6th Wing"
		strength = 100
		type = cas
		model = 5
	}
}
############
	airunit = {
	id = { type = 14800 id = 201 }
	name = "4th TacFighter Wing"
	location = 606 
	base = 606 
	division = {
	id = { type = 14800 id = 202 }
		name = "334th TFS"
		strength = 100
		type = interceptor
		model = 5
			}
	division = {
	id = { type = 14800 id = 203 }
		name = "335th TFS"
		strength = 100
		type = interceptor
		model = 5
	}
	division = {
	id = { type = 14800 id = 204 }
		name = "336st TFS"
		strength = 100
		type = interceptor
		model = 5
	}
}
############
	airunit = {
	id = { type = 14800 id = 205 }
	name = "23rd TFW"
	location = 600 
	base = 600 
	division = {
	id = { type = 14800 id = 206 }
		name = "74th TFS"
		strength = 100
		type = cas
		model = 5
			}
	division = {
	id = { type = 14800 id = 207 }
		name = "75th TFS"
		strength = 100
		type = cas
		model = 5
	}
	division = {
	id = { type = 14800 id = 208 }
		name = "76st TFS"
		strength = 100
		type = cas
		model = 5
	}
}
############
	airunit = {
	id = { type = 14800 id = 209 }
	name = "31st TFW"
	location = 600 
	base = 600 
	division = {
	id = { type = 14800 id = 210 }
		name = "306th TFS"
		strength = 100
		type = multi_role
		model = 7
			}
	division = {
	id = { type = 14800 id = 211 }
		name = "307th TFS"
		strength = 100
		type = multi_role
		model = 7
	}
	division = {
	id = { type = 14800 id = 212 }
		name = "308th TFS"
		strength = 100
		type = multi_role
		model = 7
	}
	division = {
	id = { type = 14800 id = 213 }
		name = "309th TFS"
		strength = 100
		type = multi_role
		model = 7
	}
}
############
	airunit = {
	id = { type = 14800 id = 214 }
	name = "33rd TFW"
	location = 651 
	base = 651 
	division = {
	id = { type = 14800 id = 215 }
		name = "58th TFS"
		strength = 100
		type = multi_role
		model = 7
			}
	division = {
	id = { type = 14800 id = 216 }
		name = "59th TFS"
		strength = 100
		type = multi_role
		model = 7
	}
	division = {
	id = { type = 14800 id = 217 }
		name = "60th TFS"
		strength = 100
		type = multi_role
		model = 7
	}
}
############
	airunit = {
	id = { type = 14800 id = 218 }
	name = "347th TFW"
	location = 651 
	base = 651 
	division = {
	id = { type = 14800 id = 219 }
		name = "68th TFS"
		strength = 100
		type = interceptor
		model = 5
			}
	division = {
	id = { type = 14800 id = 220 }
		name = "69th TFS"
		strength = 100
		type = interceptor
		model = 5
	}
	division = {
	id = { type = 14800 id = 221 }
		name = "70th TFS"
		strength = 100
		type = interceptor
		model = 5
	}
}
############
	airunit = {
	id = { type = 14800 id = 222 }
	name = "354th TFW"
	location = 651 
	base = 651 
	division = {
	id = { type = 14800 id = 223 }
		name = "353th TFS"
		strength = 100
		type = cas
		model = 5
			}
	division = {
	id = { type = 14800 id = 224 }
		name = "355th TFS"
		strength = 100
		type = cas
		model = 5
	}
	division = {
	id = { type = 14800 id = 225 }
		name = "356th TFS"
		strength = 100
		type = cas
		model = 5
	}
}
############
	airunit = {
	id = { type = 14800 id = 226 }
	name = "363rd TFW"
	location = 651 
	base = 651 
	division = {
	id = { type = 14800 id = 227 }
		name = "17th TFS"
		strength = 100
		type = multi_role
		model = 7
			}
	division = {
	id = { type = 14800 id = 228 }
		name = "19th TFS"
		strength = 100
		type = multi_role
		model = 7
	}
	division = {
	id = { type = 14800 id = 229 }
		name = "30th TFS"
		strength = 100
		type = multi_role
		model = 7
		}
	}
######################################
	airunit = {
	id = { type = 14800 id = 230 }
	name = "12th Air Force"
	location = 716 
	base = 716 
	division = {
	id = { type = 14800 id = 231 }
		name = "24th Tactical Wing"
		strength = 100
		type = strategic_bomber
		model = 1
			}
	division = {
	id = { type = 14800 id = 232 }
		name = "522th TFS"
		strength = 100
		type = strategic_bomber
		model = 1
	}
	division = {
	id = { type = 14800 id = 233 }
		name = "523rd TFS"
		strength = 100
		type = strategic_bomber
		model = 1
	}
}
############
	airunit = {
	id = { type = 14800 id = 234 }
	name = "37th TacFighter Wing"
	location = 716 
	base = 716 
	division = {
	id = { type = 14800 id = 235 }
		name = "561th Tactical Wing"
		strength = 100
		type = interceptor
		model = 5
			}
	division = {
	id = { type = 14800 id = 236 }
		name = "562nd TFS"
		strength = 100
		type = interceptor
		model = 5
	}
	division = {
	id = { type = 14800 id = 237 }
		name = "563rd TFS"
		strength = 100
		type = interceptor
		model = 5
	}
}
############
	airunit = {
	id = { type = 14800 id = 238 }
	name = "49th TacFighter Wing"
	location = 780 
	base = 780 
	division = {
	id = { type = 14800 id = 239 }
		name = "7th Tactical Wing"
		strength = 100
		type = interceptor
		model = 5
			}
	division = {
	id = { type = 14800 id = 240 }
		name = "8th TFS"
		strength = 100
		type = interceptor
		model = 5
	}
	division = {
	id = { type = 14800 id = 241 }
		name = "9th TFS"
		strength = 100
		type = interceptor
		model = 5
	}
}
############
	airunit = {
	id = { type = 14800 id = 242 }
	name = "67th TacFighter Wing"
	location = 716 
	base = 716 
	division = {
	id = { type = 14800 id = 243 }
		name = "12th TRS"
		strength = 100
		type = multi_role
		model = 7
			}
	division = {
	id = { type = 14800 id = 244 }
		name = "62nd TFS"
		strength = 100
		type = multi_role
		model = 7
	}
	division = {
	id = { type = 14800 id = 245 }
		name = "91st TFS"
		strength = 100
		type = multi_role
		model = 7
	}
	division = {
	id = { type = 14800 id = 246 }
		name = "45th TFS"
		strength = 100
		type = multi_role
		model = 7
	}
}
############
	airunit = {
	id = { type = 14800 id = 247 }
	name = "366th TacFighter Wing"
	location = 716 
	base = 716 
	division = {
	id = { type = 14800 id = 248 }
		name = "388th ECS"
		strength = 100
		type = strategic_bomber
		model = 1
			}
	division = {
	id = { type = 14800 id = 249 }
		name = "389th TFTS"
		strength = 100
		type = strategic_bomber
		model = 1
	}
	division = {
	id = { type = 14800 id = 250 }
		name = "391st TFS"
		strength = 100
		type = strategic_bomber
		model = 1
	}
}
############
	airunit = {
	id = { type = 14800 id = 251 }
	name = "388th TacFighter Wing"
	location = 620 
	base = 620 
	division = {
	id = { type = 14800 id = 252 }
		name = "4th TFS"
		strength = 100
		type = interceptor
		model = 5
			}
	division = {
	id = { type = 14800 id = 253 }
		name = "421st TFS"
		strength = 100
		type = interceptor
		model = 5
	}
	division = {
	id = { type = 14800 id = 254 }
		name = "34th TFS"
		strength = 100
		type = interceptor
		model = 5
	}
}
############
	airunit = {
	id = { type = 14800 id = 255 }
	name = "474th TacFighter Wing"
	location = 620 
	base = 620 
	division = {
	id = { type = 14800 id = 256 }
		name = "428th TFS"
		strength = 100
		type = interceptor
		model = 5
			}
	division = {
	id = { type = 14800 id = 257 }
		name = "429th TFS"
		strength = 100
		type = interceptor
		model = 5
	}
	division = {
	id = { type = 14800 id = 258 }
		name = "430th TFS"
		strength = 100
		type = interceptor
		model = 5
		}
	}
#######################
# Stealth Squadron
#######################
	airunit = {
	id = { type = 14800 id = 259 }
	name = "Stealth Squadron"
	location = 620 
	base = 620 
	division = {
	id = { type = 14800 id = 260 }
		name = "Stealth Squadron"
		strength = 100
		type = tactical_bomber
		model = 3
			}
	}
}