 
 ####################################
 # Country definition for the India # 
 #################################### 

 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 { tag                    = IND
   capital                = 1469 
   manpower               = 200 
   # Resource Reserves 
   energy                 = 5520
   metal                  = 2760
   rare_materials         = 1380
   oil                    = 500 
   supplies               = 500 
   money                  = 70 
   transports             = 200 
   escorts                = 20 
   #relative_manpower = 0.6000 
  
   
   diplomacy = 
   {   
  relation = {  tag = ENG value = 50 }  
    } 
   nationalprovinces      = {
		1469 1477 1476 1474 1454 1287 1284 1516 1517 1518 1519 1285 
	1286 1288 1456 1457 1878 1465 1466 1479 1478 1470 1471 1472 1468 
	1467 1464 1463 1460 1459 1458 1461 1508 1462 1505 1506 1507 1509 
	1510 1511 1512 1513 1514 1515
	1591 2106 1694 774 773 775
	1758 2639 777 2638 2085 1817
	2175 702 771 1695 2099 2640 635
	729 781 769 697 703 726 1699 714
	597 2637 2636 669 631 1721 611 722
	785 2198 2124 791 2091 1701 2104
	2592 2952 1877 1590 2043 2094
	2133 2641 599 2642 2199 2092
	685 687 736 1705 2835 1430
	1728 2828 1731 593 2922 
5195 5196 5197 5198 5199 5200 5201 5202 5203 5204 
5205 5206 5207 5208 5209 5210 5211 5212 5213 5214 
5215 5216 5217 5218 5219 5220 5221 5222 5223 5224 
5225 5226 5227 5228 5229 5230 5231 5232 5233 5234 
5235 5236 5237 5238 5239 5240 5241 5242 5243 5244 
5245 5246 5247 5248 5249 5250 5251 5252 5253 5254 
5255 5256 5257 5258 5259 5260 5261 5262 5263 5264 
5265 5266 5267 5268 5269 5270 5271 5272 5273 5274 
5275 5276 5277 5278 5279 5280 5281 5282 5283 5284 
5285 5286 5287 5288 5289 5290 5291 5292 5293 5294 
5295 5296 5297 5298 5299 5300 5301 5302 5303 5304 
5305 5306 5307 5308 5309 5310 5311 5312 5313 5314 
5315 5316 5317 5318 5319 5320 5321 5322 5323 5324 
5325 5326 5327 5328 5329 5330 5331 5332 5333 5334 
5335 5336 5337 5338 5339 5340 5341 5342 5343 5175 5176	
6921 6922 6920
7904 7192 7193 7307 7306 7924 7925 7305 7926 7292 7293 7175
	} 
   ownedprovinces         = {
		1469 1477 1476 1474 1454 1287 1284 1518 1519 
	1456 1457 1878 1465 1466 1479 1478 1470 1471 1472 1468 
	1467 1464 1463 1460 1459 1458 1461 1508 1462 1505 1506 1507 1509 
	1510 1511 1512 1513 1514 1515
	2106 1694 774 773 775
	1758 2639 777 2638
	2175 702 771 1695 2099 2640 635
	729 781 769 697 703 726 1699 714
	597 2637 2636 669 631 1721 611 722
	785 2198 2124 791 2091 1701 2104
	2592 2952 1877 2043 2094
	2133 2641 599 2642 2199 2092
	685 687 736 1705 2835
	593 2922 
5199 5200 5201 5202 5203 5204 
5205 5206 5207 5208 5209 5210 5211 5212 5213 5214 
5215 5216 5217 5218 5219 5220 5221 5222 5223 5224 
5225 5226 5227 5228 5229 5230 5231 5232 5233 5234 
5235 5236 5237 5238 5239 5240 5241 5242 5243 5244 
5245 5246 5247 5248 5249 5250 5251 5252 5253 5254 
5255 5256 5257 5258 5259 5260 5261 5262 5263 5264 
5265 5266 5267 5268 5269 5270 5271 5272 5273 5274 
5275 5276 5277 5278 5279 5280 5281 5282 5283 5284 
5285 5286 5287 5288 5289 5290 5291 5292 5293 5294 
5295 5296 5297 5298 5299 5300 5301 5302 5303 5304 
5305 5306 5307 5308 5309 5310 5311 5312 5313 5314 
5315 5316 5317 5318 5319 5320 5321 5322 5323 5324 
5325 5326 5327 5328 5329 5330 5331 5332 5333 5334 
5335 5336 5337 5338 5339 
6921 6922
7192 7193 7307 7306 7924
	} 
   controlledprovinces    = {
		1469 1477 1476 1474 1454 1287 1284 1518 1519 
	1456 1457 1878 1465 1466 1479 1478 1470 1471 1472 1468 
	1467 1464 1463 1460 1459 1458 1461 1508 1462 1505 1506 1507 1509 
	1510 1511 1512 1513 1514 1515
	2106 1694 774 773 775
	1758 2639 777 2638
	2175 702 771 1695 2099 2640 635
	729 781 769 697 703 726 1699 714
	597 2637 2636 669 631 1721 611 722
	785 2198 2124 791 2091 1701 2104
	2592 2952 1877 2043 2094
	2133 2641 599 2642 2199 2092
	685 687 736 1705 2835
	593 2922 
5199 5200 5201 5202 5203 5204 
5205 5206 5207 5208 5209 5210 5211 5212 5213 5214 
5215 5216 5217 5218 5219 5220 5221 5222 5223 5224 
5225 5226 5227 5228 5229 5230 5231 5232 5233 5234 
5235 5236 5237 5238 5239 5240 5241 5242 5243 5244 
5245 5246 5247 5248 5249 5250 5251 5252 5253 5254 
5255 5256 5257 5258 5259 5260 5261 5262 5263 5264 
5265 5266 5267 5268 5269 5270 5271 5272 5273 5274 
5275 5276 5277 5278 5279 5280 5281 5282 5283 5284 
5285 5286 5287 5288 5289 5290 5291 5292 5293 5294 
5295 5296 5297 5298 5299 5300 5301 5302 5303 5304 
5305 5306 5307 5308 5309 5310 5311 5312 5313 5314 
5315 5316 5317 5318 5319 5320 5321 5322 5323 5324 
5325 5326 5327 5328 5329 5330 5331 5332 5333 5334 
5335 5336 5337 5338 5339
6921 6922
7192 7193 7307 7306 7924
	} 
  
  SpyInfo                = {  country = "U02" NumberOfSpies = 3  } 
  
  techapps = {
   ###################
   #     Infantry    #
   ###################
   #Infantry
   1010 1020 1030
   #Motorized
   1100 1110 1120
   #Mountain
   1160 1170 1180
   #Special Forces
   1250 1260 1270
   #Naval Infantry
   1560 1570 1580
   #Airborne Infantry
   1670 1680 1690
   #Air Cavalry
   1396 1400
   #Armored Cavalry
   13060 13070
   #Mechanized
   1470 1480 1490
   #Irregular Infantry
   1360 1370 1380
   #Combat Engineers
   1830 1840 1850
   #Supply and Repair
   1990 199100 199110 199130 
   ###################
   #Armor & Artillery#
   ###################
   #Main Battle Tanks
   2620 2010 2630 2640 2646
   #Infantry Fighting Vehicles	
   2100
   #Armored Cars
   2860 2870 2950 
   #Anti-Air
   2800 2450 21180
   #Armored Personnel Carriers
   2170 2180 2850 2400 
   #Field Artillery
   2290 2300 2310
   #Self-Propelled Anti-Air
   2810 2820 2510
   #Man-Portable Air-Defense Systems
   3000 3170
   #Self-Propelled Artillery
   2220 2230
   #Self-Propelled Rocket Artillery
   2980 2260 2270
   ###################
   #     Naval       #
   ###################
   #Frigates
   3110 3120 3130
   #Cruisers
   3410 3420 3430 3440
   #Destroyers
   3310 3320 3330 3340
   #Light Aircraft Carriers
   12100
   #Submarines
   3010 3020 3030
   #Transport Ships
   3900 3910 3920
   ###################
   #    Aircraft     #
   ###################
   #Attack Helicopter
   4900
   #Reconnaissance Aircraft
   4770
   #Strategic Bomber
   4800
   #Strike Bomber
   15040
   #Naval Patrol
   4610
   #ASW Bomber
   4230
   #Attack Aircraft
   4030 4060 4090
   #Multi-Role
   4500 4570 4530 4540
   #Air Superiority Fighter
   4510 4520
   #Air Transports
   4250 4260
   #AEW&C
   4450 #4180
   #Air-to-Ground Missiles
   4040
   #Air-to-Air Missiles
   4600
   #Air-to-Sea Missiles
   4740
   ###################
   #    Industry     #
   ###################
   #Light Industry
   5810 5820
   #Heavy Industry
   5130 5110
   #Material Science
   53050 63160 63070
   #Construction Eng.
   5800 5080
   #Rocketry
   5560 5910
   #Agriculture
   5700 5710 5010
   #Oil
   5190 5220
   #Computing
   5310 54010 54020
   #Nuclear
   5470 5480 5490
   #Research
   5316
   #Cryptography
   5350 5360
   #Medicine
   5600 5610
   5630
   5660 5730
   ###################
   #  Land Doctrines #
   ###################
   6500 
   6510 6530 
   1650
   6560 #Defensive
   ###################
   # Naval Doctrines #
   ###################
   #Surface Ship Role
   81050 81060 81070 81080 81090 81100 81110 81120
   #Naval Interdiction
   8500 8510 8520 8550 8560 8570 8600 8610 8620
   #Naval Supremacy
   8100 8110 8150 8120 8160 8170 8200 8210 8220
   #Logistics Support
   82500 82510 82520 82530
   #Naval Capability
   8010
   #Amphibious Warfare
   82300
   ###################
   #  Air Doctrines  #
   ###################
   9390 9260 9400 9410
   9090 9100 9110 9120 9050 9060 9070
   9190 9200 9210 9220 9310 9320 9330 9340 9230 9240 9250
   9130 9420 9300
   }
  inventions = {  }
  policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 5 
     political_left    = 3 
     freedom           = 3 
     free_market       = 5 
     professional_army = 2 # no conscription 
     defense_lobby     = 3 
     interventionism   = 3 
    } 

   headofstate            = {  type = 9 id = 825001  } 
   headofgovernment       = {  type = 9 id = 825002  } 
   foreignminister        = {  type = 9 id = 825003  } 
   armamentminister       = {  type = 9 id = 825004  } 
   ministerofsecurity     = {  type = 9 id = 825005  } 
   ministerofintelligence = {  type = 9 id = 825006  } 
   chiefofstaff           = {  type = 9 id = 825007  } 
   chiefofarmy            = {  type = 9 id = 825008  } 
   chiefofnavy            = {  type = 9 id = 825009  } 
   chiefofair             = {  type = 9 id = 825010  } 
  
  # #####################################
  # ARMY
  # #####################################
  landunit =
  { id       = { type = 12300 id = 1 }
    location = 1474 #1540
    name     = "Northern Command"
    division =
    { id       = { type = 12300 id = 2 }
      name     = "NORCOM HQ"
      strength = 100
      type     = hq
      model    = 1
    }
  }
  landunit =
  { id       = { type = 12300 id = 4 }
    location = 1474 #1540
    name     = "XIV Corps"
    division =
    { id       = { type = 12300 id = 5 }
      name     = "3rd Infantry Division"
      strength = 100
      type     = motorized
      model    = 4
     
    }
    division =
    { id       = { type = 12300 id = 6 }
      name     = "8th Mountain Division"
      strength = 100
      type     = bergsjaeger
      model    = 4
    }
  }
  landunit =
  { id       = { type = 12300 id = 9 }
    location = 1474 #1540
    name     = "XV Corps"
    division =
    { id       = { type = 12300 id = 10 }
      name     = "19th Infantry Division"
      strength = 100
      type     = motorized
      model    = 4
      
    }
    division =
    { id       = { type = 12300 id = 11 }
      name     = "28th Mountain Division"
      strength = 100
      type     = bergsjaeger
      model    = 4
    }
  }
  landunit =
  { id       = { type = 12300 id = 12 }
    location = 1474 #1540
    name     = "XVI Corps"
    division =
    { id        = { type = 12300 id = 13 }
      name      = "10th Infantry Division"
      strength  = 100
      type      = motorized
      model     = 3
  
    }
    division =
    { id       = { type = 12300 id = 14 }
      name     = "25th Infantry Division"
      strength = 100
      type     = motorized
      model    = 3
    }
    division =
    { id       = { type = 12300 id = 15 }
      name     = "39th Infantry Division"
      strength = 100
      type     = motorized
      model    = 3
    }
  }
  landunit =
  { id       = { type = 12300 id = 16 }
    location = 5253 #1463
    name     = "Western Command"
    division =
    { id       = { type = 12300 id = 17 }
      name     = "WESTCOM HQ"
      strength = 100
      type     = hq
      model    = 1
    }
  }
  landunit =
  { id       = { type = 12300 id = 19 }
    location = 5253 #1463
    name     = "II Corps"
    division =
    { id       = { type = 12300 id = 20 }
      name     = "1st Armoured Division"
      strength = 100
      type     = armor
      model    = 4
    }
    division =
    { id       = { type = 12300 id = 22 }
      name     = "14th RAPID"
      strength = 100
      type     = infantry
      model    = 4
    
    }
    division =
    { id       = { type = 12300 id = 23 }
      name     = "22nd Infantry Division"
      strength = 100
      type     = motorized
      model    = 4
    } 
  }
  landunit =
  { id       = { type = 12300 id = 24 }
    location = 687 #1454
    name     = "IX Corps"
    division =
    { id       = { type = 12300 id = 25 }
      name     = "26th Infantry Division"
      strength = 100
      type     = motorized
      model    = 3
    }
    division =
    { id       = { type = 12300 id = 26 }
      name     = "29th Infantry Division"
      strength = 100
      type     = motorized
      model    = 3
    }
    division =
    { id       = { type = 12300 id = 27 }
      name     = "2nd Armoured Brigade"
      strength = 100
      type     = light_armor
      model    = 4
    }
    division =
    { id       = { type = 12300 id = 28 }
      name     = "3rd Armoured Brigade"
      strength = 100
      type     = light_armor
      model    = 4
    }
  }
  landunit =
  { id       = { type = 12300 id = 29 }
    location = 1476 #1531
    name     = "X Corps"
    division =
    { id       = { type = 12300 id = 33 }
      name     = "16th Infantry Division"
      strength = 100
      type     = motorized
      model    = 3
    } 
    division =
    { id       = { type = 12300 id = 31 }
      name     = "18th RAPID"
      strength = 100
      type     = infantry
      model    = 4
     
    }
    division =
    { id       = { type = 12300 id = 32 }
      name     = "24th RAPID"
      strength = 100
      type     = infantry
      model    = 4
    }
    division =
    { id       = { type = 12300 id = 30 }
      name     = "6th Armoured Brigade"
      strength = 100
      type     = light_armor
      model    = 4
    }
  }
  landunit =
  { id       = { type = 12300 id = 34 }
    location = 5253 #1463
    name     = "XI Corps"
    division =
    { id       = { type = 12300 id = 37 }
      name     = "7th Infantry Division"
      strength = 100
      type     = motorized
      model    = 4
    }
    division =
    { id       = { type = 12300 id = 38 }
      name     = "9th Infantry Division"
      strength = 100
      type     = motorized
      model    = 4
    }
    division =
    { id       = { type = 12300 id = 39 }
      name     = "15th Infantry Division"
      strength = 100
      type     = motorized
      model    = 4
    }
    division =
    { id       = { type = 12300 id = 35 }
      name     = "23rd Armoured Brigade"
      strength = 100
      type     = light_armor
      model    = 4
    }
    division =
    { id       = { type = 12300 id = 36 }
      name     = "55th Mechanized Brigade"
      strength = 100
      type     = cavalry
      model    = 4
    }
  }
  landunit =
  { id       = { type = 12300 id = 40 }
    location = 726 #1516
    name     = "Southern Command"
    division =
    { id       = { type = 12300 id = 41 }
      name     = "SOUTHCOM HQ"
      strength = 100
      type     = hq
      model    = 1
    }
    division =
    { id       = { type = 12300 id = 42 }
      name     = "50th Parachute Brigade"
      strength = 100
      type     = d_08
      model    = 4
    }
  }
  landunit =
  { id       = { type = 12300 id = 44 }
    location = 1479 #1525
    name     = "XII Corps"
    division =
    { id       = { type = 12300 id = 45 }
      name     = "4th Armoured Brigade"
      strength = 100
      type     = light_armor
      model    = 4
    }
    division =
    { id       = { type = 12300 id = 46 }
      name     = "340th Mechanized Brigade"
      strength = 100
      type     = cavalry
      model    = 4
    }
    division =
    { id       = { type = 12300 id = 47 }
      name     = "11th Infantry Division"
      strength = 100
      type     = motorized
      model    = 3
    }
    division =
    { id       = { type = 12300 id = 48 }
      name     = "12th Infantry Division"
      strength = 100
      type     = motorized
      model    = 3
    }
  }
  landunit =
  { id       = { type = 12300 id = 49 }
    location = 722 #1480
    name     = "XXI Corps"
    division =
    { id       = { type = 12300 id = 50 }
      name     = "31st Armoured Division"
      strength = 100
      type     = armor
      model    = 4
    
    }
    division =
    { id       = { type = 12300 id = 51 }
      name     = "36th RAPID"
      strength = 100
      type     = infantry
      model    = 4
      
    }
    division =
    { id       = { type = 12300 id = 52 }
      name     = "54th Infantry Division"
      strength = 100
      type     = motorized
      model    = 4
    }
  }
  landunit =
  { id       = { type = 12300 id = 53 }
    location = 2094 #1461
    name     = "Central Command"
    division =
    { id       = { type = 12300 id = 54 }
      name     = "CENTCOM HQ"
      strength = 100
      type     = hq
      model    = 1
    }
  }
  landunit =
  { id       = { type = 12300 id = 55 }
    location = 2094 #1461
    name     = "I Corps"
    division =
    { id       = { type = 12300 id = 56 }
      name     = "33rd Armoured Division"
      strength = 100
      type     = armor
      model    = 4
     
    }
    division =
    { id       = { type = 12300 id = 57 }
      name     = "4th Infantry Division"
      strength = 100
      type     = motorized
      model    = 4
    }
    division =
    { id       = { type = 12300 id = 58 }
      name     = "6th Mountain Division"
      strength = 100
      type     = bergsjaeger
      model    = 4
    }
  }
  landunit =
  { id       = { type = 12300 id = 61 }
    location = 1457 #1447
    name     = "Eastern Command"
    division =
    { id       = { type = 12300 id = 62 }
      name     = "EASTCOM HQ"
      strength = 100
      type     = hq
      model    = 1
    }
    division =
    { id       = { type = 12300 id = 63 }
      name     = "23rd Infantry Division"
      strength = 100
      type     = motorized
      model    = 4
    }
  }
  landunit =
  { id       = { type = 12300 id = 65 }
    location = 2592 #1441
    name     = "III Corps"
    division =
    { id       = { type = 12300 id = 66 }
      name     = "2nd Mountain Division"
      strength = 100
      type     = bergsjaeger
      model    = 4
    }
    division =
    { id       = { type = 12300 id = 67 }
      name     = "56th Mountain Division"
      strength = 100
      type     = bergsjaeger
      model    = 4
    }
    division =
    { id       = { type = 12300 id = 69 }
      name     = "57th Mountain Division"
      strength = 100
      type     = bergsjaeger
      model    = 4
    }
  }
  landunit =
  { id       = { type = 12300 id = 72 }
    location = 1878 #1455
    name     = "IV Corps"
    division =
    { id       = { type = 12300 id = 73 }
      name     = "5th Mountain Division"
      strength = 100
      type     = bergsjaeger
      model    = 4
    }
    division =
    { id       = { type = 12300 id = 76 }
      name     = "21st Mountain Division"
      strength = 100
      type     = bergsjaeger
      model    = 4
    }
    division =
    { id       = { type = 12300 id = 77 }
      name     = "71st Mountain Division"
      strength = 100
      type     = bergsjaeger
      model    = 4
    }
  }
  landunit =
  { id       = { type = 12300 id = 79 }
    location = 1456 #1446
    name     = "XXXIII Corps"
    division =
    { id       = { type = 12300 id = 80 }
      name     = "17th Mountain Division"
      strength = 100
      type     = bergsjaeger
      model    = 4
    }
    division =
    { id       = { type = 12300 id = 83 }
      name     = "20th Mountain Division"
      strength = 100
      type     = bergsjaeger
      model    = 4
    }
    division =
    { id       = { type = 12300 id = 86 }
      name     = "27th Mountain Division"
      strength = 100
      type     = bergsjaeger
      model    = 4
    }
  }
  landunit =
  { id       = { type = 12300 id = 87 }
    location = 1511 #1502
    name     = "Para Commandos"
    division =
    { id       = { type = 12300 id = 88 }
      name     = "Para Commandos"
      strength = 100
      type     = d_08
      model    = 4
     
    }
  }
 
# ###################################
# NAVY
# ###################################
navalunit ={ id = { type = 12300 id = 300 }
	location = 1457 #1447
	base     = 1457 #1447
	name     = "Western Fleet"
	division = { id = { type = 12300 id = 301 } name = "INS Viraat" type = carrier model = 1 }
    division = { id = { type = 12300 id = 302 } name = "INS Mysore" type = light_cruiser model = 1 }
	division = { id = { type = 12300 id = 303 } name = "INS Mumbai" type = light_cruiser model = 1 }
    division = { id = { type = 12300 id = 304 } name = "INS Rajput" type = light_cruiser model = 1 }
    division = { id = { type = 12300 id = 305 } name = "INS Rana" type  = light_cruiser model = 1 }
	division = { id = { type = 12300 id = 306 } name = "INS Ranvijay" type = light_cruiser model = 1 }
	division = { id = { type = 12300 id = 307 } name = "INS Talwar" type = destroyer model = 1 }
	division = { id = { type = 12300 id = 308 } name = "INS Trishul" type = destroyer model = 1 }
	division = { id = { type = 12300 id = 309 } name = "INS Brahmaputra" type = destroyer model = 1 }
	division = { id = { type = 12300 id = 310 } name = "INS Beas" type = destroyer model = 1 }
	division = { id = { type = 12300 id = 311 } name = "INS Gomati" type = destroyer model = 1 }
	}
navalunit = { id = { type = 12300 id = 330 }
	location = 1505 #1517
	base     = 1505 #1517
	name     = "Western Fleet Submarines"
	division = { id = { type = 12300 id = 331 } name = "INS Vagli" type = submarine model = 5 }
	division = { id = { type = 12300 id = 332 } name = "INS Karanj" type = submarine model = 5 }
	division = { id = { type = 12300 id = 333 } name = "INS Shankush" type = submarine model = 5 }
	division = { id = { type = 12300 id = 334 } name = "INS Shalki" type = submarine model = 5 }
	}
navalunit = { id = { type = 12300 id = 335 }
	location = 1505 #1517
	base     = 1505 #1517
	name     = "Eastern Fleet"
	division = { id = { type = 12300 id = 336 } name = "INS Delhi" type = light_cruiser model = 1 }
	division = { id = { type = 12300 id = 337 } name = "INS Ranjit" type = light_cruiser model = 1 }
	division = { id = { type = 12300 id = 338 } name = "INS Ranvir" type = light_cruiser model = 1 }
	division = { id = { type = 12300 id = 339 } name = "INS Himgiri" type = destroyer model = 1 }
	division = { id = { type = 12300 id = 340 } name = "INS Dunagiri" type = destroyer model = 1 }
	division = { id = { type = 12300 id = 341 } name = "INS Vindhyagiri" type = destroyer model = 1 }
	division = { id = { type = 12300 id = 342 } name = "INS Godavari" type = destroyer model = 1 }
	division = { id = { type = 12300 id = 343 } name = "INS Ganga" type = destroyer model = 1 }
	}
navalunit = { id = { type = 12300 id = 363 }
	location = 1457 #1447
	base     = 1457 #1447
	name     = "Eastern Fleet Transports"
	division = { id    = { type = 12300 id = 364 } name  = "1st Transport Fleet" type  = transport model = 5 }
    division = { id    = { type = 12300 id = 365 } name  = "2nd Transport Fleet" type  = transport model = 5 }
	division = { id    = { type = 12300 id = 366 } name  = "3rd Transport Fleet" type  = transport model = 5 }
	}
navalunit = { id = { type = 12300 id = 374 }
	location = 1457 #1447
	base     = 1457 #1447
	name     = "Eastern Fleet Submarines"
	division = { id = { type = 12300 id = 375 } name = "INS Shankul" type = submarine model = 4 }
	division = { id = { type = 12300 id = 376 } name = "INS Shishumar" type = submarine model = 4 }
	division = { id = { type = 12300 id = 377 } name = "INS Sindhugosh" type = submarine model = 4 }
	division = { id = { type = 12300 id = 378 } name = "INS Sindhudvaj" type = submarine model = 4 }
	division = { id = { type = 12300 id = 379 } name = "INS Sindhuraj" type = submarine model = 4 }
	division = { id = { type = 12300 id = 380 } name = "INS Sindhuvir" type = submarine model = 4 }
	division = { id = { type = 12300 id = 381 } name = "INS Sindhuratma" type = submarine model = 4 }
	division = { id = { type = 12300 id = 382 } name = "INS Sindhukesari" type = submarine model = 4 }
	division = { id = { type = 12300 id = 383 } name = "INS Sindhukirti" type = submarine model = 4 }
	division = { id = { type = 12300 id = 384 } name = "INS Sindhuvijay" type = submarine model = 4 }
	division = { id = { type = 12300 id = 385 } name = "INS Sindhurajshak" type = submarine model = 4 }
	division = { id = { type = 12300 id = 386 } name = "INS Sindhushastra" type = submarine model = 4 }
	division = { id = { type = 12300 id = 387 } name = "INS Vela" type = submarine model = 4 }
	division = { id = { type = 12300 id = 388 } name = "INS Vagir" type = submarine model = 4 }
	}
# ####################################
# AIR FORCE
# ####################################
airunit = { id = { type = 12300 id = 200 }
	location = 2094 #1461
	base     = 2094 #1461
	name     = "Central Air Command"
	division = { id = { type = 12300 id = 201 } name = "40th Fighter Squadron" type = multi_role strength = 100 model = 6 }
	division = { id = { type = 12300 id = 202 } name = "11th Fighter Squadron" type = multi_role strength = 100 model = 6 }
        division = { id = { type = 12300 id = 203 } name = "18th Fighter Squadron" type = multi_role strength = 80 model = 6 }
	}
airunit = { id = { type = 12300 id = 204 }
	location = 1457 #1447
	base     = 1457 #1447
	name     = "40th Figther Wing"
	division = { id = { type = 12300 id = 205 } name = "66th Fighter Squadron" type = multi_role strength = 80 model = 6 }
        division = { id = { type = 12300 id = 206 } name = "22nd Fighter Squadron" type = interceptor strength = 100 model = 4 }
        division = { id = { type = 12300 id = 207 } name = "37th Fighter Squadron" type = interceptor strength = 100 model = 4 }
	}
airunit = { id = { type = 12300 id = 208 }
	location = 1514 #1495
	base     = 1514 #1495
	name     = "20th Fighter Wing"
        division = { id = { type = 12300 id = 209 } name = "21st Fighter Squadron" type = interceptor strength = 100 model = 4 }
        division = { id = { type = 12300 id = 210 } name = "14th Fighter Squadron" type = interceptor strength = 100 model = 4 }
        division = { id = { type = 12300 id = 211 } name = "16th Fighter Squadron" type = interceptor strength = 100 model = 4 }
	}
airunit = { id = { type = 12300 id = 212 }
	location = 1505 #1517
	base     = 1505 #1517
	name     = "Eastern Air Command 1"
	division = { id = { type = 12300 id = 213 } name = "29th Fighter Squadron" type = interceptor strength = 100 model = 4 }
        division = { id = { type = 12300 id = 214 } name = "2nd Fighter Squadron" type = interceptor strength = 100 model = 4 }
        division = { id = { type = 12300 id = 215 } name = "3rd Fighter Squadron" type = interceptor strength = 100 model = 4 }
	}
airunit = { id = { type = 12300 id = 216 }
    location = 1469 #1459
    base     = 1469 #1459
    name     = "27th Ground Attack Wing"
    division = { id = { type = 12300 id = 217 } name = "33rd Ground Attack Squadron" type = cas strength = 100 model = 4 }
	division = { id = { type = 12300 id = 218 } name = "6th Ground Attack Squadron" type = cas strength = 100 model = 4 }
	division = { id = { type = 12300 id = 219 } name = "8th Ground Attack Squadron" type = cas strength = 100 model = 4 }
	division = { id = { type = 12300 id = 220 } name = "15th Ground Attack Squadron" type = cas strength = 100 model = 4 }
	}
airunit = { id = { type = 12300 id = 221 }
    location = 1469 #1459
    base     = 1469 #1459
    name     = "Western Air Command 1"
        division = { id = { type = 12300 id = 222 } name = "8th Fighter Squadron" type = interceptor strength = 100 model = 4 }
	division = { id = { type = 12300 id = 223 } name = "7th Fighter Squadron" type = interceptor strength = 100 model = 4 }
        division = { id = { type = 12300 id = 224 } name = "12th Fighter Squadron" type = interceptor strength = 100 model = 4 }
	}
airunit = { id = { type = 12300 id = 225 }
	location = 1469 #1459
	base     = 1469 #1459
	name     = "Western Air Command 2"
	division = { id = { type = 12300 id = 226 } name = "19th Ground Attack Squadron" type = cas strength = 100 model = 4 }
	division = { id = { type = 12300 id = 227 } name = "43rd Ground Attack Squadron" type = cas strength = 100 model = 4 }
	division = { id = { type = 12300 id = 228 } name = "55th Ground Attack Squadron" type = cas strength = 100 model = 4 }
	division = { id = { type = 12300 id = 229 } name = "25th Ground Attack Squadron" type = cas strength = 100 model = 4 }
	}
airunit = { id = { type = 12300 id = 230 }
	location = 1457 #1447
	base     = 1457 #1447
	name     = "Central Air Transport Command"
	division = 
	{ id = { type = 12300 id = 231 } 
	  name = "1st Air Transport Squadron" 
	  type     = transport_plane
	  strength = 100 
	  model = 2 
	  }
	}
# ###################################
# Under Development
# ###################################
  division_development =
  { id    = { type = 12300 id = 400 }
    name  = "INS Shivalik"
    type  = destroyer
    model = 1
    cost  = 5
    date  = { day = 29 month = august year = 1989 }
  }
  division_development =
  { id    = { type = 12300 id = 401 }
    name  = "INS Betwa"
    type  = destroyer
    model = 1
    cost  = 5
    date  = { day = 2 month = february year = 1990 }
  }
}