#####################
# Country main data #
#####################

country =
{ tag                    = PHI
  # Resource Reserves
  energy                 = 200
  metal                  = 200
  rare_materials         = 200
  oil                    = 200
  supplies               = 500
  money                  = 10
  manpower               = 200
  capital                = 1737
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 7
    political_left    = 6
    freedom           = 4
    free_market       = 5
    professional_army = 1
    defense_lobby     = 3
    interventionism   = 1
  }
  nationalprovinces      = { 
1735 1736 1737 1738 1739 1740 1741 1742 1743 1744 1745 1746 1747 1748 1749 1750
5715 5716 5717 5718 5719 5720 5721 5722 5723 5724 5725 5726 5727 5728 5729 5730 5731 5732 5733
1647 5744 5745 5746 7991
  }
  ownedprovinces         = { 
1735 1736 1737 1738 1739 1740 1741 1742 1743 1744 1745 1746 1747 1748 1749 1750 5891
5715 5716 5717 5718 5719 5720 5721 5722 5723 5724 5725 5726 5727 5728 5729 5730 5731 5732 5733
  }
  controlledprovinces    = { 
1735 1736 1737 1738 1739 1740 1741 1742 1743 1744 1745 1746 1747 1748 1749 1750 5891
5715 5716 5717 5718 5719 5720 5721 5722 5723 5724 5725 5726 5727 5728 5729 5730 5731 5732 5733
  }
	claimedprovinces = { 5836 5891 5873 5892 }
  techapps = {
   ###################
   #     Infantry    #
   ###################
   #Infantry
   1010 1020
   #Motorized
   1100 1110
   #Mountain
   1160 1170
   #Special Forces
   1250 1260
   #Naval Infantry
   1560 1570
   #Airborne Infantry
   1670 1680
   #Air Cavalry
   1396 #1400
   #Armored Cavalry
   13060
   #Mechanized
   1470 1480
   #Irregular Infantry
   1360 1370
   #Combat Engineers
   1830 1840
   #Supply and Repair
   1990 199100
   ###################
   #Armor & Artillery#
   ###################
   #Main Battle Tanks
   2620 2010 2630
   #Infantry Fighting Vehicles	
   2100
   #Armored Cars
   2860 2870 2950 
   #Anti-Air
   2800 2450
   #Armored Personnel Carriers
   2170 2180 2850
   #Field Artillery
   2290 2300 2310
   #Self-Propelled Anti-Air
   2810 2820 2510
   #Man-Portable Air-Defense Systems
   3000 3170
   #Self-Propelled Artillery
   2220 2230
   #Self-Propelled Rocket Artillery
   2980 2260 2270
   ###################
   #     Naval       #
   ###################
   #Frigates
   3110 3120 3130
   #Cruisers
   3410 3420 3430 3440
   #Destroyers
   3310 3320 3330 3340
   #Light Aircraft Carriers
   12100
   #Submarines
   3010 3020 3030
   #Transport Ships
   3900 3910
   ###################
   #    Aircraft     #
   ###################
   #Attack Helicopter
   4900
   #Reconnaissance Aircraft
   4770
   #Strategic Bomber
   4800
   #Strike Bomber
   15040 15050 4360
   #Naval Patrol
   4610
   #ASW Bomber
   4230
   #Attack Aircraft
   4030 4060 4090
   #Multi-Role
   4500 4570 4530 4540
   #Air Superiority Fighter
   4510 4520
   #Air Transports
   4250 4260
   #AEW&C
   4450
   #Air-to-Ground Missiles
   4040
   #Air-to-Air Missiles
   4600
   #Air-to-Sea Missiles
   4740
   ###################
   #    Industry     #
   ###################
   #Light Industry
   5810
   #Heavy Industry
   5130
   #Material Science
   53050 63160
   #Construction Eng.
   5800
   #Rocketry
   5560 5910
   #5426 5440 5430
   #Agriculture
   5700 5710
   #Oil
   5190 5220
   #Computing
   5310 54010 54020
   #Nuclear
   5470 5480
   #Cryptography
   5350 5360
   #Medicine
   5600 5610
   #5630
   5660 5730
   ###################
   #  Land Doctrines #
   ###################
   6500 
   6510 6530 
   1650
   #6900 6730 6750 6820 6740 6810 6760 6210 6220 6230 6240 6250 6260 6270 6280 6290 14100 #NATO
   6560 #Defensive
   ###################
   # Naval Doctrines #
   ###################
   #Surface Ship Role
   81050 81060 81070 81080 81090 81100 81110 81120
   #Naval Interdiction
   8500 8510 8520 8550 8560 8570 8600 8610 8620
   #Naval Supremacy
   8100 8110 8150 8120 8160 8170 8200 8210 8220
   #Logistics Support
   82500 82510
   #Naval Capability
   8010
   #Amphibious Warfare
   82300 82310 
   ###################
   #  Air Doctrines  #
   ###################
   9190 9200 9210 9220 9310 9320 9330 9340 9230 9240 9250
   }
  diplomacy =
  { relation = { tag = AST value = 40 }
    # relation = { tag = CHI value = 5 }
    relation = { tag = JAP value = 1 }
    relation = { tag = LIB value = 200 }
    relation = { tag = NZL value = 25 }
    relation = { tag = USA value = 200 }
  }
  #headofstate            = { type = 9 id = 50001 }
  #headofgovernment       = { type = 9 id = 50002 }
  #foreignminister        = { type = 9 id = 50003 }
  #armamentminister       = { type = 9 id = 50004 }
  #ministerofsecurity     = { type = 9 id = 50005 }
  #ministerofintelligence = { type = 9 id = 50006 }
  #chiefofstaff           = { type = 9 id = 50007 }
  #chiefofarmy            = { type = 9 id = 50008 }
  #chiefofnavy            = { type = 9 id = 50009 }
  #chiefofair             = { type = 9 id = 50010 }

	# #####################################
	# ARMY
	# #####################################
	landunit = {
		id = { type = 18100 id = 1 }
		location = 1738 #1569
		name = "Light Armor Brigade"
		division = {
			id = { type = 18100 id = 2 }
			name = "Light Armor Brigade"
			strength = 100
			type = cavalry
			model = 2
		}
	}
	landunit = {
		id = { type = 18100 id = 3 }
		location = 1748 #1580
		name = "1st Infantry Division"
		division = {
			id = { type = 18100 id = 4 }
			name = "1st Infantry Division"
			strength = 100
			type = motorized
			model = 2
		}
	}
        landunit = {
		id = { type = 18100 id = 5 }
		location = 1737 #1565
		name = "2nd Infantry Division"
		division = {
			id = { type = 18100 id = 6 }
			name = "2nd Infantry Division"
			strength = 100
			type = motorized
			model = 2
		}
	}
        landunit = {
		id = { type = 18100 id = 7 }
		location = 1746 #1576
		name = "3rd Infantry Division"
		division = {
			id = { type = 18100 id = 8 }
			name = "3rd Infantry Division"
			strength = 100
			type = motorized
			model = 2
		}
	}
        landunit = {
		id = { type = 18100 id = 9 }
		location = 1750 #1579
		name = "4th Infantry Division"
		division = {
			id = { type = 18100 id = 10 }
			name = "4th Infantry Division"
			strength = 100
			type = motorized
			model = 2
		}
	}
        landunit = {
		id = { type = 18100 id = 11 }
		location = 1741 #1567
		name = "5th Infantry Division"
		division = {
			id = { type = 18100 id = 12 }
			name = "5th Infantry Division"
			strength = 100
			type = motorized
			model = 2
		}
	}
        landunit = {
		id = { type = 18100 id = 13 }
		location = 1749 #1578
		name = "6th Infantry Division"
		division = {
			id = { type = 18100 id = 14 }
			name = "6th Infantry Division"
			strength = 100
			type = motorized
			model = 2
		}
	}
        landunit = {
		id = { type = 18100 id = 15 }
		location = 5732 #1566
		name = "7th Infantry Division"
		division = {
			id = { type = 18100 id = 16 }
			name = "7th Infantry Division"
			strength = 70
			type = motorized
			model = 2
		}
	}
        landunit = {
		id = { type = 18100 id = 17 }
		location = 5722 #1574
		name = "8th Infantry Division"
		division = {
			id = { type = 18100 id = 18 }
			name = "8th Infantry Division"
			strength = 70
			type = motorized
			model = 2
		}
	}
        landunit = {
		id = { type = 18100 id = 19 }
		location = 1737 #1565
		name = "Special Operations Command"
		division = {
			id = { type = 18100 id = 20 }
			name = "Special Operations Command"
			strength = 60
            type     = d_03
            model    = 2
                       
		}
	}
        landunit = {
		id = { type = 18100 id = 21 }
		location = 1737 #1565
		name = "Philippine Marine Corps"
		division = {
			id = { type = 18100 id = 22 }
			name = "1st Marine Brigade"
			strength = 80
			type = d_05
			model = 2
		}
            division = {
			id = { type = 18100 id = 23 }
			name = "2nd Marine Brigade"
			strength = 80
			type = d_05
			model = 2
		}
            division = {
			id = { type = 18100 id = 24 }
			name = "3rd Marine Brigade"
			strength = 80
			type = d_05
			model = 2
		}
            division = {
			id = { type = 18100 id = 25 }
			name = "4th Reserve Marine Brigade"
			strength = 10
			type = d_05
			model = 2
		}
	}
	# ###################################
	# NAVY
	# ###################################
	navalunit = {
		id = { type = 18100 id = 300 }
		location = 1737 #1565
		base = 1737 #1565
		name = "Philippine Navy"
		division = {
			id = { type = 18100 id = 301 }
			name = "BRP Rajah Humabon"
			type = destroyer
			model = 1
		}
		division = {
			id = { type = 18100 id = 316 }
			name = "1st Transport Fleet"
			type = transport
			model = 3
		}
		division = {
			id = { type = 18100 id = 319 }
			name = "2nd Transport Fleet"
			type = transport
			model = 3
		}
		division = {
			id = { type = 18100 id = 322 }
			name = "3rd Transport Fleet"
			type = transport
			model = 3
		}
	}
	# ####################################
	# AIR FORCE
	# ####################################
	airunit = {
		id = { type = 18100 id = 200 }
		location = 1739 #1570
		base = 1739 #1570
		name = "5th Fighter Wing"
		division = {
			id = { type = 18100 id = 201 }
			name = "6th Tactical Fighter Squadron"
			type = cas
			strength = 100
			model = 0
		}
		division = {
			id = { type = 18100 id = 202 }
			name = "'Blue Diamonds' Squadron"
			type = cas
			strength = 100
			model = 0
		}
	}
}
 
