	#####################
	# Country main data #
	#####################

	country =
	{ tag                    = TUR
	  # Resource Reserves
	  energy                 = 1000
	  metal                  = 1000
	  rare_materials         = 500
	  oil                    = 500
	  supplies               = 500
	  money                  = 20
	  capital                = 448
	  manpower               = 200
	  transports             = 35
	  escorts                = 10
	  policy =
	  { date              = { year = 0 month = january day = 0 }
		 democratic        = 4 
		 political_left    = 3 
		 freedom           = 4 
		 free_market       = 7 
		 professional_army = 5 
		 defense_lobby     = 8 
		 interventionism   = 8
	  }
	nationalprovinces      = { 
	409 408 437 438 439 441 442 443 448 440 449 447 446 445 450 1852 1853 1855 2322
	1158 1159 418 2611 2613 2873 2874 2875 2877 2879 2880 2881 2882 3398 3430
	4122 4123 4124 4128 
	4129 4130 4131 4132 4133 4134 4135 4136 4137 4138 
	4139 4140 4141 4142 4143 4144 4145 4146 4147 4148 444
	5412 5413
	7056 7057 7058 7059 7060 7061 7062 7063 7068 7259 7351 7976 
	2323 2321 7352
	  }
	ownedprovinces         = { 409 408 437 438 439 441 442 443 448 440 449 447 446 445 450 1851 1852 1853 1854 1855 2322
								1158 
								2611 2613 2873 2874 2875 2876 2877 2878 2879 2880
	2881 2882	3398	3430
	4118 4119 4120 4122 4123 4124 4125 4126 4127 4128 
	4129 4130 4131 4132 4133 4134 4135 4136 4137 4138 
	4139 4140 4141 4142 4143 4144 4145 4146 4147 4148
	7056 7057 7058 7059 7060 7061 7062 7063 7068 7069 7259 7351 7976 7982 1159
	  }
	controlledprovinces    = { 409 408 437 438 439 441 442 443 448 440 449 447 446 445 450 1851 1852 1853 1854 1855 2322
								1158 
								2611 2613 2873 2874 2875 2876 2877 2878 2879 2880
	2881 2882	3398	3430
	4118 4119 4120 4122 4123 4124 4125 4126 4127 4128 
	4129 4130 4131 4132 4133 4134 4135 4136 4137 4138 
	4139 4140 4141 4142 4143 4144 4145 4146 4147 4148
	7056 7057 7058 7059 7060 7061 7062 7063 7068 7069 7259 7351 7976 7982 1159
	  }
	  claimedprovinces 		 = { 
	4118 4119 2878 7982 4120 1851 4127 7069 4125 1854 4126 2876
	6507 7337 416 2610 410 411 6508 412 7055 405 6918 398 399 563
	396 7320 7357 1862 7280 7355 7281 1861 7353 4152 2019 4155
	2496 4156 7977 710 7349 1860 4154
	6509 7319 2319 392 7316 7163 664 5465 391 390 5466 7961
	665 3397 414 4474 6505 413 1169 3393 6562 415 2609 3372 
	7269 7270 7271 1894 2608 3374
	 } 
	  
	techapps = {
   ###################
   #     Infantry    #
   ###################
   #Infantry
   1010 1020 1030
   #Motorized
   1100 1110 1120
   #Mountain
   1160 1170 1180
   #Special Forces
   1250 1260 1270
   #Naval Infantry
   1560 1570 1580
   #Airborne Infantry
   1670 1680 1690
   #Air Cavalry
   1396 1400
   #Armored Cavalry
   13060 13070
   #Mechanized
   1470 1480 1490
   #Irregular Infantry
   1360 1370 1380
   #Combat Engineers
   1830 1840 1850
   #Supply and Repair
   1990 199100 199110 199130 
   ###################
   #Armor & Artillery#
   ###################
   #Main Battle Tanks
   2620 2010 2630 2640 2646
   #Infantry Fighting Vehicles	
   2100
   #Armored Cars
   2860 2870 2950 
   #Anti-Air
   2800 2450 21180
   #Armored Personnel Carriers
   2170 2180 2850 2400 
   #Field Artillery
   2290 2300 2310
   #Self-Propelled Anti-Air
   2810 2820 2510
   #Man-Portable Air-Defense Systems
   3000 3170
   #Self-Propelled Artillery
   2220 2230
   #Self-Propelled Rocket Artillery
   2980 2260 2270
   ###################
   #     Naval       #
   ###################
   #Frigates
   3110 3120 3130
   #Cruisers
   3410 3420 3430 3440
   #Destroyers
   3310 3320 3330 3340
   #Light Aircraft Carriers
   12100
   #Submarines
   3010 3020 3030
   #Transport Ships
   3900 3910 3920
   ###################
   #    Aircraft     #
   ###################
   #Attack Helicopter
   4900
   #Reconnaissance Aircraft
   4770
   #Strategic Bomber
   4800
   #Strike Bomber
   15040
   #Naval Patrol
   4610
   #ASW Bomber
   4230
   #Attack Aircraft
   4030 4060 4090
   #Multi-Role
   4500 4570 4530 4540
   #Air Superiority Fighter
   4510 4520
   #Air Transports
   4250 4260
   #AEW&C
   4450 #4180
   #Air-to-Ground Missiles
   4040
   #Air-to-Air Missiles
   4600
   #Air-to-Sea Missiles
   4740
   ###################
   #    Industry     #
   ###################
   #Light Industry
   5810 5820
   #Heavy Industry
   5130 5110
   #Material Science
   53050 63160 63070
   #Construction Eng.
   5800 5080
   #Rocketry
   5560 5910
   #Agriculture
   5700 5710 5010
   #Oil
   5190 5220
   #Computing
   5310 54010 54020
   #Nuclear
   5470 5480 5490
   #Research
   5316
   #Cryptography
   5350 5360
   #Medicine
   5600 5610
   5630
   5660 5730
   ###################
   #  Land Doctrines #
   ###################
   6500 
   6510 6530 
   1650
   6560 #Defensive
   ###################
   # Naval Doctrines #
   ###################
   #Surface Ship Role
   81050 81060 81070 81080 81090 81100 81110 81120
   #Naval Interdiction
   8500 8510 8520 8550 8560 8570 8600 8610 8620
   #Naval Supremacy
   8100 8110 8150 8120 8160 8170 8200 8210 8220
   #Logistics Support
   82500 82510 82520 82530
   #Naval Capability
   8010
   #Amphibious Warfare
   82300
   ###################
   #  Air Doctrines  #
   ###################
   9390 9260 9400 9410
   9090 9100 9110 9120 9050 9060 9070
   9190 9200 9210 9220 9310 9320 9330 9340 9230 9240 9250
   9130 9420 9300
   }
	inventions = {  }
	SpyInfo                = {  country = "TUR" NumberOfSpies = 9  }
	  
	diplomacy = {}
	  
	headofstate            = {  type = 9 id = 45001  } 
	headofgovernment       = {  type = 9 id = 45002  } 
	foreignminister        = {  type = 9 id = 45003  } 
	armamentminister       = {  type = 9 id = 45004  } 
	ministerofsecurity     = {  type = 9 id = 45005  } 
	ministerofintelligence = {  type = 9 id = 45006  } 
	chiefofstaff           = {  type = 9 id = 45007  } 
	chiefofarmy            = {  type = 9 id = 45008  } 
	chiefofnavy            = {  type = 9 id = 45009  } 
	chiefofair             = {  type = 9 id = 45010  } 

	##########################
	#
    # TURKEY OOB
	#
	 ###########################
	  landunit =
   {  id       = {  type = 11700 id = 1  } 			
     name     = "1st Army"
     location = 409 
     division = 
     { id       = {  type = 11700 id = 2  } 
       name     = "1st Army HQ" 
       type     = hq 
       model    = 5 
       strength = 100 
       extra    = armored_car
       brigade_model = 2
      }
	division =
     {  id    = {  type = 11700 id = 3  }
       name  = "3rd Mechanized Division"
       type     = mechanized
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 4  }
       name  = "66th Mechanized Division"
       type     = mechanized
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 5  }
       name  = "2nd Infantry Division"
       type     = infantry
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 6  }
       name  = "4th Infantry Division"
       type     = infantry
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 7  }
       name  = "6th Infantry Division"
       type     = infantry
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 8  }
       name  = "8th Infantry Division"
       type     = infantry
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 9  }
       name  = "23rd Infantry Division"
       type     = infantry
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 10  }
       name  = "33rd Infantry Division"
       type     = infantry
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 11  }
       name  = "61st Infantry Division"
       type     = infantry
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 12  }
       name  = "65th Infantry Division"
       type     = infantry
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 13  }
       name  = "1st Mechanized Brigade"
       type     = d_06
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 14  }
       name  = "2nd Mechanized Brigade"
       type     = d_06
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 15  }
       name  = "3rd Mechanized Brigade"
       type     = d_06
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 16  }
       name  = "41st Infantry Brigade"
       type     = d_01
       model    = 5
       strength = 100
      }
	}
	######################
		 landunit =
   {  id       = {  type = 11700 id = 17  } 			
     name     = "2nd Army"
     location = 442
	  division = 
     { id       = {  type = 11700 id = 18  } 
       name     = "2ndt Army HQ" 
       type     = hq 
       model    = 5 
       strength = 100 
       extra    = armored_car
       brigade_model = 2
      }
     division =
     {  id    = {  type = 11700 id = 19  }
       name  = "5th Armored Division"
       type     = armor
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 20  }
       name  = "16th Mechanized Division"
       type     = mechanized
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 21  }
       name  = "20th Mechanized Division"
       type     = mechanized
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 22  }
       name  = "39th Infantry Division"
       type     = infantry
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 23  }
       name  = "70th Infantry Division"
       type     = infantry
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 24  }
       name  = "21st Motorized Brigade"
       type     = d_02
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 25  }
       name  = "22nd Motorized Brigade"
       type     = d_02
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 26  }
       name  = "23rd Motorized Brigade"
       type     = d_02
       model    = 5
       strength = 100
      }
	}
    ######################
		 landunit =
   {  id       = {  type = 11700 id = 27  } 			
     name     = "3rd Army"
     location = 4122
      division = 
     { id       = {  type = 11700 id = 28  } 
       name     = "3rd Army HQ" 
       type     = hq 
       model    = 5 
       strength = 100 
       extra    = armored_car
       brigade_model = 2
      }
	  division =
     {  id    = {  type = 11700 id = 29  }
       name  = "9th Infantry Division"
       type     = infantry
       model    = 5
       strength = 100
      } 
	  division =
     {  id    = {  type = 11700 id = 30  }
       name  = "12th Infantry Division"
       type     = infantry
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 31  }
       name  = "29th Infantry Division"
       type     = infantry
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 32  }
       name  = "51st Infantry Division"
       type     = infantry
       model    = 5
       strength = 100
      }
	division =
     {  id    = {  type = 11700 id = 34  }
       name  = "4th Armored Division"
       type     = armor
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 35  }
       name  = "1st Mechanized Brigade"
       type     = d_06
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 36  }
       name  = "14th Mechanized Brigade"
       type     = d_06
       model    = 5
       strength = 100
      }
	   division =
     {  id    = {  type = 11700 id = 37  }
       name  = "10th Infantry Brigade"
       type     = d_01
       model    = 5
       strength = 100
      }
	   division =
     {  id    = {  type = 11700 id = 38  }
       name  = "48th Infantry Brigade"
       type     = d_01
       model    = 5
       strength = 100
      }
	   division =
     {  id    = {  type = 11700 id = 39  }
       name  = "49th Infantry Brigade"
       type     = d_01
       model    = 5
       strength = 100
      }
	   division =
     {  id    = {  type = 11700 id = 40  }
       name  = "51st Infantry Brigade"
       type     = d_01
       model    = 5
       strength = 100
      }
	}
	######################
		 landunit =
   {  id       = {  type = 11700 id = 41  } 			
     name     = "4th Army"
     location = 2611
      division = 
     { id       = {  type = 11700 id = 42  } 
       name     = "4th Army HQ" 
       type     = hq 
       model    = 5 
       strength = 100 
       extra    = armored_car
       brigade_model = 2
      }
	 division =
     {  id    = {  type = 11700 id = 43  }
       name  = "28th Infantry Division"
       type     = infantry
       model    = 5
       strength = 100
      } 
	  division =
     {  id    = {  type = 11700 id = 44  }
       name  = "39th Infantry Division"
       type     = infantry
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 45  }
       name  = "11th Infantry Brigade"
       type     = d_01
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 46  }
       name  = "19th Infantry Brigade"
       type     = d_01
       model    = 5
       strength = 100
      }
	}
	######################
		 landunit =
   {  id       = {  type = 11700 id = 47  } 			
     name     = "Ankara Army HQ"
     location = 2611
      division = 
     { id       = {  type = 11700 id = 48  } 
       name     = "Ankara Army HQ" 
       type     = hq 
       model    = 5 
       strength = 100 
       extra    = armored_car
       brigade_model = 2
      }
	 division =
     {  id    = {  type = 11700 id = 49  }
       name  = "15th Infantry Division"
       type     = infantry
       model    = 5
       strength = 100
      } 
	  division =
     {  id    = {  type = 11700 id = 50  }
       name  = "28th Infantry Division"
       type     = infantry
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 51  }
       name  = "62nd Special Forces Brigade"
       type     = d_03
       model    = 5
       strength = 100
      }
	  division =
     {  id    = {  type = 11700 id = 52  }
       name  = "1st Airborne Brigade"
       type     = d_08
       model    = 5
       strength = 100
      }
	}
# #################
    # ### AIR OOB  ####
    # #################
	airunit = {
	id = { type = 11700 id = 53 }
	name = "1st Ana Hava Us"
	location = 448 
	base = 448 
	division = {
	id = { type = 11700 id = 54 }
		name = "No 111 Filo"
		strength = 100
		type = interceptor
		model = 5
			}
	division = {
	id = { type = 11700 id = 55 }
		name = "No 112 Filo"
		strength = 100
		type = interceptor
		model = 5
	}
	division = {
	id = { type = 11700 id = 56 }
		name = "No 113 Filo"
		strength = 100
		type = cas
		model = 5
		}
	}
################
airunit = {
	id = { type = 11700 id = 57 }
	name = "4th Ana Hava Us"
	location = 448 
	base = 448 
	division = {
	id = { type = 11700 id = 58 }
		name = "No 141 Filo"
		strength = 100
		type = interceptor
		model = 5
			}
	division = {
	id = { type = 11700 id = 59 }
		name = "No 142 Filo"
		strength = 100
		type = interceptor
		model = 5
		}
	}
################
airunit = {
	id = { type = 11700 id = 60 }
	name = "5th Ana Hava Us"
	location = 439 
	base = 439 
	division = {
	id = { type = 11700 id = 61 }
		name = "No 151 Filo"
		strength = 100
		type = multi_role
		model = 7
			}
	division = {
	id = { type = 11700 id = 62 }
		name = "No 152 Filo"
		strength = 100
		type = multi_role
		model = 7
		}
		division = {
	id = { type = 11700 id = 63 }
		name = "No 153 Filo"
		strength = 100
		type = multi_role
		model = 7
		}
		division = {
	id = { type = 11700 id = 64 }
		name = "No 184 Filo"
		strength = 100
		type = multi_role
		model = 7
		}
	}
################
airunit = {
	id = { type = 11700 id = 65 }
	name = "4th Ana Hava Us"
	location = 439 
	base = 439 
	division = {
	id = { type = 11700 id = 66 }
		name = "No 161 Filo"
		strength = 100
		type = interceptor
		model = 5
			}
	division = {
	id = { type = 11700 id = 67 }
		name = "No 162 Filo"
		strength = 100
		type = interceptor
		model = 5
		}
	}
################
airunit = {
	id = { type = 11700 id = 68 }
	name = "7th Ana Hava Us"
	location = 439 
	base = 439 
	division = {
	id = { type = 11700 id = 69 }
		name = "No 171 Filo"
		strength = 100
		type = interceptor
		model = 5
			}
	division = {
	id = { type = 11700 id = 70 }
		name = "No 172 Filo"
		strength = 100
		type = interceptor
		model = 5
		}
	division = {
	id = { type = 11700 id = 71 }
		name = "No 173 Filo"
		strength = 100
		type = interceptor
		model = 5
		}
	}
################
airunit = {
	id = { type = 11700 id = 72 }
	name = "4th Ana Hava Us"
	location = 448 
	base = 448 
	division = {
	id = { type = 11700 id = 73 }
		name = "No 181 Filo"
		strength = 100
		type = interceptor
		model = 5
			}
	division = {
	id = { type = 11700 id = 74 }
		name = "No 182 Filo"
		strength = 100
		type = interceptor
		model = 5
		}
	}
################
airunit = {
	id = { type = 11700 id = 75 }
	name = "9th Ana Hava Us"
	location = 448 
	base = 448 
	division = {
	id = { type = 11700 id = 76 }
		name = "No 191 Filo"
		strength = 100
		type = interceptor
		model = 5
			}
	division = {
	id = { type = 11700 id = 77 }
		name = "No 192 Filo"
		strength = 100
		type = interceptor
		model = 5
		}
	}
}