#####################
# Country main data #
#####################

country =
{ tag                    = ALB
  manpower               = 100
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 10
  capital                = 390
  policy =
  { date              = { year = 0 month = january day = 0 }
     democratic        = 3 
     political_left    = 4 
     free_market       = 7 
     freedom           = 5 
     professional_army = 5 
     defense_lobby     = 4 
     interventionism   = 1
  }
  nationalprovinces      = { 390 391 415 665 664 1169 3372 2609 3393 5465 5466 6562 413 7163 7961 7315 7936 }
  ownedprovinces         = { 390 391 665 664 5465 5466 7163 7961 7936 }
  controlledprovinces    = { 390 391 665 664 5465 5466 7163 7961 7936 }
  claimedprovinces 		 = { 392 393 7269 7270 7316 }
  
  diplomacy =
  { relation = { tag = ITA value = 10 }
  }
  headofstate            = { type = 9 id = 32001 }
  headofgovernment       = { type = 9 id = 32002 }
  foreignminister        = { type = 9 id = 32003 }
  armamentminister       = { type = 9 id = 32004 }
  ministerofsecurity     = { type = 9 id = 32005 }
  ministerofintelligence = { type = 9 id = 32006 }
  chiefofstaff           = { type = 9 id = 32007 }
  chiefofarmy            = { type = 9 id = 32008 }
  chiefofnavy            = { type = 9 id = 32009 }
  chiefofair             = { type = 9 id = 32010 }
}