
##############################
# Country definition for CYP #
##############################

country =
{ tag                 = CYP
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 10
  capital             = 444
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 8
    political_left    = 7
    freedom           = 8
    free_market       = 7
    professional_army = 1
    defense_lobby     = 8
    interventionism   = 6
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  ownedprovinces      = {
		444
	}
  controlledprovinces = {
		444
	}
  nationalprovinces   = {
		444 418 5412 5413
	}
	
}