
##################################
# Country definition for Iceland #
##################################

country =
{ tag                 = ICL
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 500
  supplies            = 5000
  money               = 100
  capital             = 1
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 4
    freedom           = 10
    free_market       = 9
    professional_army = 7
    defense_lobby     = 8
    interventionism   = 4
  }
  diplomacy = { 
	relation = { tag = USA value = 100 }
	}
  ownedprovinces      = { 1 7137 2632 7138 7139 }
  controlledprovinces = { 1 7137 2632 7138 7139 }
  nationalprovinces   = { 1 7137 2632 7138 7139 }
  
   headofstate            = {  type = 9 id = 360001  } 
   headofgovernment       = {  type = 9 id = 360002  } 
   foreignminister        = {  type = 9 id = 360003  } 
   armamentminister       = {  type = 9 id = 360004  } 
   ministerofsecurity     = {  type = 9 id = 360005  } 
   ministerofintelligence = {  type = 9 id = 360006  } 
   chiefofstaff           = {  type = 9 id = 360007  } 
   chiefofarmy            = {  type = 9 id = 360008  } 
   chiefofnavy            = {  type = 9 id = 360009  } 
   chiefofair             = {  type = 9 id = 360010  } 

}