################################
# Country definition for Malta #
################################

country =
{ tag                 = U92
  energy              = 100
  metal               = 100
  rare_materials      = 500
  oil                 = 50
  supplies            = 500
  money               = 100
  capital             = 31
  manpower            = 100
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 4
    freedom           = 10
    free_market       = 10
    professional_army = 9
    defense_lobby     = 8
    interventionism   = 1
  }
  diplomacy = { 
	relation = { tag = USA value = 25 }
	}
  ownedprovinces      = { 31 }
  controlledprovinces = { 31 }
  nationalprovinces   = { 31 }

}