#####################
# Country main data #
#####################

country =
{ tag                    = POR
  # Resource Reserves
  energy                 = 10000
  metal                  = 10000
  rare_materials         = 5000
  oil                    = 1000
  supplies               = 5000
  money                  = 4000
  capital                = 336
  manpower               = 200
  transports             = 50
  escorts                = 7

  diplomacy = {}
  
  SpyInfo                = { country = "ENG" NumberOfSpies = 3 }
  SpyInfo                = { country = "FRA" NumberOfSpies = 2 }
  SpyInfo                = { country = "SPR" NumberOfSpies = 4 }
  SpyInfo                = { country = "ARG" NumberOfSpies = 3 }
  SpyInfo                = { country = "ITA" NumberOfSpies = 1 }
  SpyInfo                = { country = "BRA" NumberOfSpies = 4 }
  SpyInfo                = { country = "MEX" NumberOfSpies = 1 }
  # Cabinda
  nationalprovinces      = { 335 336 337 344 345 1867 1563 1163 965 3206 3207 3208 3209 3210 3211 3212 1036 6492
7166 7167 7257 7258 7981
  }
  ownedprovinces         = { 335 336 337 344 345 1867 1563 1163 965 3206 3207 3208 3209 3210 3211 3212 1036 6492
7166 7167 7257 7258
  }
  controlledprovinces    = { 335 336 337 344 345 1867 1563 1163 965 3206 3207 3208 3209 3210 3211 3212 1036 6492
7166 7167 7257 7258
  }

  inventions = {  }
  policy =
  { date              = { year = 0 month = january day = 0 }
     democratic        = 10 
     political_left    = 10 
     freedom           = 10 
     free_market       = 10 
     professional_army = 3 
     defense_lobby     = 4 
     interventionism   = 4
  }
  headofstate            = { type = 9 id = 9001 }
  headofgovernment       = { type = 9 id = 9002 }
  foreignminister        = { type = 9 id = 9003 }
  armamentminister       = { type = 9 id = 9004 }
  ministerofsecurity     = { type = 9 id = 9005 }
  ministerofintelligence = { type = 9 id = 9006 }
  chiefofstaff           = { type = 9 id = 9007 }
  chiefofarmy            = { type = 9 id = 9008 }
  chiefofnavy            = { type = 9 id = 9009 }
  chiefofair             = { type = 9 id = 9010 }
}