#####################
# Country main data #
#####################

country =
{ tag                    = SWE
  # Resource Reserves
  energy                 = 1000
  metal                  = 1000
  rare_materials         = 500
  oil                    = 500
  supplies               = 500
  money                  = 20
  manpower               = 200
  capital                = 101
  diplomacy =
  { relation = { tag = BEL value = 100 }
    relation = { tag = DEN value = 75 }
    relation = { tag = ENG value = 80 }
    relation = { tag = FIN value = 150 }
    relation = { tag = GER value = 50 }
    relation = { tag = HOL value = 100 }
    relation = { tag = LUX value = 100 }
    relation = { tag = NOR value = 150 }
    relation = { tag = PER value = 50 }
    relation = { tag = USA value = 75 }
  }
  SpyInfo                = { country = "ENG" NumberOfSpies = 3 }
  SpyInfo                = { country = "EST" NumberOfSpies = 1 }
  SpyInfo                = { country = "SOV" NumberOfSpies = 2 }
  SpyInfo                = { country = "POL" NumberOfSpies = 2 }
  SpyInfo                = { country = "NOR" NumberOfSpies = 4 }
  SpyInfo                = { country = "FIN" NumberOfSpies = 2 }
  SpyInfo                = { country = "DEN" NumberOfSpies = 3 }
  SpyInfo                = { country = "LAT" NumberOfSpies = 1 }
  SpyInfo                = { country = "LIT" NumberOfSpies = 1 }
  SpyInfo                = { country = "GER" NumberOfSpies = 2 }
  SpyInfo                = { country = "FRA" NumberOfSpies = 3 }
  nationalprovinces      = {  126 127   121  119 115 113  106 105   101 100 99 98 97 93  96 103
2629
3300	3301	3302	3303	3304	3305	3306	3307	3308	3309
3311	3312	3313	3314	3315	3316	3317	3318	3319	3320	3321	3322
6528 6529 6530 6531 6532
7168 7169 7451 7452 7453 7454
  }
  ownedprovinces         = {  126 127   121  119 115 113  106 105   101 100 99 98 97 93  96
  3300	3301	3302	3303	3304	3305	3306	3307	3308	3309
3311	3312	3313	3314	3315	3316	3317	3318	3319	3320	3321	3322
6528 6529 6530 6531 6532
2629
7168 7169 7451 7452 7453 7454
  }
  controlledprovinces    = {  126 127   121  119 115 113  106 105   101 100 99 98 97 93  96
  3300	3301	3302	3303	3304	3305	3306	3307	3308	3309
3311	3312	3313	3314	3315	3316	3317	3318	3319	3320	3321	3322
6528 6529 6530 6531 6532
2629
7168 7169 7451 7452 7453 7454
  }

  inventions = {  }
  policy =
  { date              = { year = 0 month = january day = 0 }
     democratic        = 10 
     political_left    = 10 
     freedom           = 6 
     free_market       = 7 
     professional_army = 3 
     defense_lobby     = 5 
     interventionism   = 4
  }
  headofstate            = { type = 9 id = 7001 }
  headofgovernment       = { type = 9 id = 7033 }
  foreignminister        = { type = 9 id = 7038 }
  armamentminister       = { type = 9 id = 7047 }
  ministerofsecurity     = { type = 9 id = 7058 }
  ministerofintelligence = { type = 9 id = 7006 }
  chiefofstaff           = { type = 9 id = 7007 }
  chiefofarmy            = { type = 9 id = 7008 }
  chiefofnavy            = { type = 9 id = 7009 }
  chiefofair             = { type = 9 id = 7010 }
}